classdef SourceModel < handle
    %SOURCEMODEL  Parsed view of a MATLAB source file.
    %
    %   A SourceModel is the language-agnostic intermediate produced by the
    %   parsers and consumed by autotest.TestWriter.  It captures only what
    %   is needed for test generation; it is intentionally not a full AST.

    properties
        Kind              (1,:) char  = 'function'  % 'function' | 'classdef' | 'app'
        SourcePath        (1,:) char  = ''
        SourceName        (1,:) char  = ''           % stem, no extension
        ClassName         (1,:) char  = ''           % when Kind ~= 'function'
        SuperClasses      (1,:) cell  = {}
        Functions         (1,:) struct = autotest.SourceModel.emptyFcn()
        Methods           (1,:) struct = autotest.SourceModel.emptyFcn()
        Properties        (1,:) struct = autotest.SourceModel.emptyProp()
        Callbacks         (1,:) struct = autotest.SourceModel.emptyCallback()
        Components        (1,:) struct = autotest.SourceModel.emptyComponent()
        ConstructorArgs   (1,:) cell  = {}
        IsHandle          (1,1) logical = false
    end

    methods (Static)
        function s = emptyFcn()
            s = struct('Name', {}, 'Inputs', {}, 'Outputs', {}, ...
                'IsStatic', {}, 'IsPublic', {}, 'HasVarargin', {}, ...
                'HasVarargout', {}, 'HelpText', {}, 'Examples', {}, ...
                'ArgumentBlocks', {});
        end

        function s = emptyProp()
            s = struct('Name', {}, 'Access', {}, 'SetAccess', {}, ...
                'Type', {}, 'Default', {}, 'IsDependent', {}, ...
                'IsConstant', {});
        end

        function s = emptyCallback()
            s = struct('Name', {}, 'ComponentTag', {}, ...
                'EventName', {}, 'Inputs', {});
        end

        function s = emptyComponent()
            s = struct('Tag', {}, 'Type', {});
        end

        function f = makeFcn(name)
            f = struct( ...
                'Name', name, ...
                'Inputs', {{}}, ...
                'Outputs', {{}}, ...
                'IsStatic', false, ...
                'IsPublic', true, ...
                'HasVarargin', false, ...
                'HasVarargout', false, ...
                'HelpText', '', ...
                'Examples', {{}}, ...
                'ArgumentBlocks', {{}});
        end

        function p = makeProp(name)
            p = struct( ...
                'Name', name, ...
                'Access', 'public', ...
                'SetAccess', 'public', ...
                'Type', '', ...
                'Default', '', ...
                'IsDependent', false, ...
                'IsConstant', false);
        end

        function c = makeCallback(name)
            c = struct( ...
                'Name', name, ...
                'ComponentTag', '', ...
                'EventName', '', ...
                'Inputs', {{}});
        end

        function c = makeComponent(tag, 