classdef TestWriter < handle
    %TESTWRITER  Emits a matlab.unittest.TestCase subclass from a SourceModel.
    %
    %   The generator strategy is:
    %     1. Always emit a "Existence" test that the function/class is
    %        resolvable on the MATLAB path.
    %     2. For functions, emit one Test method per smoke case and per
    %        edge case derived from autotest.InputSampler.  Each test
    %        verifies the call does not throw, that nargout outputs are
    %        produced when expected, and that numeric outputs are finite
    %        for smoke inputs.
    %     3. For classdef, emit a TestMethodSetup that constructs the
    %        object (with default args), property get/set tests, and per-
    %        method invocations.  Handle classes are wrapped in cleanup.
    %     4. For App Designer apps, emit a launch/teardown pair plus per-
    %        callback invocation tests via findComponentByTag helpers.
    %     5. Each "Example:" block found in help text is materialised as a
    %        Test method that runs the example expression and verifies it
    %        does not throw.

    properties (SetAccess = immutable)
        Model    autotest.SourceModel
        Options  % autotest.TestGenerator
    end

    properties (Access = private, Transient)
        % Phase 7 (Option 1) marker: set true by
        % maybeEmitKnownRealSignalSkip when a skip was emitted, read by
        % lastWasSkip so the caller can short-circuit and avoid emitting
        % the would-be normal test.  Reset on every maybeEmit call.
        LastEmittedSkip (1,1) logical = false
    end

    methods
        function obj = TestWriter(model, options)
            obj.Model = model;
            obj.Options = options;
        end

        function writeTo(obj, filePath)
            src = obj.buildSource();
            fid = fopen(filePath, 'w');
            if fid < 0
                error('autotest:WriteFailed', 'Cannot write %s', filePath);
            end
            cleaner = onCleanup(@() fclose(fid));
            fwrite(fid, src);
        end

        function written = writeUserStubTo(obj, filePath, className)
            % Emit a hand-edit-friendly stub at FILEPATH iff it does not
            % already exist.  Returns true if a new file was written, false
            % if an existing stub was preserved.  The stub contains one
            % `userTest_<name>` Test method per public function / method /
            % property / callback found in the model, each prefilled with
            % `assumeFail` so it shows as Incomplete until the user
            % replaces it with real assertions.
            if isfile(filePath)
                written = false;
                return
            end
            src = obj.buildUserStubSource(className);
            fid = fopen(filePath, 'w');
            if fid < 0
                error('autotest:WriteFailed', 'Cannot write %s', filePath);
            end
            cleaner = onCleanup(@() fclose(fid));
            fwrite(fid, src);
            written = true;
        end

        function src = buildSource(obj)
            buf = strings(0,1);
            tw = obj.Options;
            cls = tw.TestClassName;

            buf(end+1,1) = string(sprintf('classdef %s < matlab.unittest.TestCase', cls));
            buf(end+1,1) = "    %% Auto-generated by autotest.TestGenerator.";
            buf(end+1,1) = "    %% DO NOT EDIT BY HAND -- regenerate with generateTests().";
            buf(end+1,1) = "";
            buf(end+1,1) = "    properties (Constant, Access = private)";
            buf(end+1,1) = string(sprintf('        SourcePath = ''%s'';', ...
                autotest.TestWriter.escapeCharLiteral(obj.Model.SourcePath)));
            buf(end+1,1) = "    end";
            buf(end+1,1) = "";
            buf = obj.appendSetup(buf);

            switch obj.Model.Kind
                case 'function'
                    buf = obj.appendFunctionTests(buf);
                case 'classdef'
                    buf = obj.appendClassTests(buf);
                case 'app'
                    buf = obj.appendAppTests(buf);
                otherwise
                    buf(end+1,1) = "    methods (Test)";
                    buf(end+1,1) = "        function testFileExists(testCase)";
                    buf(end+1,1) = "            testCase.verifyTrue(isfile(testCase.SourcePath));";
                    buf(end+1,1) = "        end";
                    buf(end+1,1) = "    end";
            end

            buf = obj.appendHelpers(buf);
            buf(end+1,1) = "end";
            % NOTE: bracket-concat, NOT `+`.  `char(...) + newline`
            % promotes both operands to double and adds 10 to every byte
            % (numeric addition), producing a garbled file that MATLAB
            % cannot load as a classdef.
            src = [char(strjoin(buf, newline)) newline];
        end

        function src = buildUserStubSource(obj, className)
            % Build a placeholder classdef the user can hand-edit.  Each
            % public surface gets ONE Test method whose body is just an
            % `assumeFail` and a comment showing the signature and a
            % template assertion.  Replace `assumeFail` with real
            % `verifyEqual`/`verifyTrue` calls when you're ready.
            buf = strings(0,1);
            buf(end+1,1) = string(sprintf('classdef %s < matlab.unittest.TestCase', className));
            buf(end+1,1) = "    %% USER tests for " + string(obj.Model.SourceName) + ".";
            buf(end+1,1) = "    %%";
            buf(end+1,1) = "    %% This file is YOURS to edit.  autotestGUI / generateTests";
            buf(end+1,1) = "    %% will NEVER overwrite an existing user_tests/u<Name>.m.";
            buf(end+1,1) = "    %% The matching tXxx.m under generated/ is regenerated every";
            buf(end+1,1) = "    %% run and covers the basic 'doesn''t throw' smoke + edge";
            buf(end+1,1) = "    %% cases; this file is where you encode 'for input X, expected";
            buf(end+1,1) = "    %% output Y'.";
            buf(end+1,1) = "    %%";
            buf(end+1,1) = "    %% Each stub starts with `assumeFail` so it shows as Incomplete";
            buf(end+1,1) = "    %% in the test report.  Delete that line and add real";
            buf(end+1,1) = "    %% verify*/assert* calls when you implement the test.";
            buf(end+1,1) = "";
            buf(end+1,1) = "    properties (Constant, Access = private)";
            buf(end+1,1) = string(sprintf('        SourcePath = ''%s'';', ...
                autotest.TestWriter.escapeCharLiteral(obj.Model.SourcePath)));
            buf(end+1,1) = "    end";
            buf(end+1,1) = "";
            switch obj.Model.Kind
                case 'classdef'
                    buf(end+1,1) = "    properties";
                    buf(end+1,1) = "        Instance  %% TODO: assign in setup if your tests need it";
                    buf(end+1,1) = "    end";
                    buf(end+1,1) = "";
                case 'app'
                    buf(end+1,1) = "    properties";
                    buf(end+1,1) = "        App  %% TODO: assign in setup (testCase.App = " + ...
                        string(obj.Model.ClassName) + ";)";
                    buf(end+1,1) = "    end";
                    buf(end+1,1) = "";
            end
            buf = obj.appendStubSetup(buf);
            buf = obj.appendStubTests(buf);
            buf(end+1,1) = "end";
            src = [char(strjoin(buf, newline)) newline];
        end
    end

    methods (Access = private)
        function buf = appendStubSetup(obj, buf)
            buf(end+1,1) = "    methods (TestMethodSetup)";
            buf(end+1,1) = "        function addSourceToPath(testCase)";
            buf(end+1,1) = "            srcDir = fileparts(testCase.SourcePath);";
            buf(end+1,1) = "            if ~isempty(srcDir) && exist(srcDir, 'dir')";
            buf(end+1,1) = "                addpath(srcDir);";
            buf(end+1,1) = "                testCase.addTeardown(@() rmpath(srcDir));";
            buf(end+1,1) = "            end";
            switch obj.Model.Kind
                case 'classdef'
                    buf(end+1,1) = "            %% --- Constructor template ---";
                    buf(end+1,1) = "            %% Uncomment + fill in the args needed by your class:";
                    buf(end+1,1) = "            %%   testCase.Instance = " + ...
                        string(obj.Model.ClassName) + "(/* args */);";
                    buf(end+1,1) = "            %% If it's a handle class, also wire teardown:";
                    buf(end+1,1) = "            %%   inst = testCase.Instance;";
                    buf(end+1,1) = "            %%   testCase.addTeardown(@() delete(inst));";
                case 'app'
                    buf(end+1,1) = "            %% --- App launch template ---";
                    buf(end+1,1) = "            %%   testCase.App = " + ...
                        string(obj.Model.ClassName) + ";";
                    buf(end+1,1) = "            %%   app = testCase.App;";
                    buf(end+1,1) = "            %%   testCase.addTeardown(@() delete(app));";
            end
            buf(end+1,1) = "        end";
            buf(end+1,1) = "    end";
            buf(end+1,1) = "";
        end

        function buf = appendStubTests(obj, buf)
            buf(end+1,1) = "    methods (Test)";
            switch obj.Model.Kind
                case 'function'
                    for k = 1:numel(obj.Model.Functions)
                        f = obj.Model.Functions(k);
                        if isfield(f, 'IsPublic') && ~f.IsPublic, continue; end
                        buf = obj.appendOneStub(buf, f.Name, ...
                            obj.fnSignature(f), ...
                            sprintf('actual = %s(/* args */);', f.Name), ...
                            'testCase.verifyEqual(actual, expected);');
                    end
                case 'classdef'
                    cls = obj.Model.ClassName;
                    for k = 1:numel(obj.Model.Methods)
                        m = obj.Model.Methods(k);
                        if isfield(m, 'IsPublic') && ~m.IsPublic, continue; end
                        if strcmp(m.Name, cls), continue; end
                        if m.IsStatic
                            sig  = sprintf('%s [static]: %s', cls, obj.fnSignature(m));
                            call = sprintf('actual = %s.%s(/* args */);', cls, m.Name);
                        else
                            sig  = sprintf('%s [instance]: %s', cls, obj.fnSignature(m));
                            call = sprintf('actual = testCase.Instance.%s(/* args */);', m.Name);
                        end
                        buf = obj.appendOneStub(buf, m.Name, sig, call, ...
                            'testCase.verifyEqual(actual, expected);');
                    end
                    for p = 1:numel(obj.Model.Properties)
                        prop = obj.Model.Properties(p);
                        if ~strcmpi(prop.Access, 'public'), continue; end
                        if prop.IsConstant, continue; end
                        sig  = sprintf('%s.%s (property)', cls, prop.Name);
                        call = sprintf('value = testCase.Instance.%s;', prop.Name);
                        buf = obj.appendOneStub(buf, ['prop_' prop.Name], sig, call, ...
                            'testCase.verifyEqual(value, expected);');
                    end
                case 'app'
                    buf = obj.appendOneStub(buf, 'appLaunches', ...
                        'App launches and is valid', ...
                        'app = testCase.App;', ...
                        'testCase.verifyTrue(isvalid(app));');
                    for k = 1:numel(obj.Model.Callbacks)
                        cb = obj.Model.Callbacks(k);
                        if isempty(cb.ComponentTag)
                            sig = sprintf('callback %s (no component bound)', cb.Name);
                        else
                            sig = sprintf('callback %s on tag "%s"', cb.Name, cb.ComponentTag);
                        end
                        buf = obj.appendOneStub(buf, ['cb_' cb.Name], sig, ...
                            sprintf('testCase.App.%s([], struct(''Source'', [], ''EventName'', ''Synthetic''));', cb.Name), ...
                            'testCase.verifyTrue(isvalid(testCase.App));');
                    end
            end
            buf(end+1,1) = "    end";
        end

        function buf = appendOneStub(~, buf, name, sigComment, callExample, verifyExample)
            methodName = matlab.lang.makeValidName(['userTest_' name]);
            buf(end+1,1) = string(sprintf('        function %s(testCase)', methodName));
            buf(end+1,1) = "            %% " + string(sigComment);
            buf(end+1,1) = "            %%";
            buf(end+1,1) = "            %% Replace this stub with real assertions, e.g.:";
            buf(end+1,1) = "            %%   " + string(callExample);
            buf(end+1,1) = "            %%   " + string(verifyExample);
            buf(end+1,1) = string(sprintf( ...
                '            testCase.assumeFail(''TODO: implement %s'');', methodName));
            buf(end+1,1) = "        end";
            buf(end+1,1) = "";
        end

        function s = fnSignature(~, f)
            inp = f.Inputs;
            if isempty(inp)
                inStr = '';
            else
                inStr = strjoin(inp, ', ');
            end
            out = f.Outputs;
            if isempty(out)
                s = sprintf('%s(%s)', f.Name, inStr);
            elseif numel(out) == 1
                s = sprintf('%s = %s(%s)', out{1}, f.Name, inStr);
            else
                s = sprintf('[%s] = %s(%s)', strjoin(out, ', '), f.Name, inStr);
            end
        end

        function buf = appendSetup(obj, buf)
            buf(end+1,1) = "    methods (TestMethodSetup)";
            buf(end+1,1) = "        function addSourceToPath(testCase)";
            buf(end+1,1) = "            srcDir = fileparts(testCase.SourcePath);";
            buf(end+1,1) = "            if ~isempty(srcDir) && exist(srcDir, 'dir')";
            buf(end+1,1) = "                addpath(srcDir);";
            buf(end+1,1) = "                testCase.addTeardown(@() rmpath(srcDir));";
            buf(end+1,1) = "            end";
            buf(end+1,1) = "        end";
            buf(end+1,1) = "    end";
            buf(end+1,1) = "";
        end

        function buf = appendFunctionTests(obj, buf)
            buf(end+1,1) = "    methods (Test)";

            % Existence + signature for the primary (first) function.
            if ~isempty(obj.Model.Functions)
                buf = obj.appendExistenceBlock(buf, obj.Model.Functions(1).Name);
            end

            for k = 1:numel(obj.Model.Functions)
                fcn = obj.Model.Functions(k);
                if ~fcn.IsPublic, continue; end
                buf = obj.appendFunctionMethods(buf, fcn, 'function');
            end
            buf(end+1,1) = "    end";
            buf(end+1,1) = "";
        end

        function buf = appendClassTests(obj, buf)
            cls = obj.Model.ClassName;
            % Resolve constructor arguments via the FixtureProvider when one
            % is wired in.  For classes whose ctor signature is satisfied by
            % the project's fixtures (paths, regex strings, GUI handles,
            % etc.) this flips constructInstance from "assumeFail" to a real
            % handle, which in turn unblocks every property/method test on
            % the class.  Falls back to a no-arg call when smartFor returns
            % empty -- preserves behaviour for ctors with no arguments.
            ctor = obj.findConstructor();
            ctorHelp = '';
            if ~isempty(ctor) && isfield(ctor, 'HelpText')
                ctorHelp = ctor.HelpText;
            end
            ctorArgs = '';
            provider = [];
            if ~isempty(obj.Options) && isprop(obj.Options, 'FixtureProvider')
                provider = obj.Options.FixtureProvider;
            end
            if ~isempty(provider) && isa(provider, 'autotest.FixtureProvider') ...
                    && ~isempty(ctor) && ~isempty(ctor.Inputs)
                ctorCases = autotest.InputSampler.smartFor( ...
                    ctor.Inputs, ctor.ArgumentBlocks, ctorHelp, provider);
                if ~isempty(ctorCases)
                    ctorArgs = ctorCases(1).Expr;
                end
            end

            buf(end+1,1) = "    properties (Access = private)";
            buf(end+1,1) = "        Instance";
            buf(end+1,1) = "    end";
            buf(end+1,1) = "";
            buf(end+1,1) = "    methods (TestMethodSetup)";
            buf(end+1,1) = "        function constructInstance(testCase)";
            buf(end+1,1) = "            % Belt-and-suspenders: ensure the source directory is on";
            buf(end+1,1) = "            % the path even if MATLAB happens to run this setup before";
            buf(end+1,1) = "            % addSourceToPath (cross-block TestMethodSetup ordering is";
            buf(end+1,1) = "            % undefined; declaration order is only guaranteed within a";
            buf(end+1,1) = "            % single methods block).";
            buf(end+1,1) = "            srcDir = fileparts(testCase.SourcePath);";
            buf(end+1,1) = "            if ~isempty(srcDir) && exist(srcDir, 'dir')";
            buf(end+1,1) = "                addpath(srcDir);";
            buf(end+1,1) = "            end";
            buf(end+1,1) = "            try";
            buf(end+1,1) = string(sprintf('                testCase.Instance = %s(%s);', cls, ctorArgs));
            if obj.Model.IsHandle
                buf(end+1,1) = "                inst = testCase.Instance;";
                buf(end+1,1) = "                testCase.addTeardown(@() testCase.safeDelete(inst));";
            end
            buf(end+1,1) = "            catch ME";
            buf(end+1,1) = "                testCase.assumeFail(sprintf( ...";
            buf(end+1,1) = string(sprintf('                    ''%s constructor threw: %%s'', ME.message));', cls));
            buf(end+1,1) = "            end";
            buf(end+1,1) = "        end";
            buf(end+1,1) = "    end";
            buf(end+1,1) = "";

            buf(end+1,1) = "    methods (Test)";
            buf = obj.appendExistenceBlock(buf, cls);

            % Constructor test using positional smoke samples.
            ctor = obj.findConstructor();
            if ~isempty(ctor)
                buf = obj.appendConstructorTests(buf, ctor);
            end

            % Property get/set tests.
            for p = 1:numel(obj.Model.Properties)
                prop = obj.Model.Properties(p);
                if ~strcmpi(prop.Access, 'public'), continue; end
                if prop.IsConstant, continue; end
                buf = obj.appendPropertyTest(buf, prop);
            end

            % Method invocation tests.
            for k = 1:numel(obj.Model.Methods)
                m = obj.Model.Methods(k);
                if ~m.IsPublic, continue; end
                if strcmp(m.Name, cls), continue; end  % skip ctor here
                buf = obj.appendFunctionMethods(buf, m, ...
                    autotest.TestWriter.iif(m.IsStatic, 'static', 'method'));
            end
            buf(end+1,1) = "    end";
            buf(end+1,1) = "";
        end

        function buf = appendAppTests(obj, buf)
            cls = obj.Model.ClassName;
            buf(end+1,1) = "    properties (Access = private)";
            buf(end+1,1) = "        App";
            buf(end+1,1) = "    end";
            buf(end+1,1) = "";
            % CLASS-level setup/teardown: launch the app exactly ONCE per";
            % generated test class run.  Per-method launching opened a new";
            % UIFigure for every callback test, and on a real App Designer";
            % app those windows tend to outlive a per-method delete (the";
            % CloseRequestFcn or component teardown frequently throws and";
            % leaves the figure orphaned).  One-window-per-class is also";
            % faster.  Mid-test damage to app state is acceptable -- these";
            % are smoke tests, not state-isolated unit tests.
            buf(end+1,1) = "    methods (TestClassSetup)";
            buf(end+1,1) = "        function launchApp(testCase)";
            buf(end+1,1) = "            % Belt-and-suspenders: ensure the source directory is on";
            buf(end+1,1) = "            % the path even if MATLAB happens to run this setup before";
            buf(end+1,1) = "            % addSourceToPath.";
            buf(end+1,1) = "            srcDir = fileparts(testCase.SourcePath);";
            buf(end+1,1) = "            if ~isempty(srcDir) && exist(srcDir, 'dir')";
            buf(end+1,1) = "                addpath(srcDir);";
            buf(end+1,1) = "            end";
            buf(end+1,1) = "            % Snapshot the figures that exist BEFORE launch so the";
            buf(end+1,1) = "            % teardown can mop up any new windows the app spawned.";
            buf(end+1,1) = "            preFigs = findall(groot, 'Type', 'figure');";
            buf(end+1,1) = "            try";
            buf(end+1,1) = string(sprintf('                testCase.App = %s();', cls));
            buf(end+1,1) = "            catch ME";
            buf(end+1,1) = "                testCase.assumeFail(sprintf( ...";
            buf(end+1,1) = "                    'App launch threw: %s', ME.message));";
            buf(end+1,1) = "            end";
            buf(end+1,1) = "            app = testCase.App;";
            buf(end+1,1) = "            testCase.addTeardown(@() testCase.shutdownApp(app, preFigs));";
            buf(end+1,1) = "        end";
            buf(end+1,1) = "    end";
            buf(end+1,1) = "";

            buf(end+1,1) = "    methods (Test)";
            buf(end+1,1) = "        function testAppLaunches(testCase)";
            buf(end+1,1) = string(sprintf('            testCase.verifyClass(testCase.App, ''%s'');', cls));
            buf(end+1,1) = "            testCase.verifyTrue(isvalid(testCase.App));";
            buf(end+1,1) = "        end";
            buf(end+1,1) = "";
            buf(end+1,1) = "        function testAppHasUIFigure(testCase)";
            buf(end+1,1) = "            % Phase 9: check by TYPE (any property holding a uifigure";
            buf(end+1,1) = "            % handle) rather than by hardcoded NAME -- App Designer apps";
            buf(end+1,1) = "            % frequently rename the figure component (e.g.";
            buf(end+1,1) = "            % ReportRedactionToolUIFigure) so a name-only check is brittle.";
            buf(end+1,1) = "            pp = properties(testCase.App);";
            buf(end+1,1) = "            found = false;";
            buf(end+1,1) = "            for k = 1:numel(pp)";
            buf(end+1,1) = "                try";
            buf(end+1,1) = "                    v = testCase.App.(pp{k});";
            buf(end+1,1) = "                    if isscalar(v) && isa(v, 'matlab.ui.Figure')";
            buf(end+1,1) = "                        found = true;";
            buf(end+1,1) = "                        break;";
            buf(end+1,1) = "                    end";
            buf(end+1,1) = "                catch";
            buf(end+1,1) = "                end";
            buf(end+1,1) = "            end";
            buf(end+1,1) = "            testCase.verifyTrue(found, ...";
            buf(end+1,1) = "                'App has no property holding a matlab.ui.Figure handle');";
            buf(end+1,1) = "        end";

            if obj.Options.AppCallbackTests
                for k = 1:numel(obj.Model.Callbacks)
                    cb = obj.Model.Callbacks(k);
                    buf = obj.appendCallbackTest(buf, cb);
                end
            end

            % Property tests still apply.
            for p = 1:numel(obj.Model.Properties)
                prop = obj.Model.Properties(p);
                if ~strcmpi(prop.Access, 'public'), continue; end
                if prop.IsConstant, continue; end
                buf = obj.appendPropertyTest(buf, prop, 'App');
            end

            buf(end+1,1) = "    end";
            buf(end+1,1) = "";
        end

        function buf = appendExistenceBlock(~, buf, name)
            safe = matlab.lang.makeValidName(['testExists_' name]);
            buf(end+1,1) = string(sprintf('        function %s(testCase)', safe));
            buf(end+1,1) = string(sprintf('            testCase.verifyNotEmpty(which(''%s''), ...', name));
            buf(end+1,1) = string(sprintf('                ''%s is not on the MATLAB path'');', name));
            buf(end+1,1) = "        end";
            buf(end+1,1) = "";
        end

        function buf = appendFunctionMethods(obj, buf, fcn, kind)
            % Phase 2.4 (early gate): instance methods on stateful classes
            % (ctor leaves required container state empty) can't be
            % usefully smoke-tested by the autogenerator -- even
            % FixtureProvider-resolved inputs (`'Sheet1'` for a
            % `sheetName` arg) crash when the underlying SheetMap /
            % DomCache / Tables / Relationships dictionary is still
            % empty.  Emit a single testSkipped_<name> Incomplete
            % carrying the per-class StatefulReason and pointing at
            % user_tests/u<Class>.m::userTest_<method> -- that's the
            % hand-edit-friendly stub where the user encodes the real
            % "construct + populate state + assert" sequence.  Static
            % methods are left to the normal smoke/edge layer (they
            % don't depend on instance state).
            %
            % NOTE: the user's Phase 2.4 spec gated this on
            % `isempty(smart)`, on the assumption that smart-resolved
            % inputs would let the call succeed.  Empirically that's
            % wrong: smart resolves `sheetName` to `'Sheet1'` but the
            % method still fails because the instance dictionary is
            % empty.  Dropping the gate is the only way to actually move
            % those failures from Failed to Incomplete.  See
            % PHASE4_HANDOFF.md for the full rationale.
            if obj.Model.IsStateful && strcmp(kind, 'method')
                methodName = matlab.lang.makeValidName(['testSkipped_' fcn.Name]);
                msg = sprintf( ...
                    ['%s skipped: %s. See user_tests/u%s.m::userTest_%s' ...
                     ' for the hand-written assertion.'], ...
                    fcn.Name, obj.Model.StatefulReason, ...
                    obj.Model.ClassName, fcn.Name);
                escMsg = autotest.TestWriter.escapeCharLiteral(msg);
                buf(end+1,1) = string(sprintf('        function %s(testCase)', methodName));
                buf(end+1,1) = string(sprintf( ...
                    '            testCase.assumeFail(''%s'');', escMsg));
                buf(end+1,1) = "        end";
                buf(end+1,1) = "";
                return;
            end
            argBlocks = fcn.ArgumentBlocks;
            inputs    = fcn.Inputs;
            smokes    = autotest.InputSampler.smokeFor(inputs, argBlocks);
            edges     = autotest.InputSampler.emptyCase();
            if obj.Options.EdgeCaseTests
                edges = autotest.InputSampler.edgeFor(inputs, argBlocks);
            end

            % Prepend a realistic smoke case derived from project fixtures
            % when one is available.  This is the "happy path" test that
            % uses real inputs (e.g. an actual xlsx file path) instead of
            % the synthetic 1/[]/NaN scaffolding.
            help = '';
            if isfield(fcn, 'HelpText'), help = fcn.HelpText; end
            provider = obj.Options.FixtureProvider;
            smart = autotest.InputSampler.smartFor(inputs, argBlocks, help, provider);
            for s = 1:numel(smart)
                buf = obj.appendCallTest(buf, fcn, smart(s), kind, false);
            end

            % Phase 2.3: when the FixtureProvider resolved a realistic
            % call (smart is non-empty) AND at least one input has a
            % name-driven literal that differs from the synthetic
            % scalarFor() default, the synthetic scalar/vector/matrix
            % variants will pass mismatched data (e.g. `1` for a
            % `message` arg, then crash on `cellstr(1)`).  Skip them.
            skipSynthetic = false;
            if ~isempty(smart) && ~isempty(provider) && ...
                    isa(provider, 'autotest.FixtureProvider')
                typedForCheck = autotest.InputSampler.typesFromArguments(inputs, argBlocks);
                for k = 1:numel(inputs)
                    if strcmp(inputs{k}, 'varargin'), break; end
                    nameLit = provider.literalForArg(inputs{k}, typedForCheck{k}, help);
                    typeLit = autotest.InputSampler.scalarFor(typedForCheck{k});
                    if ~isempty(nameLit) && ~strcmp(nameLit, typeLit)
                        skipSynthetic = true;
                        break;
                    end
                end
            end
            if ~skipSynthetic
                for s = 1:numel(smokes)
                    buf = obj.appendCallTest(buf, fcn, smokes(s), kind, false);
                end
            end

            % Phase 1.2: when both layers produced no usable smoke (e.g.
            % every positional input is opaque-typed), emit a single
            % "skipped" placeholder via assumeFail so the function still
            % shows up in the report as Incomplete with a clear reason --
            % rather than silently not appearing at all.
            if isempty(smart) && isempty(smokes) && ~isempty(inputs)
                methodName = matlab.lang.makeValidName(['testSkipped_' fcn.Name]);
                buf(end+1,1) = string(sprintf('        function %s(testCase)', methodName));
                buf(end+1,1) = string(sprintf( ...
                    '            testCase.assumeFail(''%s smoke skipped: opaque-typed input'');', ...
                    fcn.Name));
                buf(end+1,1) = "        end";
                buf(end+1,1) = "";
            end

            if obj.Options.PropertyTests
                buf = obj.appendPropertyTestsForFcn(buf, fcn, kind);
            end

            for e = 1:numel(edges)
                buf = obj.appendCallTest(buf, fcn, edges(e), kind, true);
            end

            if obj.Options.DocExampleTests
                for ex = 1:numel(fcn.Examples)
                    buf = obj.appendDocExampleTest(buf, fcn, ex, fcn.Examples{ex});
                end
            end
        end

        function buf = appendCallTest(obj, buf, fcn, sample, kind, isEdge)
            label = matlab.lang.makeValidName(sample.Label);
            prefix = autotest.TestWriter.iif(isEdge, 'testEdge_', 'testSmoke_');
            methodName = matlab.lang.makeValidName([prefix fcn.Name '_' label]);

            % Phase 7 (Option 1): per-target known-real-signal opt-out.
            buf = obj.maybeEmitKnownRealSignalSkip(buf, methodName);
            if obj.lastWasSkip(buf), return; end

            callExpr = obj.formatCall(fcn, sample.Expr, kind);
            buf(end+1,1) = string(sprintf('        function %s(testCase)', methodName));
            if isEdge
                % Edge cases may legitimately throw OR return degenerate
                % values (NaN, Inf, []).  The contract is "doesn't crash
                % the interpreter"; either a clean return or a thrown
                % error is acceptable.  Don't run assertReasonable here
                % (it intentionally rejects all-NaN, which is a *valid*
                % outcome when the input itself is NaN).
                buf(end+1,1) = "            try";
                if numel(fcn.Outputs) >= 1
                    buf(end+1,1) = string(sprintf('                out = %s; %%#ok<NASGU>', callExpr));
                    buf(end+1,1) = "                testCase.verifyTrue(true, 'Edge case returned without error');";
                else
                    buf(end+1,1) = string(sprintf('                %s;', callExpr));
                    buf(end+1,1) = "                testCase.verifyTrue(true, 'Edge case returned without error');";
                end
                buf(end+1,1) = "            catch ME";
                buf(end+1,1) = "                testCase.verifyTrue(true, ...";
                buf(end+1,1) = "                    sprintf('Edge case threw (acceptable): %s', ME.message));";
                buf(end+1,1) = "            end";
            else
                if numel(fcn.Outputs) >= 1 && ~strcmp(fcn.Outputs{1}, 'varargout')
                    buf(end+1,1) = string(sprintf('            out = %s;', callExpr));
                    % Phase 1.3: returning [] is a valid "nothing to do"
                    % outcome (e.g. redactSharedStrings with no matches);
                    % don't fail the smoke for that.
                    buf(end+1,1) = "            testCase.assertReasonable(out);";
                else
                    buf(end+1,1) = string(sprintf('            %s;', callExpr));
                    buf(end+1,1) = "            testCase.verifyTrue(true, 'Smoke call did not throw');";
                end
            end
            buf(end+1,1) = "        end";
            buf(end+1,1) = "";
        end

        function buf = appendPropertyTestsForFcn(obj, buf, fcn, kind)
            % Property-based: run several random inputs and verify a set of
            % invariants (no error, output type = double when input is, no
            % NaN/Inf for smoke samples).
            if isempty(fcn.Inputs), return; end

            % Phase 2.2: when every positional input is opaque-typed
            % (DOM nodes, dictionary, containers.Map, etc.), the
            % randomized layer can only emit `rand(1, randi(5))` -- which
            % always throws on real DOM/dictionary methods.  Mirror the
            % smoke-skip behavior: emit a single Incomplete placeholder
            % so the function still appears in the report.
            inputsCheck = fcn.Inputs;
            argBlocksCheck = fcn.ArgumentBlocks;
            typedCheck = autotest.InputSampler.typesFromArguments(inputsCheck, argBlocksCheck);
            % Phase 3 (Option 1): skip randomized when ANY positional
            % input is opaque-typed.  randomized uses rand(1, randi(5))
            % for every input -- a single DOM / dictionary / sheet arg
            % is enough to crash the call, even when other args are
            % well-typed strings.  The Phase 2.2 all-opaque gate left
            % those failures live in ExcelRemover / ExcelXmlCleaner /
            % TableMetadata; widening to any-opaque lets the existing
            % opaque-skip path do its job.
            anyOpaque = false;
            for k = 1:numel(inputsCheck)
                if strcmp(inputsCheck{k}, 'varargin')
                    break;
                end
                if autotest.InputSampler.isOpaqueType(typedCheck{k}, inputsCheck{k})
                    anyOpaque = true;
                    break;
                end
            end
            if anyOpaque
                skipName = matlab.lang.makeValidName(['testSkipped_random_' fcn.Name]);
                buf(end+1,1) = string(sprintf('        function %s(testCase)', skipName));
                buf(end+1,1) = string(sprintf( ...
                    '            testCase.assumeFail(''%s randomized skipped: opaque-typed input'');', ...
                    fcn.Name));
                buf(end+1,1) = "        end";
                buf(end+1,1) = "";
                return;
            end

            methodName = matlab.lang.makeValidName(['testRandomized_' fcn.Name]);

            % Phase 7 (Option 1): per-target known-real-signal opt-out.
            buf = obj.maybeEmitKnownRealSignalSkip(buf, methodName);
            if obj.lastWasSkip(buf), return; end

            buf(end+1,1) = string(sprintf('        function %s(testCase)', methodName));
            buf(end+1,1) = "            rng(42);";
            buf(end+1,1) = "            for trial = 1:25";
            randomArgs = obj.randomArgsExpr(fcn);
            callExpr = obj.formatCallExplicit(fcn, randomArgs, kind);
            buf(end+1,1) = "                try";
            if ~isempty(fcn.Outputs)
                buf(end+1,1) = string(sprintf('                    out = %s;', callExpr));
                buf(end+1,1) = "                    testCase.assertReasonable(out);";
            else
                buf(end+1,1) = string(sprintf('                    %s;', callExpr));
            end
            buf(end+1,1) = "                catch ME";
            buf(end+1,1) = "                    if ~testCase.isValidationError(ME)";
            buf(end+1,1) = "                        rethrow(ME);";
            buf(end+1,1) = "                    end";
            buf(end+1,1) = "                end";
            buf(end+1,1) = "            end";
            buf(end+1,1) = "        end";
            buf(end+1,1) = "";
        end

        function buf = appendDocExampleTest(~, buf, fcn, idx, exampleText)
            methodName = matlab.lang.makeValidName(sprintf('testDocExample_%s_%d', fcn.Name, idx));
            % Examples are run via a sandbox eval, capturing expected
            % outputs only when safe.
            buf(end+1,1) = string(sprintf('        function %s(testCase)', methodName));
            escaped = autotest.TestWriter.escapeString(exampleText);
            buf(end+1,1) = string(sprintf('            exampleText = sprintf(''%s'');', escaped));
            buf(end+1,1) = "            testCase.verifyWarningFree(@() testCase.runExample(exampleText), ...";
            buf(end+1,1) = "                'Example block from help text threw');";
            buf(end+1,1) = "        end";
            buf(end+1,1) = "";
        end

        function buf = appendConstructorTests(obj, buf, ctor)
            % Phase 7 (Option 2): when the FixtureProvider can resolve a
            % literal for EVERY ctor arg (e.g. `filePath` -> tempname(),
            % `classificationTag` -> 'FOR OFFICIAL USE ONLY'), emit one
            % testConstructor_realistic and skip the scalar/vector/matrix
            % variants.  Realistic args produce a writable tempname() and
            % therefore the ctor can actually fopen the file -- the
            % shape-driven 'a'/[1 2 3 4]/magic(3) variants couldn't.
            % Falls back to the smoke ladder when any arg is unresolved.
            inputs = ctor.Inputs;
            ctorHelp = '';
            if isfield(ctor, 'HelpText')
                ctorHelp = ctor.HelpText;
            end

            % Try realistic first.
            realisticArgs = '';
            haveRealistic = false;
            provider = [];
            if ~isempty(obj.Options) && isprop(obj.Options, 'FixtureProvider')
                provider = obj.Options.FixtureProvider;
            end
            if ~isempty(provider) && isa(provider, 'autotest.FixtureProvider') ...
                    && ~isempty(inputs)
                smart = autotest.InputSampler.smartFor( ...
                    inputs, ctor.ArgumentBlocks, ctorHelp, provider);
                if ~isempty(smart)
                    realisticArgs = smart(1).Expr;
                    haveRealistic = true;
                end
            end

            if haveRealistic
                methodName = 'testConstructor_realistic';

                % Phase 7 (Option 1): per-target known-real-signal opt-out.
                buf = obj.maybeEmitKnownRealSignalSkip(buf, methodName);
                if obj.lastWasSkip(buf), return; end

                buf(end+1,1) = string(sprintf('        function %s(testCase)', methodName));
                buf(end+1,1) = string(sprintf('            obj = %s(%s); %%#ok<NASGU>', ...
                    obj.Model.ClassName, realisticArgs));
                buf(end+1,1) = string(sprintf('            testCase.verifyClass(obj, ''%s'');', obj.Model.ClassName));
                if obj.Model.IsHandle
                    buf(end+1,1) = "            testCase.addTeardown(@() testCase.safeDelete(obj));";
                end
                buf(end+1,1) = "        end";
                buf(end+1,1) = "";
                return;
            end

            % Fallback: shape-driven smoke ladder (scalar / vector / matrix).
            smokes = autotest.InputSampler.smokeFor(inputs, ctor.ArgumentBlocks);
            for s = 1:numel(smokes)
                methodName = matlab.lang.makeValidName(sprintf('testConstructor_%s', smokes(s).Label));

                % Phase 7 (Option 1): per-target known-real-signal opt-out.
                buf = obj.maybeEmitKnownRealSignalSkip(buf, methodName); %#ok<AGROW>
                if obj.lastWasSkip(buf)
                    continue;
                end

                buf(end+1,1) = string(sprintf('        function %s(testCase)', methodName)); %#ok<AGROW>
                buf(end+1,1) = string(sprintf('            obj = %s(%s); %%#ok<NASGU>', ...
                    obj.Model.ClassName, smokes(s).Expr));
                buf(end+1,1) = string(sprintf('            testCase.verifyClass(obj, ''%s'');', obj.Model.ClassName));
                if obj.Model.IsHandle
                    buf(end+1,1) = "            testCase.addTeardown(@() testCase.safeDelete(obj));";
                end
                buf(end+1,1) = "        end";
                buf(end+1,1) = "";
            end
        end

        function buf = appendPropertyTest(obj, buf, prop, holderProp)
            if nargin < 4, holderProp = 'Instance'; end
            methodName = matlab.lang.makeValidName(['testProperty_' prop.Name]);
            buf(end+1,1) = string(sprintf('        function %s(testCase)', methodName));
            buf(end+1,1) = string(sprintf('            value = testCase.%s.%s;', holderProp, prop.Name));
            buf(end+1,1) = "            testCase.verifyTrue(true, 'Property read did not throw');";
            setAccess = '';
            if isfield(prop, 'SetAccess') && ~isempty(prop.SetAccess)
                setAccess = prop.SetAccess;
            else
                setAccess = prop.Access;
            end
            isSettable = ~prop.IsDependent ...
                && ~prop.IsConstant ...
                && strcmpi(setAccess, 'public');
            if isSettable
                sampleExpr = '';
                provider = obj.Options.FixtureProvider;
                if ~isempty(provider) && isa(provider, 'autotest.FixtureProvider')
                    sampleExpr = provider.literalForProperty(prop.Name, char(prop.Type));
                end
                if isempty(sampleExpr)
                    sampleExpr = autotest.TestWriter.sampleForType(prop);
                end
                if ~isempty(sampleExpr)
                    buf(end+1,1) = "            try";
                    buf(end+1,1) = string(sprintf('                testCase.%s.%s = %s;', ...
                        holderProp, prop.Name, sampleExpr));
                    buf(end+1,1) = string(sprintf('                testCase.verifyEqual(testCase.%s.%s, %s);', ...
                        holderProp, prop.Name, sampleExpr));
                    buf(end+1,1) = "            catch ME";
                    buf(end+1,1) = "                if ~testCase.isValidationError(ME)";
                    buf(end+1,1) = "                    rethrow(ME);";
                    buf(end+1,1) = "                end";
                    buf(end+1,1) = "            end";
                end
            end
            buf(end+1,1) = "            assert(~isempty(class(value)));";
            buf(end+1,1) = "        end";
            buf(end+1,1) = "";
        end

        function buf = appendCallbackTest(obj, buf, cb)
            methodName = matlab.lang.makeValidName(['testCallback_' cb.Name]);
            usesDialog = isfield(cb, 'UsesFileDialog') && cb.UsesFileDialog;

            % Phase 7 (Option 1): per-target known-real-signal opt-out.
            buf = obj.maybeEmitKnownRealSignalSkip(buf, methodName);
            if obj.lastWasSkip(buf), return; end
            buf(end+1,1) = string(sprintf('        function %s(testCase)', methodName));
            buf(end+1,1) = "            app = testCase.App;";
            if ~isempty(cb.ComponentTag)
                buf(end+1,1) = string(sprintf('            comp = testCase.findByTag(app, ''%s'');', cb.ComponentTag));
                buf(end+1,1) = "            event = struct('Source', comp, 'EventName', 'Synthetic');";
            else
                buf(end+1,1) = "            comp = [];";
                buf(end+1,1) = "            event = struct('Source', app, 'EventName', 'Synthetic');";
            end
            if usesDialog
                % Phase 3 (Option 2): pre-stub file dialogs so the
                % callback returns immediately with canned values rather
                % than blocking on a modal picker.  installFileDialogStubs
                % is inlined as a private helper on this test class.
                dialogs = cb.DialogFunctions;
                if isempty(dialogs)
                    dialogs = autotest.MlappFixtureProvider.DialogFunctions;
                end
                dialogList = '{';
                for di = 1:numel(dialogs)
                    if di > 1, dialogList = [dialogList ', ']; end %#ok<AGROW>
                    dialogList = [dialogList '''' dialogs{di} '''']; %#ok<AGROW>
                end
                dialogList = [dialogList '}'];
                buf(end+1,1) = "            % --- Phase 3: file-dialog shim ---";
                buf(end+1,1) = string(sprintf( ...
                    '            testCase.installFileDialogStubs(%s);', dialogList));
            end
            buf(end+1,1) = "            try";
            buf(end+1,1) = string(sprintf('                if ismethod(app, ''%s'')', cb.Name));
            buf(end+1,1) = string(sprintf('                    app.%s(comp, event);', cb.Name));
            buf(end+1,1) = "                else";
            buf(end+1,1) = string(sprintf('                    feval(@(s,e) app.%s(s,e), comp, event);', cb.Name));
            buf(end+1,1) = "                end";
            buf(end+1,1) = "                testCase.verifyTrue(isvalid(app), 'App was deleted by callback');";
            buf(end+1,1) = "            catch ME";
            if usesDialog
                % Downstream IO (xlsread, copyfile, ...) may still throw
                % because the synthetic path won't point at a real file.
                % That's acceptable: the dialog itself was successfully
                % shimmed (no infinite hang) and the App survived.
                buf(end+1,1) = "                if isvalid(app)";
                buf(end+1,1) = "                    testCase.verifyTrue(true, ...";
                buf(end+1,1) = string(sprintf( ...
                    '                        sprintf(''Callback %s threw downstream of dialog (acceptable): %%s: %%s'', class(ME), ME.message));', cb.Name));
                buf(end+1,1) = "                else";
                buf(end+1,1) = "                    testCase.verifyTrue(false, ...";
                buf(end+1,1) = string(sprintf( ...
                    '                        sprintf(''Callback %s threw and destroyed app: %%s: %%s'', class(ME), ME.message));', cb.Name));
                buf(end+1,1) = "                end";
            else
                buf(end+1,1) = "                testCase.verifyTrue(false, ...";
                buf(end+1,1) = "                    sprintf('Callback %s threw: %s', class(ME), ME.message));";
            end
            buf(end+1,1) = "            end";
            buf(end+1,1) = "        end";
            buf(end+1,1) = "";
        end

        function buf = appendHelpers(~, buf)
            buf(end+1,1) = "    methods (Access = private)";
            buf(end+1,1) = "        function safeDelete(~, h)";
            buf(end+1,1) = "            try";
            buf(end+1,1) = "                if ~isempty(h) && isobject(h) && isvalid(h)";
            buf(end+1,1) = "                    delete(h);";
            buf(end+1,1) = "                end";
            buf(end+1,1) = "            catch";
            buf(end+1,1) = "            end";
            buf(end+1,1) = "        end";
            buf(end+1,1) = "";
            buf(end+1,1) = "        function shutdownApp(~, app, preFigs)";
            buf(end+1,1) = "            try";
            buf(end+1,1) = "                if ~isempty(app) && isobject(app) && isvalid(app)";
            buf(end+1,1) = "                    delete(app);";
            buf(end+1,1) = "                end";
            buf(end+1,1) = "            catch";
            buf(end+1,1) = "            end";
            buf(end+1,1) = "            try";
            buf(end+1,1) = "                postFigs = findall(groot, 'Type', 'figure');";
            buf(end+1,1) = "                if ~isempty(preFigs)";
            buf(end+1,1) = "                    leaked = setdiff(postFigs, preFigs);";
            buf(end+1,1) = "                else";
            buf(end+1,1) = "                    leaked = postFigs;";
            buf(end+1,1) = "                end";
            buf(end+1,1) = "                for k = 1:numel(leaked)";
            buf(end+1,1) = "                    try";
            buf(end+1,1) = "                        delete(leaked(k));";
            buf(end+1,1) = "                    catch";
            buf(end+1,1) = "                    end";
            buf(end+1,1) = "                end";
            buf(end+1,1) = "            catch";
            buf(end+1,1) = "            end";
            buf(end+1,1) = "        end";
            buf(end+1,1) = "";
            buf(end+1,1) = "        function tf = isValidationError(~, ME)";
            buf(end+1,1) = "            tf = startsWith(ME.identifier, 'MATLAB:validators') ...";
            buf(end+1,1) = "                || startsWith(ME.identifier, 'MATLAB:validation') ...";
            buf(end+1,1) = "                || strcmp(ME.identifier, 'MATLAB:type:InvalidInputSize') ...";
            buf(end+1,1) = "                || strcmp(ME.identifier, 'MATLAB:invalidType') ...";
            buf(end+1,1) = "                || contains(ME.identifier, 'expectedType', 'IgnoreCase', true);";
            buf(end+1,1) = "        end";
            buf(end+1,1) = "";
            buf(end+1,1) = "        function assertReasonable(testCase, value)";
            buf(end+1,1) = "            if isnumeric(value) && ~isempty(value)";
            buf(end+1,1) = "                testCase.verifyFalse(all(isnan(value(:))), ...";
            buf(end+1,1) = "                    'All-NaN numeric output is suspicious');";
            buf(end+1,1) = "            end";
            buf(end+1,1) = "            testCase.verifyTrue(true);";
            buf(end+1,1) = "        end";
            buf(end+1,1) = "";
            buf(end+1,1) = "        function comp = findByTag(~, app, tag)";
            buf(end+1,1) = "            comp = [];";
            buf(end+1,1) = "            try";
            buf(end+1,1) = "                fig = [];";
            buf(end+1,1) = "                pn = properties(app);";
            buf(end+1,1) = "                for k = 1:numel(pn)";
            buf(end+1,1) = "                    v = app.(pn{k});";
            buf(end+1,1) = "                    if isa(v, 'matlab.ui.Figure')";
            buf(end+1,1) = "                        fig = v; break;";
            buf(end+1,1) = "                    end";
            buf(end+1,1) = "                end";
            buf(end+1,1) = "                if isempty(fig), return; end";
            buf(end+1,1) = "                comp = findobj(fig, 'Tag', tag);";
            buf(end+1,1) = "            catch";
            buf(end+1,1) = "            end";
            buf(end+1,1) = "        end";
            buf(end+1,1) = "";
            buf(end+1,1) = "        function runExample(~, text)";
            buf(end+1,1) = "            eval(text);";
            buf(end+1,1) = "        end";
            buf(end+1,1) = "";
            % Phase 3 (Option 2): file-dialog stub helpers, inlined so
            % generated tXxx.m files stay self-contained (no runtime
            % dependency on the +autotest package).
            buf(end+1,1) = "        function installFileDialogStubs(testCase, dialogs)";
            buf(end+1,1) = "            if nargin < 2 || isempty(dialogs)";
            buf(end+1,1) = "                dialogs = {'uigetfile', 'uiputfile', 'uigetdir'};";
            buf(end+1,1) = "            end";
            buf(end+1,1) = "            stubDir = tempname();";
            buf(end+1,1) = "            if ~exist(stubDir, 'dir'), mkdir(stubDir); end";
            buf(end+1,1) = "            testCase.addTeardown(@() testCase.removeFileDialogStubDir(stubDir));";
            buf(end+1,1) = "            for k = 1:numel(dialogs)";
            buf(end+1,1) = "                name = dialogs{k};";
            buf(end+1,1) = "                switch name";
            buf(end+1,1) = "                    case {'uigetfile', 'uiputfile'}";
            buf(end+1,1) = "                        src = ['function varargout = ' name '(varargin)' newline ...";
            buf(end+1,1) = "                               'varargout = {''synthetic.xlsx'', tempdir(), 1};' newline ...";
            buf(end+1,1) = "                               'end' newline];";
            buf(end+1,1) = "                    case 'uigetdir'";
            buf(end+1,1) = "                        src = ['function p = ' name '(varargin)' newline ...";
            buf(end+1,1) = "                               'p = tempdir();' newline ...";
            buf(end+1,1) = "                               'end' newline];";
            buf(end+1,1) = "                    otherwise";
            buf(end+1,1) = "                        continue;";
            buf(end+1,1) = "                end";
            buf(end+1,1) = "                stubFile = fullfile(stubDir, [name '.m']);";
            buf(end+1,1) = "                fid = fopen(stubFile, 'w');";
            buf(end+1,1) = "                if fid < 0, continue; end";
            buf(end+1,1) = "                fwrite(fid, src);";
            buf(end+1,1) = "                fclose(fid);";
            buf(end+1,1) = "            end";
            buf(end+1,1) = "            addpath(stubDir);";
            buf(end+1,1) = "            testCase.addTeardown(@() testCase.removeFileDialogStubPath(stubDir));";
            buf(end+1,1) = "            rehash path;";
            buf(end+1,1) = "        end";
            buf(end+1,1) = "";
            buf(end+1,1) = "        function removeFileDialogStubPath(~, stubDir)";
            buf(end+1,1) = "            try";
            buf(end+1,1) = "                rmpath(stubDir);";
            buf(end+1,1) = "            catch";
            buf(end+1,1) = "            end";
            buf(end+1,1) = "            try";
            buf(end+1,1) = "                rehash path;";
            buf(end+1,1) = "            catch";
            buf(end+1,1) = "            end";
            buf(end+1,1) = "        end";
            buf(end+1,1) = "";
            buf(end+1,1) = "        function removeFileDialogStubDir(~, stubDir)";
            buf(end+1,1) = "            try";
            buf(end+1,1) = "                if isfolder(stubDir)";
            buf(end+1,1) = "                    rmdir(stubDir, 's');";
            buf(end+1,1) = "                end";
            buf(end+1,1) = "            catch";
            buf(end+1,1) = "            end";
            buf(end+1,1) = "        end";
            buf(end+1,1) = "    end";
            buf(end+1,1) = "";
        end

        function ctor = findConstructor(obj)
            ctor = [];
            for k = 1:numel(obj.Model.Methods)
                if strcmp(obj.Model.Methods(k).Name, obj.Model.ClassName)
                    ctor = obj.Model.Methods(k);
                    return;
                end
            end
            ctor = autotest.SourceModel.makeFcn(obj.Model.ClassName);
        end

        function expr = formatCall(obj, fcn, args, kind)
            if isempty(args)
                argList = '';
            else
                argList = args;
            end
            switch kind
                case 'function'
                    expr = sprintf('%s(%s)', fcn.Name, argList);
                case 'method'
                    expr = sprintf('testCase.Instance.%s(%s)', fcn.Name, argList);
                case 'static'
                    expr = sprintf('%s.%s(%s)', obj.Model.ClassName, fcn.Name, argList);
                otherwise
                    expr = sprintf('%s(%s)', fcn.Name, argList);
            end
        end

        function expr = formatCallExplicit(obj, fcn, args, kind)
            expr = obj.formatCall(fcn, args, kind);
        end

        function buf = maybeEmitKnownRealSignalSkip(obj, buf, methodName)
            % Phase 7 (Option 1): if the per-target known_real_signal.txt
            % lists (TestClassName, methodName), emit a
            % testSkipped_<methodName> Incomplete carrying the user-
            % supplied reason and signal the caller via LastEmittedSkip.
            % Reset the marker on every entry so callers can short-
            % circuit cleanly.  See +autotest/KnownRealSignal.m and
            % CLAUDE.md ("Excluding known real-signal failures").
            obj.LastEmittedSkip = false;
            targetFolder = '';
            if ~isempty(obj.Options) && isprop(obj.Options, 'TargetFolder')
                targetFolder = obj.Options.TargetFolder;
            end
            if isempty(targetFolder), return; end
            classForLookup = '';
            if ~isempty(obj.Options) && isprop(obj.Options, 'TestClassName')
                classForLookup = obj.Options.TestClassName;
            end
            if isempty(classForLookup), return; end
            reason = autotest.KnownRealSignal.match( ...
                targetFolder, classForLookup, methodName);
            if isempty(reason), return; end
            skipName = matlab.lang.makeValidName(['testSkipped_' methodName]);
            msg = ['known-real-signal: ' reason];
            escMsg = autotest.TestWriter.escapeCharLiteral(msg);
            buf(end+1,1) = string(sprintf('        function %s(testCase)', skipName));
            buf(end+1,1) = string(sprintf( ...
                '            testCase.assumeFail(''%s'');', escMsg));
            buf(end+1,1) = "        end";
            buf(end+1,1) = "";
            obj.LastEmittedSkip = true;
        end

        function tf = lastWasSkip(obj, ~)
            tf = obj.LastEmittedSkip;
        end

        function expr = randomArgsExpr(~, fcn)
            % Phase 6 (Option 3): typed-aware random arg generation.
            % Plain `rand(1, randi(5))` crashes when the arg is actually
            % a string/cell/char (regexp/fprintf/etc.).  Resolve typed
            % info via InputSampler.typesFromArguments and pick a
            % type-appropriate randomized literal.  Numeric types still
            % use rand() so existing randomized coverage is unchanged.
            %
            % Phase 10 (generic): fileID-named args get a real fopen-
            % backed handle via autotest.InputSampler.fileIDExpr() so
            % the randomized layer doesn't pipe rand() into fprintf.
            parts = strings(0,1);
            inputs = fcn.Inputs;
            argBlocks = {};
            if isfield(fcn, 'ArgumentBlocks')
                argBlocks = fcn.ArgumentBlocks;
            end
            typed = autotest.InputSampler.typesFromArguments(inputs, argBlocks);
            for k = 1:numel(inputs)
                if strcmp(inputs{k}, 'varargin')
                    break;
                end
                % Phase 10: fileID-named args -> real FID, regardless of
                % declared type.  Stops randomized testRandomized_* from
                % crashing on fprintf with a numeric "fileID".
                if autotest.InputSampler.isFileIDName(inputs{k})
                    parts(end+1,1) = string(autotest.InputSampler.fileIDExpr()); %#ok<AGROW>
                    continue;
                end
                tyLow = '';
                if k <= numel(typed) && isfield(typed{k}, 'Type')
                    tyLow = lower(strtrim(char(typed{k}.Type)));
                end
                switch tyLow
                    case {'string'}
                        parts(end+1,1) = "string(char(double('a') + randi(25, 1, randi(5))))"; %#ok<AGROW>
                    case {'char'}
                        parts(end+1,1) = "char(double('a') + randi(25, 1, randi(5)))"; %#ok<AGROW>
                    case {'cell'}
                        parts(end+1,1) = "num2cell(rand(1, randi(5)))"; %#ok<AGROW>
                    case {'logical'}
                        parts(end+1,1) = "logical(randi([0 1], 1, randi(5)))"; %#ok<AGROW>
                    otherwise
                        parts(end+1,1) = "rand(1, randi(5))"; %#ok<AGROW>
                end
            end
            if isempty(parts)
                expr = '';
            else
                expr = char(strjoin(parts, ', '));
            end
        end
    end

    methods (Static)
        function safeDelete(obj)
            try
                if ~isempty(obj) && isobject(obj) && isvalid(obj)
                    delete(obj);
                end
            catch
            end
        end

        function tf = isValidationError(ME)
            tf = startsWith(ME.identifier, 'MATLAB:validators') ...
                || startsWith(ME.identifier, 'MATLAB:validation') ...
                || strcmp(ME.identifier, 'MATLAB:type:InvalidInputSize') ...
                || strcmp(ME.identifier, 'MATLAB:invalidType') ...
                || contains(ME.identifier, 'expectedType', 'IgnoreCase', true);
        end

        function assertReasonable(testCase, value)
            if isnumeric(value) && ~isempty(value)
                testCase.verifyFalse(all(isnan(value(:))), ...
                    'All-NaN numeric output is suspicious');
            end
            testCase.verifyTrue(true);
        end

        function comp = findByTag(app, tag)
            comp = [];
            try
                fig = [];
                props = properties(app);
                for k = 1:numel(props)
                    p = props{k};
                    v = app.(p);
                    if isa(v, 'matlab.ui.Figure')
                        fig = v; break;
                    end
                end
                if isempty(fig), return; end
                comp = findobj(fig, 'Tag', tag);
            catch
                comp = [];
            end
        end

        function runExample(text)
            evalin('caller', text);
        end

        function s = escapeString(text)
            s = strrep(text, '\', '\\');
            s = strrep(s, '''', '''''');
            s = strrep(s, sprintf('\n'), '\\n');
            s = strrep(s, sprintf('\r'), '\\r');
            s = strrep(s, '%', '%%');
        end

        function s = escapeCharLiteral(text)
            s = strrep(text, '''', '''''');
        end

        function out = iif(cond, a, b)
            if cond
                out = a;
            else
                out = b;
            end
        end

        function expr = sampleForType(prop)
            t = lower(strtrim(char(prop.Type)));
            if isempty(t)
                expr = '1';
                return;
            end
            t = regexprep(t, '\([^)]*\)', '');
            t = strtrim(t);
            parts = strsplit(t);
            base = '';
            if ~isempty(parts), base = parts{1}; end
            switch base
                case {'double','single','numeric',''}
                    expr = '1';
                case {'int8','int16','int32','int64', ...
                      'uint8','uint16','uint32','uint64'}
                    expr = sprintf('%s(1)', base);
                case 'logical'
                    expr = 'true';
                case 'char'
                    expr = '''x''';
                case 'string'
                    expr = '"x"';
                case 'cell'
                    expr = '{1}';
                case 'struct'
                    expr = 'struct(''f'', 1)';
                case 'datetime'
                    expr = 'datetime(2024,1,1)';
                case 'duration'
                    expr = 'seconds(1)';
                case 'categorical'
                    expr = 'categorical("a")';
                case 'function_handle'
                    expr = '@(x) x';
                otherwise
                    expr = '';
            end
        end
    end
end
