classdef TestWriter < handle
    %TESTWRITER  Emits a matlab.unittest.TestCase subclass from a SourceModel.
    %
    %   The generator strategy is:
    %     1. Always emit a "Existence" test that the function/class is
    %        resolvable on the MATLAB path.
    %     2. For functions, emit one Test method per smoke case and per
    %        edge case derived from autotest.InputSampler.  Each test
    %        verifies the call does not throw, that nargout outputs are
    %        produced when expected, and that numeric outputs are finite
    %        for smoke inputs.
    %     3. For classdef, emit a TestMethodSetup that constructs the
    %        object (with default args), property get/set tests, and per-
    %        method invocations.  Handle classes are wrapped in cleanup.
    %     4. For App Designer apps, emit a launch/teardown pair plus per-
    %        callback invocation tests via findComponentByTag helpers.
    %     5. Each "Example:" block found in help text is materialised as a
    %        Test method that runs the example expression and verifies it
    %        does not throw.

    properties (SetAccess = immutable)
        Model    autotest.SourceModel
        Options  % autotest.TestGenerator
    end

    methods
        function obj = TestWriter(model, options)
            obj.Model = model;
            obj.Options = options;
        end

        function writeTo(obj, filePath)
            src = obj.buildSource();
            fid = fopen(filePath, 'w');
            if fid < 0
                error('autotest:WriteFailed', 'Cannot write %s', filePath);
            end
            cleaner = onCleanup(@() fclose(fid));
            fwrite(fid, src);
        end

        function src = buildSource(obj)
            buf = strings(0,1);
            tw = obj.Options;
            cls = tw.TestClassName;

            buf(end+1,1) = string(sprintf('classdef %s < matlab.unittest.TestCase', cls));
            buf(end+1,1) = "    %% Auto-generated by autotest.TestGenerator.";
            buf(end+1,1) = "    %% DO NOT EDIT BY HAND -- regenerate with generateTests().";
            buf(end+1,1) = "";
            buf(end+1,1) = "    properties (Constant, Access = private)";
            buf(end+1,1) = string(sprintf('        SourcePath = ''%s'';', ...
                autotest.TestWriter.escapeCharLiteral(obj.Model.SourcePath)));
            buf(end+1,1) = "    end";
            buf(end+1,1) = "";
            buf = obj.appendSetup(buf);

            switch obj.Model.Kind
                case 'function'
                    buf = obj.appendFunctionTests(buf);
                case 'classdef'
                    buf = obj.appendClassTests(buf);
                case 'app'
                    buf = obj.appendAppTests(buf);
                otherwise
                    buf(end+1,1) = "    methods (Test)";
                    buf(end+1,1) = "        function testFileExists(testCase)";
                    buf(end+1,1) = "            testCase.verifyTrue(isfile(testCase.SourcePath));";
                    buf(end+1,1) = "        end";
                    buf(end+1,1) = "    end";
            end

            buf = obj.appendHelpers(buf);
            buf(end+1,1) = "end";
            src = char(strjoin(buf, newline)) + newline;
        end
    end

    methods (Access = private)
        function buf = appendSetup(obj, buf)
            buf(end+1,1) = "    methods (TestMethodSetup)";
            buf(end+1,1) = "        function addSourceToPath(testCase)";
            buf(end+1,1) = "            srcDir = fileparts(testCase.SourcePath);";
            buf(end+1,1) = "            if ~isempty(srcDir) && exist(srcDir, 'dir')";
            buf(end+1,1) = "                addpath(srcDir);";
            buf(end+1,1) = "                testCase.addTeardown(@() rmpath(srcDir));";
            buf(end+1,1) = "            end";
            buf(end+1,1) = "        end";
            buf(end+1,1) = "    end";
            buf(end+1,1) = "";
        end

        function buf = appendFunctionTests(obj, buf)
            buf(end+1,1) = "    methods (Test)";

            % Existence + signature for the primary (first) function.
            if ~isempty(obj.Model.Functions)
                buf = obj.appendExistenceBlock(buf, obj.Model.Functions(1).Name);
            end

            for k = 1:numel(obj.Model.Functions)
                fcn = obj.Model.Functions(k);
                if ~fcn.IsPublic, continue; end
                buf = obj.appendFunctionMethods(buf, fcn, 'function');
            end
            buf(end+1,1) = "    end";
            buf(end+1,1) = "";
        end

        function buf = appendClassTests(obj, buf)
            cls = obj.Model.ClassName;
            buf(end+1,1) = "    properties (Access = private)";
            buf(end+1,1) = "        Instance";
            buf(end+1,1) = "    end";
            buf(end+1,1) = "";
            buf(end+1,1) = "    methods (TestMethodSetup)";
            buf(end+1,1) = "        function constructInstance(testCase)";
            buf(end+1,1) = "            try";
            buf(end+1,1) = string(sprintf('                testCase.Instance = %s();', cls));
            if obj.Model.IsHandle
                buf(end+1,1) = "                inst = testCase.Instance;";
                buf(end+1,1) = "                testCase.addTeardown(@() testCase.safeDelete(inst));";
            end
            buf(end+1,1) = "            catch ME";
            buf(end+1,1) = "                testCase.assumeFail(sprintf( ...";
            buf(end+1,1) = string(sprintf('                    ''%s constructor threw: %%s'', ME.message));', cls));
            buf(end+1,1) = "            end";
            buf(end+1,1) = "        end";
            buf(end+1,1) = "    end";
            buf(end+1,1) = "";

            buf(end+1,1) = "    methods (Test)";
            buf = obj.appendExistenceBlock(buf, cls);

            % Constructor test using positional smoke samples.
            ctor = obj.findConstructor();
            if ~isempty(ctor)
                buf = obj.appendConstructorTests(buf, ctor);
            end

            % Property get/set tests.
            for p = 1:numel(obj.Model.Properties)
                prop = obj.Model.Properties(p);
                if ~strcmpi(prop.Access, 'public'), continue; end
                if prop.IsConstant, continue; end
                buf = obj.appendPropertyTest(buf, prop);
            end

            % Method invocation tests.
            for k = 1:numel(obj.Model.Methods)
                m = obj.Model.Methods(k);
                if ~m.IsPublic, continue; end
                if strcmp(m.Name, cls), continue; end  % skip ctor here
                buf = obj.appendFunctionMethods(buf, m, ...
                    autotest.TestWriter.iif(m.IsStatic, 'static', 'method'));
            end
            buf(end+1,1) = "    end";
            buf(end+1,1) = "";
        end

        function buf = appendAppTests(obj, buf)
            cls = obj.Model.ClassName;
            buf(end+1,1) = "    properties (Access = private)";
            buf(end+1,1) = "        App";
            buf(end+1,1) = "    end";
            buf(end+1,1) = "";
            buf(end+1,1) = "    methods (TestMethodSetup)";
            buf(end+1,1) = "        function launchApp(testCase)";
            buf(end+1,1) = "            try";
            buf(end+1,1) = string(sprintf('                testCase.App = %s();', cls));
            buf(end+1,1) = "            catch ME";
            buf(end+1,1) = "                testCase.assumeFail(sprintf( ...";
            buf(end+1,1) = "                    'App launch threw: %s', ME.message));";
            buf(end+1,1) = "            end";
            buf(end+1,1) = "            app = testCase.App;";
            buf(end+1,1) = "            testCase.addTeardown(@() testCase.safeDelete(app));";
            buf(end+1,1) = "        end";
            buf(end+1,1) = "    end";
            buf(end+1,1) = "";

            buf(end+1,1) = "    methods (Test)";
            buf(end+1,1) = "        function testAppLaunches(testCase)";
            buf(end+1,1) = string(sprintf('            testCase.verifyClass(testCase.App, ''%s'');', cls));
            buf(end+1,1) = "            testCase.verifyTrue(isvalid(testCase.App));";
            buf(end+1,1) = "        end";
            buf(end+1,1) = "";
            buf(end+1,1) = "        function testAppHasUIFigure(testCase)";
            buf(end+1,1) = "            testCase.verifyTrue( ...";
            buf(end+1,1) = "                any(strcmp(properties(testCase.App), 'UIFigure')) || ...";
            buf(end+1,1) = "                any(strcmp(properties(testCase.App), 'Figure')));";
            buf(end+1,1) = "        end";

            if obj.Options.AppCallbackTests
                for k = 1:numel(obj.Model.Callbacks)
                    cb = obj.Model.Callbacks(k);
                    buf = obj.appendCallbackTest(buf, cb);
                end
            end

            % Property tests still apply.
            for p = 1:numel(obj.Model.Properties)
                prop = obj.Model.Properties(p);
                if ~strcmpi(prop.Access, 'public'), continue; end
                if prop.IsConstant, continue; end
                buf = obj.appendPropertyTest(buf, prop, 'App');
            end

            buf(end+1,1) = "    end";
            buf(end+1,1) = "";
        end

        function buf = appendExistenceBlock(~, buf, name)
            safe = matlab.lang.makeValidName(['testExists_' name]);
            buf(end+1,1) = string(sprintf('        function %s(testCase)', safe));
            buf(end+1,1) = string(sprintf('            testCase.verifyNotEmpty(which(''%s''), ...', name));
            buf(end+1,1) = string(sprintf('                ''%s is not on the MATLAB path'');', name));
            buf(end+1,1) = "        end";
            buf(end+1,1) = "";
        end

        function buf = appendFunctionMethods(obj, buf, fcn, kind)
            argBlocks = fcn.ArgumentBlocks;
            inputs    = fcn.Inputs;
            smokes    = autotest.InputSampler.smokeFor(inputs, argBlocks);
            edges     = autotest.InputSampler.emptyCase();
            if obj.Options.EdgeCaseTests
                edges = autotest.InputSampler.edgeFor(inputs, argBlocks);
            end

            for s = 1:numel(smokes)
                buf = obj.appendCallTest(buf, fcn, smokes(s), kind, false);
            end

            if obj.Options.PropertyTests
                buf = obj.appendPropertyTestsForFcn(buf, fcn, kind);
            end

            for e = 1:numel(edges)
                buf = obj.appendCallTest(buf, fcn, edges(e), kind, true);
            end

            if obj.Options.DocExampleTests
                for ex = 1:numel(fcn.Examples)
                    buf = obj.appendDocExampleTest(buf, fcn, ex, fcn.Examples{ex});
                end
            end
        end

        function buf = appendCallTest(obj, buf, fcn, sample, kind, isEdge)
            label = matlab.lang.makeValidName(sample.Label);
            prefix = autotest.TestWriter.iif(isEdge, 'testEdge_', 'testSmoke_');
            methodName = matlab.lang.makeValidName([prefix fcn.Name '_' label]);

            callExpr = obj.formatCall(fcn, sample.Expr, kind);
            buf(end+1,1) = string(sprintf('        function %s(testCase)', methodName));
            if isEdge
                % Edge cases may legitimately throw OR return degenerate
                % values (NaN, Inf, []).  The contract is "doesn't crash
                % the interpreter"; either a clean return or a thrown
                % error is acceptable.  Don't run assertReasonable here
                % (it intentionally rejects all-NaN, which is a *valid*
                % outcome when the input itself is NaN).
                buf(end+1,1) = "            try";
                if numel(fcn.Outputs) >= 1
                    buf(end+1,1) = string(sprintf('                out = %s; %%#ok<NASGU>', callExpr));
                    buf(end+1,1) = "                testCase.verifyTrue(true, 'Edge case returned without error');";
                else
                    buf(end+1,1) = string(sprintf('                %s;', callExpr));
                    buf(end+1,1) = "                testCase.verifyTrue(true, 'Edge case returned without error');";
                end
                buf(end+1,1) = "            catch ME";
                buf(end+1,1) = "                testCase.verifyTrue(true, ...";
                buf(end+1,1) = "                    sprintf('Edge case threw (acceptable): %s', ME.message));";
                buf(end+1,1) = "            end";
            else
                if numel(fcn.Outputs) >= 1 && ~strcmp(fcn.Outputs{1}, 'varargout')
                    buf(end+1,1) = string(sprintf('            out = %s;', callExpr));
                    buf(end+1,1) = "            testCase.verifyNotEmpty(out, 'Smoke call produced empty result');";
                    buf(end+1,1) = "            testCase.assertReasonable(out);";
                else
                    buf(end+1,1) = string(sprintf('            %s;', callExpr));
                    buf(end+1,1) = "            testCase.verifyTrue(true, 'Smoke call did not throw');";
                end
            end
            buf(end+1,1) = "        end";
            buf(end+1,1) = "";
        end

        function buf = appendPropertyTestsForFcn(obj, buf, fcn, kind)
            % Property-based: run several random inputs and verify a set of
            % invariants (no error, output type = double when input is, no
            % NaN/Inf for smoke samples).
            if isempty(fcn.Inputs), return; end
            methodName = matlab.lang.makeValidName(['testRandomized_' fcn.Name]);
            buf(end+1,1) = string(sprintf('        function %s(testCase)', methodName));
            buf(end+1,1) = "            rng(42);";
            buf(end+1,1) = "            for trial = 1:25";
            randomArgs = obj.randomArgsExpr(fcn);
            callExpr = obj.formatCallExplicit(fcn, randomArgs, kind);
            buf(end+1,1) = "                try";
            if ~isempty(fcn.Outputs)
                buf(end+1,1) = string(sprintf('                    out = %s;', callExpr));
                buf(end+1,1) = "                    testCase.assertReasonable(out);";
            else
                buf(end+1,1) = string(sprintf('                    %s;', callExpr));
            end
            buf(end+1,1) = "                catch ME";
            buf(end+1,1) = "                    if ~testCase.isValidationError(ME)";
            buf(end+1,1) = "                        rethrow(ME);";
            buf(end+1,1) = "                    end";
            buf(end+1,1) = "                end";
            buf(end+1,1) = "            end";
            buf(end+1,1) = "        end";
            buf(end+1,1) = "";
        end

        function buf = appendDocExampleTest(~, buf, fcn, idx, exampleText)
            methodName = matlab.lang.makeValidName(sprintf('testDocExample_%s_%d', fcn.Name, idx));
            % Examples are run via a sandbox eval, capturing expected
            % outputs only when safe.
            buf(end+1,1) = string(sprintf('        function %s(testCase)', methodName));
            escaped = autotest.TestWriter.escapeString(exampleText);
            buf(end+1,1) = string(sprintf('            exampleText = sprintf(''%s'');', escaped));
            buf(end+1,1) = "            testCase.verifyWarningFree(@() testCase.runExample(exampleText), ...";
            buf(end+1,1) = "                'Example block from help text threw');";
            buf(end+1,1) = "        end";
            buf(end+1,1) = "";
        end

        function buf = appendConstructorTests(obj, buf, ctor)
            inputs = ctor.Inputs;
            smokes = autotest.InputSampler.smokeFor(inputs, ctor.ArgumentBlocks);
            for s = 1:numel(smokes)
                methodName = matlab.lang.makeValidName(sprintf('testConstructor_%s', smokes(s).Label));
                buf(end+1,1) = string(sprintf('        function %s(testCase)', methodName)); %#ok<AGROW>
                buf(end+1,1) = string(sprintf('            obj = %s(%s); %%#ok<NASGU>', ...
                    obj.Model.ClassName, smokes(s).Expr));
                buf(end+1,1) = string(sprintf('            testCase.verifyClass(obj, ''%s'');', obj.Model.ClassName));
                if obj.Model.IsHandle
                    buf(end+1,1) = "            testCase.addTeardown(@() testCase.safeDelete(obj));";
                end
                buf(end+1,1) = "        end";
                buf(end+1,1) = "";
            end
        end

        function buf = appendPropertyTest(obj, buf, prop, holderProp)
            if nargin < 4, holderProp = 'Instance'; end
            methodName = matlab.lang.makeValidName(['testProperty_' prop.Name]);
            buf(end+1,1) = string(sprintf('        function %s(testCase)', methodName));
            buf(end+1,1) = string(sprintf('            value = testCase.%s.%s;', holderProp, prop.Name));
            buf(end+1,1) = "            testCase.verifyTrue(true, 'Property read did not throw');";
            % Only attempt round-trip set/get when the property is publicly
            % settable (Access=public AND SetAccess=public, and not a
            % Dependent property without a setter).
            setAccess = '';
            if isfield(prop, 'SetAccess') && ~isempty(prop.SetAccess)
                setAccess = prop.SetAccess;
            else
                setAccess = prop.Access;
            end
            isSettable = ~prop.IsDependent ...
                && ~prop.IsConstant ...
                && strcmpi(setAccess, 'public');
            if isSettable
                sampleExpr = autotest.TestWriter.sampleForType(prop);
                if ~isempty(sampleExpr)
                    buf(end+1,1) = "            try";
                    buf(end+1,1) = string(sprintf('                testCase.%s.%s = %s;', ...
                        holderProp, prop.Name, sampleExpr));
                    buf(end+1,1) = string(sprintf('                testCase.verifyEqual(testCase.%s.%s, %s);', ...
                        holderProp, prop.Name, sampleExpr));
                    buf(end+1,1) = "            catch ME";
                    buf(end+1,1) = "                if ~testCase.isValidationError(ME)";
                    buf(end+1,1) = "                    rethrow(ME);";
                    buf(end+1,1) = "                end";
                    buf(end+1,1) = "            end";
                end
            end
            buf(end+1,1) = "            assert(~isempty(class(value)));";
            buf(end+1,1) = "        end";
            buf(end+1,1) = "";
        end

        function buf = appendCallbackTest(~, buf, cb)
            methodName = matlab.lang.makeValidName(['testCallback_' cb.Name]);
            buf(end+1,1) = string(sprintf('        function %s(testCase)', methodName));
            buf(end+1,1) = "            app = testCase.App;";
            if ~isempty(cb.ComponentTag)
                buf(end+1,1) = string(sprintf('            comp = testCase.findByTag(app, ''%s'');', cb.ComponentTag));
                buf(end+1,1) = "            event = struct('Source', comp, 'EventName', 'Synthetic');";
            else
                buf(end+1,1) = "            comp = [];";
                buf(end+1,1) = "            event = struct('Source', app, 'EventName', 'Synthetic');";
            end
            buf(end+1,1) = "            try";
            buf(end+1,1) = string(sprintf('                if ismethod(app, ''%s'')', cb.Name));
            buf(end+1,1) = string(sprintf('                    app.%s(comp, event);', cb.Name));
            buf(end+1,1) = "                else";
            buf(end+1,1) = string(sprintf('                    feval(@(s,e) app.%s(s,e), comp, event);', cb.Name));
            buf(end+1,1) = "                end";
            buf(end+1,1) = "                testCase.verifyTrue(isvalid(app), 'App was deleted by callback');";
            buf(end+1,1) = "            catch ME";
            buf(end+1,1) = "                testCase.verifyTrue(false, ...";
            buf(end+1,1) = "                    sprintf('Callback %s threw: %s', class(ME), ME.message));";
            buf(end+1,1) = "            end";
            buf(end+1,1) = "        end";
            buf(end+1,1) = "";
        end

        function buf = appendHelpers(~, buf)
            % Emit private helpers so generated tests are self-contained
            % (no runtime dependency on the autotest package).
            buf(end+1,1) = "    methods (Access = private)";
            buf(end+1,1) = "        function safeDelete(~, h)";
            buf(end+1,1) = "            try";
            buf(end+1,1) = "                if ~isempty(h) && isobject(h) && isvalid(h)";
            buf(end+1,1) = "                    delete(h);";
            buf(end+1,1) = "                end";
            buf(end+1,1) = "            catch";
            buf(end+1,1) = "            end";
            buf(end+1,1) = "        end";
            buf(end+1,1) = "";
            buf(end+1,1) = "        function tf = isValidationError(~, ME)";
            buf(end+1,1) = "            tf = startsWith(ME.identifier, 'MATLAB:validators') ...";
            buf(end+1,1) = "                || startsWith(ME.identifier, 'MATLAB:validation') ...";
            buf(end+1,1) = "                || strcmp(ME.identifier, 'MATLAB:type:InvalidInputSize') ...";
            buf(end+1,1) = "                || strcmp(ME.identifier, 'MATLAB:invalidType') ...";
            buf(end+1,1) = "                || contains(ME.identifier, 'expectedType', 'IgnoreCase', true);";
            buf(end+1,1) = "        end";
            buf(end+1,1) = "";
            buf(end+1,1) = "        function assertReasonable(testCase, value)";
            buf(end+1,1) = "            if isnumeric(value) && ~isempty(value)";
            buf(end+1,1) = "                testCase.verifyFalse(all(isnan(value(:))), ...";
            buf(end+1,1) = "                    'All-NaN numeric output is suspicious');";
            buf(end+1,1) = "            end";
            buf(end+1,1) = "            testCase.verifyTrue(true);";
            buf(end+1,1) = "        end";
            buf(end+1,1) = "";
            buf(end+1,1) = "        function comp = findByTag(~, app, tag)";
            buf(end+1,1) = "            comp = [];";
            buf(end+1,1) = "            try";
            buf(end+1,1) = "                fig = [];";
            buf(end+1,1) = "                pn = properties(app);";
            buf(end+1,1) = "                for k = 1:numel(pn)";
            buf(end+1,1) = "                    v = app.(pn{k});";
            buf(end+1,1) = "                    if isa(v, 'matlab.ui.Figure')";
            buf(end+1,1) = "                        fig = v; break;";
            buf(end+1,1) = "                    end";
            buf(end+1,1) = "                end";
            buf(end+1,1) = "                if isempty(fig), return; end";
            buf(end+1,1) = "                comp = findobj(fig, 'Tag', tag);";
            buf(end+1,1) = "            catch";
            buf(end+1,1) = "            end";
            buf(end+1,1) = "        end";
            buf(end+1,1) = "";
            buf(end+1,1) = "        function runExample(~, text)";
            buf(end+1,1) = "            eval(text);";
            buf(end+1,1) = "        end";
            buf(end+1,1) = "    end";
            buf(end+1,1) = "";
        end

        function ctor = findConstructor(obj)
            ctor = [];
            for k = 1:numel(obj.Model.Methods)
                if strcmp(obj.Model.Methods(k).Name, obj.Model.ClassName)
                    ctor = obj.Model.Methods(k);
                    return;
                end
            end
            % Synthesise a no-arg constructor signature.
            ctor = autotest.SourceModel.makeFcn(obj.Model.ClassName);
        end

        function expr = formatCall(obj, fcn, args, kind)
            if isempty(args)
                argList = '';
            else
                argList = args;
            end
            switch kind
                case 'function'
                    expr = sprintf('%s(%s)', fcn.Name, argList);
                case 'method'
                    expr = sprintf('testCase.Instance.%s(%s)', fcn.Name, argList);
                case 'static'
                    expr = sprintf('%s.%s(%s)', obj.Model.ClassName, fcn.Name, argList);
                otherwise
                    expr = sprintf('%s(%s)', fcn.Name, argList);
            end
        end

        function expr = formatCallExplicit(obj, fcn, args, kind)
            expr = obj.formatCall(fcn, args, kind);
        end

        function expr = randomArgsExpr(~, fcn)
            parts = strings(0,1);
            for k = 1:numel(fcn.Inputs)
                if strcmp(fcn.Inputs{k}, 'varargin')
                    break;
                end
                parts(end+1,1) = "rand(1, randi(5))"; %#ok<AGROW>
            end
            if isempty(parts)
                expr = '';
            else
                expr = char(strjoin(parts, ', '));
            end
        end
    end

    % --- Static helpers consumed at test runtime --------------------------
    methods (Static)
        function safeDelete(obj)
            try
                if ~isempty(obj) && isobject(obj) && isvalid(obj)
                    delete(obj);
                end
            catch
                % ignore
            end
        end

        function tf = isValidationError(ME)
            tf = startsWith(ME.identifier, 'MATLAB:validators') ...
                || startsWith(ME.identifier, 'MATLAB:validation') ...
                || strcmp(ME.identifier, 'MATLAB:type:InvalidInputSize') ...
                || strcmp(ME.identifier, 'MATLAB:invalidType') ...
                || contains(ME.identifier, 'expectedType', 'IgnoreCase', true);
        end

        function assertReasonable(testCase, value)
            if isnumeric(value) && ~isempty(value)
                testCase.verifyFalse(all(isnan(value(:))), ...
                    'All-NaN numeric output is suspicious');
            end
            testCase.verifyTrue(true);
        end

        function comp = findByTag(app, tag)
            comp = [];
            try
                fig = [];
                props = properties(app);
                for k = 1:numel(props)
                    p = props{k};
                    v = app.(p);
                    if isa(v, 'matlab.ui.Figure')
                        fig = v; break;
                    end
                end
                if isempty(fig), return; end
                comp = findobj(fig, 'Tag', tag);
            catch
                comp = [];
            end
        end

        function runExample(text)
            % Example blocks may include the function call we're testing
            % and assignments.  Wrap them in a try/catch so the example
            % runner reports a clean error site to verifyWarningFree.
            evalin('caller', text);
        end

        function s = escapeString(text)
            % For use inside sprintf format strings (escapes %, \n, \r, \\,
            % single quotes for the surrounding char-vector literal).
            s = strrep(text, '\', '\\');
            s = strrep(s, '''', '''''');
            s = strrep(s, sprintf('\n'), '\\n');
            s = strrep(s, sprintf('\r'), '\\r');
            s = strrep(s, '%', '%%');
        end

        function s = escapeCharLiteral(text)
            % For use inside a plain '...' char-vector literal: only single
            % quotes need escaping (