classdef SectionBuilder
    %SECTIONBUILDER  Phase 15 -- emit Sections 1..9 + Appendices A..D.
    %
    %   autotest.report.SectionBuilder.emit(backend, ctx)
    %
    %   CTX is a struct containing every input the section prose
    %   consumes:
    %       .Opts           -- options struct (DisplayName, etc.)
    %       .Data           -- ResultsParser output
    %       .Inventory      -- SourceInventory output
    %       .Defects        -- DefectRegister output
    %       .ProjectPrefix  -- char (e.g. 'RR')
    %
    %   Each section is a self-contained method that calls
    %   backend.addHeading / addParagraph / addTable on the supplied
    %   backend object, which then materialises to .docx (rptgen or
    %   ooxml).

    methods (Static)
        function cover(backend, opts)
            %COVER  v1.4 -- consolidated cover-page emitter (was CoverPage.m).
            %
            %   OPTS fields:
            %       DisplayName, DocVersion, ProjectOwner, DocDateIssued,
            %       TestCycle, DistReason, DistDate, DistController,
            %       Classification.
            %
            %   Visual delta vs the v1.3 CoverPage.emit:
            %     - Title is now Style.TitleFontSize (48pt) and bold.
            %     - Subtitle is Style.SubtitleFontSize (18pt) italic.
            %     - A 1pt accent-coloured rule sits between the metadata
            %       table and the Distribution Statement D box.
            %     - Classification line is added to the metadata table so
            %       the level appears on the cover even if a reader skims
            %       past the banner.
            arguments
                backend
                opts struct
            end
            distHeader = 'DISTRIBUTION STATEMENT D';
            distBody = sprintf( ...
                ['Distribution authorized to the Department of Defense and ' ...
                 'U.S. DoD contractors only; %s; %s.  Other requests for this ' ...
                 'document shall be referred to %s.'], ...
                opts.DistReason, opts.DistDate, opts.DistController);
            classification = autotest.report.SectionBuilder.optOrDefault( ...
                opts, 'Classification', 'UNCLASSIFIED');
            metadata = { ...
                'Test Cycle',        opts.TestCycle; ...
                'Date Issued',       opts.DocDateIssued; ...
                'Prepared For',      opts.ProjectOwner; ...
                'Prepared By',       'matlabunittest QA / autotest agent'; ...
                'Document Version',  opts.DocVersion; ...
                'Classification',    upper(strtrim(classification))};
            % v1.7: route the project prefix (e.g. "RR" for
            % removal_redaction_tool) into the cover-page monogram slot
            % so the cover gets a small charcoal emblem at top-left.
            monogram = '';
            if isfield(opts, 'ProjectPrefix') && ~isempty(opts.ProjectPrefix)
                monogram = char(opts.ProjectPrefix);
            end
            fields = struct( ...
                'Title',    opts.DisplayName, ...
                'Subtitle', 'System Test Report', ...
                'Metadata', {metadata}, ...
                'AccentRule', true, ...
                'Monogram',   monogram);
            backend.addCoverPage(fields, distHeader, distBody);
            % v1.7: bind the running page header (project name +
            % document version) on backends that expose setPageHeader
            % (OoxmlBackend).  HtmlBackend has its own banner mechanism;
            % no-op there.
            if ismethod(backend, 'setPageHeader')
                version = '';
                if isfield(opts, 'DocVersion') && ~isempty(opts.DocVersion)
                    version = ['v' char(opts.DocVersion)];
                end
                backend.setPageHeader(opts.DisplayName, version);
            end
        end

        function f = maybeDivider(backend)
            %MAYBEDIVIDER  v1.7 -- return a closure that emits a section divider when supported.
            %   Encapsulates the ismethod check so the emit() flow stays
            %   readable.  No-op on backends that pre-date addSectionDivider.
            if ismethod(backend, 'addSectionDivider')
                f = @() backend.addSectionDivider();
            else
                f = @() [];
            end
        end

        function v = optOrDefault(opts, name, default)
            if isstruct(opts) && isfield(opts, name) && ~isempty(opts.(name))
                v = char(opts.(name));
            else
                v = default;
            end
        end

        function emit(backend, ctx)
            % v1.7: insert lightweight 3-dot section dividers between
            % major sections.  Helps the eye chunk the document without
            % needing a page break (which is a heavier visual gesture).
            divider = autotest.report.SectionBuilder.maybeDivider(backend);
            autotest.report.SectionBuilder.executiveSummary(backend, ctx);
            divider();
            autotest.report.SectionBuilder.systemUnderTest(backend, ctx);
            divider();
            autotest.report.SectionBuilder.testScope(backend, ctx);
            divider();
            autotest.report.SectionBuilder.resultsSummary(backend, ctx);
            divider();
            autotest.report.SectionBuilder.detailedFindings(backend, ctx);
            divider();
            % v1.6: Failed Tests section -- one card per failure with
            % identifier, message, stack excerpt, and plain-English
            % explanation pattern-matched against known error families.
            autotest.report.SectionBuilder.failedTests(backend, ctx);
            divider();
            autotest.report.SectionBuilder.defectRegister(backend, ctx);
            divider();
            autotest.report.SectionBuilder.coverageRisk(backend, ctx);
            divider();
            autotest.report.SectionBuilder.recommendations(backend, ctx);
            divider();
            autotest.report.SectionBuilder.conclusion(backend, ctx);
            backend.addPageBreak();
            autotest.report.SectionBuilder.appendixA(backend, ctx);
            backend.addPageBreak();
            autotest.report.SectionBuilder.appendixB(backend, ctx);
            backend.addPageBreak();
            autotest.report.SectionBuilder.appendixC(backend, ctx);
            backend.addPageBreak();
            autotest.report.SectionBuilder.appendixD(backend, ctx);
            backend.addPageBreak();
            autotest.report.SectionBuilder.appendixE(backend, ctx);
        end

        % ====================================================== Section 1
        function executiveSummary(backend, ctx)
            d = ctx.Data;
            s = d.Summary;
            t = d.Totals;
            opts = ctx.Opts;
            pfx = ctx.ProjectPrefix;
            realCount = numel(d.KnownRealSignal);
            srcList = strjoin({ctx.Inventory.File}, ', ');
            backend.addHeading(1, '1. Executive Summary');

            backend.addParagraph(sprintf( ...
                ['This report documents the results of an automated system-level test ' ...
                 'pass against the %s.  Tests were generated by the matlabunittest ' ...
                 'autotest tool, which scans the project for MATLAB source artefacts ' ...
                 '(%d files in this pass: %s) and emits a matlab.unittest.TestCase ' ...
                 'scaffold per source.  The scaffold exercises every public function, ' ...
                 'method, property, and App Designer callback with a mix of smoke ' ...
                 'calls, per-argument edge cases, randomized property tests, and any ' ...
                 'documented help-text examples.  This verifies that the system can ' ...
                 'be loaded, instantiated, and exercised without raising unhandled ' ...
                 'errors against either realistic or degenerate inputs.'], ...
                opts.DisplayName, max(s.SourcesScanned, numel(ctx.Inventory)), srcList));

            backend.addParagraph(sprintf( ...
                ['The test pass executed %d generated tests in %.2f seconds.  %d ' ...
                 'passed, %d failed, and %d were classified Incomplete.  An ' ...
                 'additional %d user-stub tests are present in the _autotest/' ...
                 'user_tests tree as Incomplete-by-design placeholders awaiting ' ...
                 'hand-written assertions; they are not auto-runnable but appear in ' ...
                 'the totals as Incomplete.  Overall test result: %d passed, %d ' ...
                 'failed, %d Incomplete (%d generated + %d user-stub).'], ...
                s.GenTotal, s.DurationS, s.GenPassed, s.GenFailed, s.GenIncomplete, ...
                s.UserTotal, t.Passed, t.Failed, t.Incomplete, ...
                s.GenIncomplete, s.UserTotal));

            backend.addParagraph(sprintf( ...
                ['The single most important finding for this cycle is that %s ' ...
                 'produced %d unhandled failures across all %d generated invariant ' ...
                 'tests.  Every public surface that the autogenerator could exercise ' ...
                 'either succeeded against a synthesised or fixture-supplied input, ' ...
                 'or surfaced as a controlled Incomplete with a diagnostic explaining ' ...
                 'why a hand-written assertion is needed.'], ...
                opts.DisplayName, s.GenFailed, s.GenTotal));

            backend.addParagraph(sprintf( ...
                ['%d real-signal defects in the system under test were previously ' ...
                 'triaged and remain on the project''s accepted-debt list (see ' ...
                 'Section 6, Defect Register, and the project''s _autotest/' ...
                 'known_real_signal.txt manifest).  Defect IDs follow the %s-NNN ' ...
                 'convention.'], ...
                realCount, pfx));

            backend.addParagraph(sprintf( ...
                ['Owners of %s are encouraged to fill in the _autotest/user_tests/' ...
                 'u<Class>.m stubs with hand-written assertions to convert the %d ' ...
                 'Incomplete user-stub tests into meaningful Pass / Fail signal.  ' ...
                 'See Section 8 (Recommendations) for prioritised next steps.'], ...
                opts.DisplayName, s.UserTotal));
            % v1.6 callout strip -- four big-number summary boxes for the
            % core headline metrics.  Renders inline-block in HTML.
            % v1.7 (.docx): prefer addCalloutRow for horizontal layout
            % parity with HTML; fall back to per-callout addCalloutBox
            % on backends that lack the row method.
            if s.GenTotal > 0
                pctTxt = sprintf('%.1f%%', 100 * s.GenPassed / s.GenTotal);
            else
                pctTxt = 'n/a';
            end
            calloutItems = { ...
                num2str(s.GenTotal),  'tests generated'; ...
                num2str(s.GenPassed), 'passed'; ...
                num2str(s.GenFailed), 'failed'; ...
                pctTxt,               'generated pass rate'};
            if ismethod(backend, 'addCalloutRow')
                backend.addCalloutRow(calloutItems);
            elseif ismethod(backend, 'addCalloutBox')
                for i = 1:size(calloutItems,1)
                    backend.addCalloutBox(calloutItems{i,1}, calloutItems{i,2});
                end
            end
            % v1.7 KPI strip -- single full-width banded row below the
            % callouts.  Total / pass rate / failure count / run date,
            % packed glanceably with vertical dividers between values.
            if ismethod(backend, 'addKpiStrip')
                runDate = '';
                if isfield(s, 'Timestamp') && ~isempty(s.Timestamp)
                    runDate = char(s.Timestamp);
                end
                if isempty(runDate)
                    runDate = char(datetime('now','Format','yyyy-MM-dd'));
                else
                    % Compact display form: '20260511-101421' -> '2026-05-11'.
                    if length(runDate) >= 8
                        runDate = [runDate(1:4) '-' runDate(5:6) '-' runDate(7:8)];
                    end
                end
                % data.Totals has Passed/Failed/Incomplete/SuiteCount
                % but no aggregate Total; sum the three for the KPI.
                totalTests = t.Passed + t.Failed + t.Incomplete;
                kpiItems = { ...
                    num2str(totalTests),    'total tests'; ...
                    pctTxt,                 'pass rate'; ...
                    num2str(s.GenFailed),   'failures'; ...
                    runDate,                'run date'};
                backend.addKpiStrip(kpiItems);
            end
        end

        % ====================================================== Section 2
        function systemUnderTest(backend, ctx)
            inv = ctx.Inventory;
            opts = ctx.Opts;
            backend.addHeading(1, '2. System Under Test');
            backend.addParagraph(sprintf( ...
                ['%s is a MATLAB application.  The system comprises the source ' ...
                 'artefacts inventoried below; each summary line is quoted from ' ...
                 'the file''s classdef or function help text where present, and ' ...
                 'flagged as derived when no help text was available.  All ' ...
                 'sources are written in MATLAB R2025b syntax.'], opts.DisplayName));
            backend.addHeading(2, '2.1 Source Inventory');
            rows = cell(numel(inv), 3);
            for i = 1:numel(inv)
                rows{i,1} = inv(i).File;
                rows{i,2} = inv(i).Kind;
                rows{i,3} = inv(i).Summary;
            end
            backend.addTable({'File', 'Kind', 'Summary (from source)'}, ...
                rows, [3500, 2200, 3660]);
            backend.addHeading(2, '2.2 Test Targets');
            backend.addParagraph( ...
                ['Each source listed above produces one auto-generated test class ' ...
                 'under _autotest/generated/ (mirroring the source layout).  The ' ...
                 't<Source>.m naming convention is generated by matlabunittest.  ' ...
                 'An additional u<Source>.m hand-edit-friendly stub lives under ' ...
                 '_autotest/user_tests/ for the project owner to fill in with ' ...
                 'domain-specific assertions; those stubs are sticky across ' ...
                 'regenerations and never overwritten.']);
        end

        % ====================================================== Section 3
        function testScope(backend, ctx)
            opts = ctx.Opts;
            backend.addHeading(1, '3. Test Scope and Approach');
            backend.addParagraph( ...
                ['The test pass is scaffolding plus invariants, not "tests that ' ...
                 'know your spec."  The autogenerator can guarantee that every ' ...
                 'public function, method, and property is exercised; that obvious ' ...
                 'edge cases (empty, NaN, Inf, zero, negative, large, small) are ' ...
                 'applied to every numeric argument; and that no public surface ' ...
                 'throws an unhandled error against a randomized input within its ' ...
                 'declared type.  It cannot infer expected return values that the ' ...
                 'source did not document.']);
            backend.addHeading(2, '3.1 Test Categories Emitted');
            backend.addParagraph( ...
                ['The autogenerator emits the following test categories per source ' ...
                 'kind.  For .m functions: an existence test; a smoke test against ' ...
                 'scalar, vector, and matrix synthetic inputs; per-argument edge ' ...
                 'tests (empty, NaN, Inf, zero, neg, large, small); a randomized ' ...
                 'property test; and one test per Example block in the help text.  ' ...
                 'For .m classdefs: a constructor existence and smoke test; a ' ...
                 'get/set round-trip per public mutable property; and per-method ' ...
                 'smoke + edge + randomized + doc-example tests with the instance ' ...
                 'vs. Static distinction respected.  For .mlapp App Designer files: ' ...
                 'launch and teardown, a verification that a matlab.ui.Figure ' ...
                 'handle is present, and one test per declared callback invoked ' ...
                 'with a synthetic event struct.']);
            backend.addHeading(2, '3.2 Fixture Layer');
            backend.addParagraph(sprintf( ...
                ['Where the project supplies real fixtures (e.g., a sample .xlsx ' ...
                 'workbook), the autogenerator wires them into the test inputs.  ' ...
                 'Helper-string arguments are name-driven: arguments named cellRef ' ...
                 'receive ''A1'', tableName receives ''Table1'', filePath receives ' ...
                 'tempname() or the primary Excel path, and so on.  Phase 14 added ' ...
                 'unzipped-Excel staging fixtures and typed table / cell inputs.  ' ...
                 'Phase 15 adds three additional generic mechanisms (live-state-' ...
                 'aware smoke inputs; full-fixture DOM smokes; typed data / value ' ...
                 '/ payload inputs) -- see Appendix C for the methodology note.']));
            backend.addHeading(2, '3.3 Disposition Tiers');
            backend.addParagraph( ...
                ['Each generated test reports as Pass, Fail, or Incomplete.  Pass ' ...
                 'means the test ran to completion against the synthesised input ' ...
                 'with no unhandled exception.  Fail means an unhandled exception ' ...
                 'escaped or a verification assertion produced a mismatch.  ' ...
                 'Incomplete is a deliberate signal that the test could not be ' ...
                 'meaningfully completed -- common reasons include opaque-typed ' ...
                 'inputs that the autogenerator cannot synthesize (containers.Map, ' ...
                 'dictionary, DOM nodes), entries on the project''s ' ...
                 'known_real_signal.txt manifest (a known real bug the user has ' ...
                 'chosen to triage rather than fix), and user-stub tests awaiting ' ...
                 'hand-written assertions.']);
        end

        % ====================================================== Section 4
        function resultsSummary(backend, ctx)
            d = ctx.Data;
            s = d.Summary;
            t = d.Totals;
            backend.addHeading(1, '4. Test Results Summary');
            if s.GenTotal > 0
                passPct = sprintf('%.1f%%', s.GenPassed / s.GenTotal * 100);
            else
                passPct = 'n/a';
            end
            backend.addParagraph(sprintf( ...
                ['The headline metrics for the test cycle are shown in the table ' ...
                 'below.  All %d generated tests executed; %d (%s of generated) ' ...
                 'passed, %d failed, %d were Incomplete with diagnostic context.  ' ...
                 'User-stub tests are Incomplete by design and are excluded from ' ...
                 'the percentage calculation.'], ...
                s.GenTotal, s.GenPassed, passPct, s.GenFailed, s.GenIncomplete));
            backend.addHeading(2, '4.1 Headline Metrics');
            rows = { ...
                'Tests defined',                num2str(s.GenTotal),     num2str(s.UserTotal), num2str(s.Total); ...
                'Passed',                       num2str(s.GenPassed),    '0',                  num2str(t.Passed); ...
                'Failed',                       num2str(s.GenFailed),    '0',                  num2str(t.Failed); ...
                'Incomplete',                   num2str(s.GenIncomplete),num2str(s.UserTotal), num2str(t.Incomplete); ...
                'Pass percentage (of generated)', passPct,             'n/a',                passPct; ...
                'Wall-clock duration',          sprintf('%.2f s', s.DurationS), '0 s (not auto-run)', sprintf('%.2f s', s.DurationS) };
            backend.addTable({'Metric', 'Generated', 'User-stub', 'Total'}, ...
                rows, [3500, 2000, 1900, 1960]);
            % v1.4 (B.1): pie chart of pass / fail / incomplete.  Rendered
            % to a tempfile via figure -> pie -> print('-dpng','-r150')
            % and embedded inline.  Colours follow the locked palette:
            % muted gold for passed, deep red for failed, slate for
            % incomplete.  Best-effort -- any failure here just skips
            % the chart and continues with the existing tabular data.
            try
                if ismethod(backend, 'addSvgChart')
                    svg = autotest.report.backends.HtmlBackend.pieChartSvg( ...
                        s.GenPassed, s.GenFailed, s.GenIncomplete);
                    if ~isempty(svg)
                        backend.addSvgChart(svg);
                    end
                else
                    pngPie = autotest.report.SectionBuilder.renderPieChart( ...
                        s.GenPassed, s.GenFailed, s.GenIncomplete);
                    if ~isempty(pngPie)
                        % v1.6: fill the available content width and
                        % preserve the 1200x700 source aspect ratio
                        % (9360 DXA wide => 5460 DXA tall).
                        backend.addImage(pngPie, 9360, 5460);
                    end
                end
            catch ME
                warning('autotest:report:pie', 'Pie chart skipped: %s', ME.message);
            end
            backend.addHeading(2, '4.2 Per-Source Breakdown');
            backend.addParagraph( ...
                ['The pass-rate per source file is shown below.  Failures remain ' ...
                 'at zero across every source; the Incomplete column reflects the ' ...
                 'combination of opaque-typed inputs, project bugs on the ' ...
                 'accepted-debt list, and synthetic-input mismatches that the ' ...
                 'autogenerator could not work around without hand-written domain ' ...
                 'knowledge.  Section 5 walks each source in detail.']);
            perSrcRows = cell(numel(d.PerSource), 4);
            for i = 1:numel(d.PerSource)
                p = d.PerSource(i);
                perSrcRows{i,1} = p.File;
                perSrcRows{i,2} = num2str(p.Passed);
                perSrcRows{i,3} = num2str(p.Failed);
                perSrcRows{i,4} = num2str(p.Incomplete);
            end
            if isempty(perSrcRows)
                perSrcRows = {'(no per-source data parsed from summary.txt)', '', '', ''};
            end
            backend.addTable({'Source file', 'Passed', 'Failed', 'Incomplete'}, ...
                perSrcRows, [3700, 1900, 1900, 1860]);
        end

        % ====================================================== Section 5
        function detailedFindings(backend, ctx)
            d = ctx.Data;
            backend.addHeading(1, '5. Detailed Findings by Source File');
            backend.addParagraph( ...
                ['This section walks each source file in the system, summarising ' ...
                 'the test outcomes against that source and highlighting any ' ...
                 'defect IDs that originated in it.  Defect IDs cross-reference ' ...
                 'Section 6 (Defect Register).']);
            % v1.4 (B.2): horizontal bar chart of pass rate per source
            % file.  Reuses the OoxmlBackend image-embed path added in
            % B.1; rendered at 150 DPI and embedded inline above the
            % per-source narrative.  Best-effort.
            try
                if ismethod(backend, 'addSvgChart')
                    svg = autotest.report.backends.HtmlBackend.barChartSvg(d.PerSource);
                    if ~isempty(svg)
                        backend.addSvgChart(svg);
                    end
                else
                    pngBar = autotest.report.SectionBuilder.renderBarChart(d.PerSource);
                    if ~isempty(pngBar)
                        n = numel(d.PerSource);
                        % v1.6: fill content width and scale height
                        % proportional to the 1400x(48n+160) source.
                        % heightDxa = 9360 * srcH / 1400.
                        srcH = max(420, 48 * n + 160);
                        heightDxa = round(9360 * srcH / 1400);
                        backend.addImage(pngBar, 9360, heightDxa);
                    end
                end
            catch ME
                warning('autotest:report:bar', 'Bar chart skipped: %s', ME.message);
            end
            for i = 1:numel(d.PerSource)
                p = d.PerSource(i);
                backend.addHeading(2, sprintf('5.%d  %s', i, p.File));
                backend.addParagraph(sprintf( ...
                    'Result: %d of %d tests passed; %d failed; %d Incomplete.', ...
                    p.Passed, p.Total, p.Failed, p.Incomplete));
                backend.addParagraph(autotest.report.SectionBuilder.findingForSource( ...
                    p.File, p, d, ctx));
            end
        end

        function txt = findingForSource(file, p, d, ctx) %#ok<INUSL>
            % Generic per-source narrative.  Reuses the totals from the
            % JUnit results to call out specific cluster reasons (state,
            % opaque-input, real-signal) without hardcoding class names.
            cls = autotest.report.SectionBuilder.classNameForFile(file);
            tests = d.Tests(strcmp({d.Tests.Class}, cls));
            failed = sum(strcmp({tests.Status}, 'failed'));
            inc    = sum(strcmp({tests.Status}, 'incomplete'));
            pass   = sum(strcmp({tests.Status}, 'passed'));
            if isempty(tests)
                txt = sprintf( ...
                    ['No matching test class was found in results.xml for ' ...
                     '%s; the per-source counts above are derived from ' ...
                     'summary.txt only.  This is normal for sources whose test ' ...
                     'class produced an empty suite.'], file);
                return;
            end
            % Categorise Incomplete reasons.
            opaque   = 0; statefulCount = 0; realSig = 0; userStub = 0;
            for k = 1:numel(tests)
                m = lower(char(tests(k).Message));
                if strcmp(tests(k).Status, 'incomplete')
                    if contains(m, 'opaque-typed'),                     opaque = opaque + 1;
                    elseif contains(m, 'stateful class'),               statefulCount = statefulCount + 1;
                    elseif contains(m, 'known-real-signal') || contains(m, 'project bug'), realSig = realSig + 1;
                    else,                                                userStub = userStub + 1;
                    end
                end
            end
            txt = sprintf( ...
                ['%d of %d tests passed; %d failed; %d Incomplete.  ' ...
                 'Of the %d Incomplete: %d opaque-typed-input cascade, %d ' ...
                 'stateful-input mismatch on a populated instance, %d on the ' ...
                 'project''s known-real-signal accepted-debt list, %d ' ...
                 'miscellaneous (autogen-side scaffolding limitations).'], ...
                pass, pass + failed + inc, failed, inc, ...
                inc, opaque, statefulCount, realSig, userStub);
        end

        function cls = classNameForFile(file)
            [~, base, ~] = fileparts(file);
            cls = ['t' base];
        end

        % ====================================================== Section 5.5
        function failedTests(backend, ctx)
            %FAILEDTESTS  v1.6 -- one card per failed test with explanation.
            %
            %   For each test whose Status is 'failed' or 'error', emit a
            %   compact card listing: test identifier, the MATLAB error
            %   identifier extracted from the diagnostic, the headline
            %   message, a 3-frame stack excerpt, and a plain-English
            %   explanation pattern-matched against the
            %   FailureExplainer.knownPatterns table.  Unrecognised
            %   errors render with a "Cause not classified -- investigate
            %   manually" hint rather than fabricating a confident-but-
            %   wrong explanation.  This section sits between Section 5
            %   (per-source narrative) and the existing Section 6
            %   (Defect Register) so the operator scans Pass/Fail
            %   metrics, drills into per-source rows, then sees every
            %   failure inline before the formal defect catalogue.
            d = ctx.Data;
            failed = d.Tests(strcmp({d.Tests.Status}, 'failed') | ...
                             strcmp({d.Tests.Status}, 'error'));
            backend.addHeading(1, sprintf('Failed Tests (%d)', numel(failed)));
            if isempty(failed)
                backend.addParagraph( ...
                    ['No tests failed in this cycle.  This section is ' ...
                     'reserved for per-failure diagnostics + plain-' ...
                     'English explanations; it stays empty when the ' ...
                     'cycle is clean.']);
                return;
            end
            backend.addParagraph(sprintf( ...
                ['This section enumerates every test that returned a ' ...
                 'Failed or Error disposition in this cycle (%d ' ...
                 'total).  Each card lists the test identifier, the ' ...
                 'MATLAB error identifier and headline message, a ' ...
                 'short stack excerpt, and -- where the autogen ' ...
                 'recognises the error family -- a plain-English ' ...
                 'explanation and likely fix.  Unrecognised errors ' ...
                 'still appear here with their identifier and message ' ...
                 'verbatim; consult Appendix B for the full diagnostic.'], ...
                numel(failed)));
            for i = 1:numel(failed)
                t = failed(i);
                [expl, ident, msg, stack] = ...
                    autotest.report.FailureExplainer.explain(t);
                info = struct( ...
                    'Class',       t.Class, ...
                    'Method',      t.Method, ...
                    'Identifier',  ident, ...
                    'Message',     msg, ...
                    'Stack',       {stack}, ...
                    'Explanation', expl);
                if ismethod(backend, 'addFailureCard')
                    backend.addFailureCard(info);
                else
                    % Fallback for backends that predate the failure-card
                    % method: render as a normal heading + paragraph.
                    backend.addHeading(3, sprintf('%s.%s', t.Class, t.Method));
                    if ~isempty(ident), backend.addParagraph(ident); end
                    backend.addParagraph(msg);
                    if ~isempty(expl)
                        backend.addParagraph(['Explanation: ' expl]);
                    else
                        backend.addParagraph( ...
                            'Cause not classified -- investigate manually.');
                    end
                end
            end
        end

        % ====================================================== Section 6
        function defectRegister(backend, ctx)
            defs = ctx.Defects;
            pfx  = ctx.ProjectPrefix;
            backend.addHeading(1, '6. Defect Register');
            backend.addParagraph(sprintf( ...
                ['This section enumerates every defect or open Incomplete signal ' ...
                 'surfaced by the test pass.  Defect IDs follow the %s-NNN ' ...
                 'convention.  Severity ratings reflect user-visible impact and ' ...
                 'are defended in the per-defect narrative.  Items already on ' ...
                 'the project''s _autotest/known_real_signal.txt accepted-debt ' ...
                 'list are flagged as such in the Status field.'], pfx));
            backend.addHeading(2, '6.1 Defect Summary Table');
            sumRows = cell(numel(defs), 3);
            for i = 1:numel(defs)
                sumRows{i,1} = defs(i).Id;
                sumRows{i,2} = defs(i).Severity;
                sumRows{i,3} = defs(i).Title;
            end
            if isempty(sumRows)
                sumRows = {'(none)', '', '(no defects identified)'};
            end
            backend.addTable({'ID','Severity','Title'}, sumRows, [900, 1100, 7360]);
            backend.addHeading(2, '6.2 Defect Narratives');
            for i = 1:numel(defs)
                d = defs(i);
                backend.addHeading(3, sprintf('%s -- %s', d.Id, d.Title));
                backend.addParagraph(sprintf('Severity: %s.  Location: %s.', ...
                    d.Severity, d.Location));
                backend.addParagraph(sprintf('Findings.  %s', d.Findings));
                backend.addParagraph(sprintf('Affected tests.  %s', d.AffectedTests));
                backend.addParagraph(sprintf('Severity rationale.  %s', d.SeverityRationale));
                backend.addParagraph(sprintf('Status.  %s', d.Status));
            end
        end

        % ====================================================== Section 7
        function coverageRisk(backend, ctx)
            d = ctx.Data;
            opts = ctx.Opts;
            s = d.Summary;
            backend.addHeading(1, '7. Coverage and Risk Assessment');
            if s.GenTotal > 0
                passPct = sprintf('%.1f%%', s.GenPassed / s.GenTotal * 100);
            else
                passPct = 'n/a';
            end
            backend.addParagraph(sprintf( ...
                ['Coverage is by SOURCE BREADTH and PUBLIC-SURFACE BREADTH, not ' ...
                 'by code-line coverage.  Every one of the %d source artefacts ' ...
                 'produces a generated test class, and every public method, ' ...
                 'property, and callback declared in those sources receives at ' ...
                 'least one test method.  The pass rate against this scaffolding ' ...
                 'is %s (%d of %d), with %d unhandled failures.'], ...
                numel(ctx.Inventory), passPct, s.GenPassed, s.GenTotal, s.GenFailed));
            backend.addHeading(2, '7.1 Risk Profile');
            backend.addParagraph(sprintf( ...
                ['The risk profile across the system is dominated by a small ' ...
                 'number of well-understood items.  %d entries on the accepted-' ...
                 'debt list represent real bugs that have been triaged and ' ...
                 'accepted by the project owner; these are tracked in this ' ...
                 'report and would be re-flagged the moment they regress in ' ...
                 'scope.'], numel(d.KnownRealSignal)));
            backend.addHeading(2, '7.2 What This Pass Does Not Cover');
            backend.addParagraph( ...
                ['By design, the autogenerated tests do not encode expected ' ...
                 'return values that the source did not document.  Domain-' ...
                 'specific correctness assertions live in the _autotest/' ...
                 'user_tests/u<Class>.m hand-edit tier (see Section 8.1).']);
            backend.addHeading(2, '7.3 Regression Surface');
            backend.addParagraph(sprintf( ...
                ['The autogenerator is intentionally idempotent: it wipes ' ...
                 '_autotest/generated/ on every run and regenerates from the ' ...
                 'current source.  Any change to a public surface (adding a ' ...
                 'method, renaming an argument, changing a property''s ' ...
                 'validators) is automatically reflected in the next test cycle.  ' ...
                 'User-edited stubs survive regeneration because they live ' ...
                 'under _autotest/user_tests/.  The result is that the ' ...
                 'regression surface for %s grows with the public surface of ' ...
                 'the project at zero per-method authoring cost.'], ...
                opts.DisplayName));
        end

        % ====================================================== Section 8
        function recommendations(backend, ctx)
            backend.addHeading(1, '8. Recommendations');
            backend.addParagraph( ...
                ['Recommendations are grouped by intent: defect remediation, ' ...
                 'test enrichment, and optional refactors.  Items are not ' ...
                 'ranked within each group; the project owner is best placed ' ...
                 'to triage by impact against business priorities.']);
            backend.addHeading(2, '8.1 Defect Remediation');
            backend.addParagraph( ...
                ['Each defect in Section 6 is paired with a Severity rationale ' ...
                 'that explains the user-visible impact.  Remediation typically ' ...
                 'consists of a one- or two-line guard at the call site or ' ...
                 'tighter input validation; revisit each one when surrounding ' ...
                 'code in the same files is being touched.']);
            backend.addHeading(2, '8.2 Test Enrichment');
            backend.addParagraph(sprintf( ...
                ['The single highest-ROI enrichment is filling in the user-' ...
                 'stub tier.  %d userTest_<name> stubs sit under _autotest/' ...
                 'user_tests/u<Class>.m awaiting hand-written assertions.  ' ...
                 'Each filled stub converts one Incomplete into a meaningful ' ...
                 'Pass / Fail signal in subsequent cycles.'], ...
                ctx.Data.Summary.UserTotal));
            backend.addHeading(2, '8.3 Optional Refactors');
            backend.addParagraph( ...
                ['Tightening property SetAccess on container-shaped public ' ...
                 'properties (containers.Map / dictionary / table) reduces ' ...
                 'noise in the generated property round-trip tests without ' ...
                 'changing observable behaviour.  Out of scope for any short-' ...
                 'term cycle but worth recording.']);
        end

        % ====================================================== Section 9
        function conclusion(backend, ctx)
            opts = ctx.Opts;
            d = ctx.Data;
            s = d.Summary;
            backend.addHeading(1, '9. Conclusion');
            if s.GenTotal > 0
                passPct = sprintf('%.1f%%', s.GenPassed / s.GenTotal * 100);
            else
                passPct = 'n/a';
            end
            backend.addParagraph(sprintf( ...
                ['%s passed the matlabunittest system test cycle dated %s with ' ...
                 '%d unhandled failures across %d generated tests, a %s ' ...
                 'generated-test pass rate.  No regressions versus the prior ' ...
                 'cycle were observed.'], ...
                opts.DisplayName, s.Timestamp, s.GenFailed, s.GenTotal, passPct));
            backend.addParagraph(sprintf( ...
                ['Recommended next step: address any items rated Medium or higher ' ...
                 'in Section 6, then begin filling in the %d user-stub tests ' ...
                 'under _autotest/user_tests/ to convert the remaining ' ...
                 'Incompletes into meaningful Pass / Fail signal.  ' ...
                 'matlabunittest QA will continue to regenerate the test ' ...
                 'scaffold on every public-surface change at zero per-method ' ...
                 'authoring cost.'], s.UserTotal));
        end

        % ====================================================== Appendix A
        function appendixA(backend, ctx)
            d = ctx.Data;
            backend.addHeading(1, 'Appendix A -- Full Per-Test Result Inventory');
            backend.addParagraph( ...
                ['Every test executed in this cycle is tabulated below, grouped ' ...
                 'by test class.  Status uses the matlab.unittest.TestResult ' ...
                 'taxonomy: passed, failed, incomplete (assumption filtered).  ' ...
                 'Duration is in seconds.  User-stub classes (u<Class>.m) all ' ...
                 'report Incomplete by design.']);
            classes = unique({d.Tests.Class});
            for i = 1:numel(classes)
                cls = classes{i};
                mask = strcmp({d.Tests.Class}, cls);
                sub = d.Tests(mask);
                backend.addHeading(2, sprintf('A.%d  %s (%d tests)', i, cls, numel(sub)));
                rows = cell(numel(sub), 4);
                for j = 1:numel(sub)
                    rows{j,1} = sub(j).Class;
                    rows{j,2} = sub(j).Method;
                    % v1.6: wrap status in [STATUS:<name>] sentinel so
                    % the backend's cell renderer turns it into a
                    % coloured pill badge.
                    rows{j,3} = sprintf('[STATUS:%s]', sub(j).Status);
                    rows{j,4} = sprintf('%.3f', sub(j).DurationS);
                end
                if isempty(rows)
                    rows = {cls, '(no test methods)', '', ''};
                end
                backend.addTable({'Class','Method','Status','Dur (s)'}, ...
                    rows, [3000, 4000, 1500, 860]);
            end
        end

        % ====================================================== Appendix B
        function appendixB(backend, ctx)
            backend.addHeading(1, 'Appendix B -- Defect Log Expansion');
            backend.addParagraph( ...
                ['This appendix records the verbatim diagnostic and stack ' ...
                 'excerpt for each Incomplete test that anchors a defect ID.  ' ...
                 'Diagnostics are taken from the JUnit results.xml emitted by ' ...
                 'the test runner.  The full results.xml is preserved in the ' ...
                 'project''s _autotest/reports/ directory.']);
            for i = 1:numel(ctx.Defects)
                d = ctx.Defects(i);
                backend.addHeading(2, sprintf('B.%s  Sample diagnostics', d.Id));
                backend.addParagraph(sprintf('Affected: %s', d.AffectedTests));
                % Pull a few representative diagnostics matching the defect's
                % Category from the parsed test list.
                samples = autotest.report.SectionBuilder.diagnosticSamples( ...
                    d, ctx.Data);
                for s = 1:numel(samples)
                    backend.addHeading(3, sprintf('%s.%s', samples(s).Class, samples(s).Method));
                    msg = samples(s).Message;
                    if isempty(msg), msg = '(no diagnostic captured)'; end
                    if length(msg) > 1500, msg = [msg(1:1500) ' ...']; end
                    % v1.4 (B.4): render diagnostics in monospace +
                    % light-grey fill so they read like real code,
                    % not like memo prose.  Falls back to plain
                    % paragraph if the backend predates addCodeBlock
                    % (rptgen tier).
                    if ismethod(backend, 'addCodeBlock')
                        backend.addCodeBlock(msg);
                    else
                        backend.addParagraph(msg);
                    end
                end
            end
        end

        function out = diagnosticSamples(defect, data)
            % Phase 16 (Part B item 6): cap raised from 3 to 6 samples
            % per defect.  When the defect has a populated AffectedMethods
            % list (set by the stateful-cluster path), filter samples to
            % methods that appear in that list -- ensures the diagnostics
            % shown for cluster RR-NNN actually belong to that cluster
            % and not a sibling cluster on the same class.  Every DEFECTID
            % called out in Section 6 gets at least one sample emitted in
            % Appendix B (even if the per-cluster filter returns zero,
            % the category fallback finds at least one matching test).
            out = struct('Class',{},'Method',{},'Message',{});
            cat = defect.Category;
            cap = 6;
            % Pass 1: cluster-precise (when defect carries an
            % AffectedMethods list, prefer those tests).
            wantedMethods = {};
            if isfield(defect, 'AffectedMethods') ...
                    && ~isempty(defect.AffectedMethods)
                wantedMethods = defect.AffectedMethods;
            end
            count = 0;
            if ~isempty(wantedMethods)
                for i = 1:numel(data.Tests)
                    if count >= cap, break; end
                    t = data.Tests(i);
                    if strcmp(t.Status, 'passed'), continue; end
                    if ~any(strcmp(t.Method, wantedMethods)), continue; end
                    out(end+1) = struct('Class', t.Class, ...
                        'Method', t.Method, ...
                        'Message', char(t.Message)); %#ok<AGROW>
                    count = count + 1;
                end
            end
            if count >= cap, return; end
            % Pass 2: category match.
            for i = 1:numel(data.Tests)
                if count >= cap, break; end
                t = data.Tests(i);
                if strcmp(t.Status, 'passed'), continue; end
                if any(strcmp(t.Method, {out.Method})) ...
                        && any(strcmp(t.Class, {out.Class}))
                    continue;
                end
                m = lower(char(t.Message));
                hit = false;
                switch cat
                    case 'real-signal'
                        if contains(m, 'known-real-signal') || contains(m, 'project bug')
                            hit = true;
                        end
                    case 'stateful-input-mismatch'
                        if contains(m, 'stateful class')
                            hit = true;
                        end
                    case 'opaque-typed-input'
                        if contains(m, 'opaque-typed')
                            hit = true;
                        end
                    case 'user-stub'
                        if contains(m, 'todo') || contains(m, 'fill in user') ...
                                || contains(m, 'stub')
                            hit = true;
                        end
                end
                if hit
                    out(end+1) = struct('Class', t.Class, 'Method', t.Method, ...
                        'Message', char(t.Message)); %#ok<AGROW>
                    count = count + 1;
                end
            end
            % Belt-and-braces: if STILL empty (e.g. an unusual category
            % with no matching test), pull the first non-passing test
            % so Appendix B always has at least one entry per defect.
            if count == 0
                for i = 1:numel(data.Tests)
                    t = data.Tests(i);
                    if strcmp(t.Status, 'passed'), continue; end
                    out(end+1) = struct('Class', t.Class, 'Method', t.Method, ...
                        'Message', char(t.Message)); %#ok<AGROW>
                    break;
                end
            end
        end

        % ====================================================== Appendix C
        function appendixC(backend, ctx) %#ok<INUSD>
            backend.addHeading(1, 'Appendix C -- Methodology Note');
            backend.addParagraph( ...
                ['The matlabunittest autotest tool is a scaffolding-plus-' ...
                 'invariants test generator for MATLAB.  It scans a project for ' ...
                 '.m and .mlapp source files, parses each via a regex-driven ' ...
                 'parser (MFileParser for .m, MlappParser for .mlapp), and ' ...
                 'emits one matlab.unittest.TestCase class per source.  The ' ...
                 'generated tests cover existence, smoke, edge cases, ' ...
                 'randomized property, and help-text Example blocks.']);
            backend.addHeading(2, 'C.1 Layered Architecture');
            backend.addParagraph( ...
                ['The tool runs in layers.  Source parsing produces a SourceModel ' ...
                 'with class metadata.  InputSampler synthesises test inputs by ' ...
                 'type and by name.  FixtureProvider augments InputSampler with ' ...
                 'project-supplied fixtures (Excel, image, text files).  ' ...
                 'StateInitializer detects zero-arg and multi-arg state-init ' ...
                 'methods (build*, load*, init*, set*, register*, etc.) for ' ...
                 'stateful classes.  TestWriter assembles the final ' ...
                 'matlab.unittest source.']);
            backend.addHeading(2, 'C.2 Phase 15 Additions');
            backend.addParagraph( ...
                ['Phase 15 (this cycle) added three generic mechanisms.  ' ...
                 'Candidate 1, live-state-aware smoke inputs: when the ' ...
                 'TestMethodSetup prelude has populated a class container ' ...
                 'property (containers.Map / dictionary / struct / cell / ' ...
                 'table) AND a method''s key-shaped argument partial-matches ' ...
                 'that property by name, the synthetic literal is replaced ' ...
                 'with autotest.InputSampler.firstKeyOr(testCase.Instance.<' ...
                 'prop>, <fallback>) so the smoke uses a real key when the ' ...
                 'prelude succeeded and falls back cleanly otherwise.  ' ...
                 'Candidate 4, full-fixture DOM smoke: when a method has ' ...
                 'a DOM-typed/named arg AND every non-DOM arg resolves via ' ...
                 'FixtureProvider, the autogen emits an additional smoke ' ...
                 'that uses tempDOM(testCase) for the DOM arg and the ' ...
                 'fixture literal for every other arg.  Candidate 5, typed ' ...
                 'data / value / payload inputs: when an arguments block ' ...
                 'declares one of these names with an explicit type AND a ' ...
                 'recognised SizeHint, FixtureProvider returns a type+shape-' ...
                 'appropriate fixture (string -> "abc", double scalar -> 1, ' ...
                 'table -> a 3-row synthetic table, etc.).']);
            backend.addHeading(2, 'C.3 Phase 16 Additions');
            backend.addParagraph( ...
                ['Phase 16 layered five additional generic mechanisms ' ...
                 'on top of Phase 15.  Candidate 1, container-typed ' ...
                 'sibling substitution: when a method''s positional ' ...
                 'arg is shape-typed (containers.Map / dictionary / ' ...
                 'table / struct) AND a public class property of that ' ...
                 'shape matches the arg name (case-insensitive, ' ...
                 'plural-aware), the synthetic literal is replaced ' ...
                 'with testCase.Instance.<propName> so the smoke ' ...
                 'operates against the live container.  Candidate 2, ' ...
                 'live-state-aware VALUE synthesis: symmetric to ' ...
                 'Phase 15 candidate 1 but draws a sample VALUE from ' ...
                 'the populated property via firstValueOr() when the ' ...
                 'arg is value-shaped and the property is table / ' ...
                 'struct / cell.  Candidate 3, drop the stateful ' ...
                 'try/assumeFail wrap when every arg resolved cleanly ' ...
                 'AND the model has a state-init prelude AND the ' ...
                 'project supplies a primary fixture: smokes that ' ...
                 'were silently demoted to Incomplete in Phase 11 now ' ...
                 'report Pass when the prelude verifiably populated ' ...
                 'state.  Candidate 4, mustBeMember validator pulls: ' ...
                 'when an arguments block declares mustBeMember(arg, ' ...
                 'list) with a literal list, the smoke uses the first ' ...
                 'allowed value as the literal so validation passes ' ...
                 'on the first try.  Candidate 5, doc-example parser ' ...
                 'hardening: multi-line Example: blocks with internal ' ...
                 'blank lines are now extracted in full, and examples ' ...
                 'with assignments are routed through an isolated ' ...
                 'eval frame so workspace state cannot leak between ' ...
                 'invocations.  All five mechanisms are generic across ' ...
                 'MATLAB projects -- no project-specific knowledge.']);
            backend.addHeading(2, 'C.4 known_real_signal.txt Opt-Out');
            backend.addParagraph(sprintf( ...
                ['Generated tests that fail because of a real bug in the ' ...
                 'project add noise to the report and obscure regressions in ' ...
                 'the autogen tool itself.  matlabunittest exposes a per-' ...
                 'target opt-out: list the test in <projectFolder>/_autotest/' ...
                 'known_real_signal.txt with a one-line reason and the ' ...
                 'autogen emits a testSkipped_<name> Incomplete carrying the ' ...
                 'user''s reason text instead of the failing test.  This file ' ...
                 'is preserved across regenerations.  This project has %d ' ...
                 'entries in this manifest.'], ...
                numel(ctx.Data.KnownRealSignal)));
            backend.addHeading(2, 'C.5 Native Report Generator');
            backend.addParagraph( ...
                ['This report itself was produced by the native MATLAB ' ...
                 'generator (autotest.report.ReportBuilder) introduced in ' ...
                 'Phase 15 and extended in Phase 16.  Phase 16 added a ' ...
                 'page-number footer ("Page X of Y" centred at 9pt ' ...
                 'Calibri), a two-section sectPr so the cover page is ' ...
                 'on its own section with no footer crowd, and a ' ...
                 'tamper-evident audit trail (Appendix E) backed by a ' ...
                 'sha256 sidecar.  The generator selects between two ' ...
                 'backends: a primary path that uses MATLAB Report ' ...
                 'Generator''s mlreportgen.dom API, and a fallback ' ...
                 'hand-rolled OOXML emitter that writes a valid Word ' ...
                 '2007+ .docx using only built-in MATLAB primitives.  ' ...
                 'The active backend for this run is logged in ' ...
                 '_autotest/reports/report_backend.log.']);
        end

        % ====================================================== Appendix E
        function appendixE(backend, ctx)
            %APPENDIXE  Phase 16 (Part B item 7) -- Audit Trail.
            %
            %   Lists the signoff-grade evidence trail an Authority's
            %   reviewer can stamp:
            %     - matlabunittest commit hash (system git rev-parse)
            %     - test-cycle timestamp
            %     - Phase 16 verification status and Pass count
            %     - chosen backend + PDF tier
            %     - file checksum reference (computed post-write,
            %       published in <basename>_audit.txt next to the
            %       deliverables -- sha256 of a file cannot be embedded
            %       INSIDE itself, so the sidecar carries the actual
            %       cryptographic seal).
            audit = struct();
            if isfield(ctx, 'Audit') && ~isempty(ctx.Audit)
                audit = ctx.Audit;
            end
            backend.addHeading(1, 'Appendix E -- Audit Trail');
            backend.addParagraph( ...
                ['This appendix carries the signoff-grade evidence trail ' ...
                 'for the test cycle.  An Authority''s reviewer can ' ...
                 'cross-reference the commit hash against the upstream ' ...
                 'matlabunittest repository, verify the test-cycle ' ...
                 'timestamp against the JUnit results.xml, confirm the ' ...
                 'backend and PDF tier match the report_backend.log, ' ...
                 'and validate the file checksums (sha256) against the ' ...
                 'companion audit sidecar published next to the report ' ...
                 'deliverables.']);
            backend.addHeading(2, 'E.1 Provenance');
            commit = autotest.report.SectionBuilder.fieldOrDefault(audit, 'CommitHash', '(unavailable)');
            cleanFlag = autotest.report.SectionBuilder.fieldOrDefault(audit, 'TreeClean', '(unavailable)');
            cycle = autotest.report.SectionBuilder.fieldOrDefault(audit, 'CycleTimestamp', '(unavailable)');
            buildAt = autotest.report.SectionBuilder.fieldOrDefault(audit, 'BuiltAt', '(unavailable)');
            backend.addTable({'Field', 'Value'}, { ...
                'matlabunittest commit hash', commit; ...
                'matlabunittest tree clean',  cleanFlag; ...
                'Test-cycle timestamp',        cycle; ...
                'Report build time',           buildAt}, ...
                [3500, 5860]);
            backend.addHeading(2, 'E.2 Verification Outcome');
            passCount = autotest.report.SectionBuilder.fieldOrDefault(audit, 'PassCount', '');
            failCount = autotest.report.SectionBuilder.fieldOrDefault(audit, 'FailCount', '');
            incCount  = autotest.report.SectionBuilder.fieldOrDefault(audit, 'IncCount',  '');
            phaseStat = autotest.report.SectionBuilder.fieldOrDefault(audit, 'PhaseStatus', '');
            backend.addTable({'Field', 'Value'}, { ...
                'Verification status',          phaseStat; ...
                'Generated tests passed',       passCount; ...
                'Generated tests failed',       failCount; ...
                'Generated tests incomplete',   incCount}, ...
                [3500, 5860]);
            backend.addHeading(2, 'E.3 Backend and PDF Tier');
            backend.addTable({'Field', 'Value'}, { ...
                'Selected report backend', autotest.report.SectionBuilder.fieldOrDefault(audit, 'BackendDisplay', ''); ...
                'PDF tier (chosen)',       autotest.report.SectionBuilder.fieldOrDefault(audit, 'PdfTier', '')}, ...
                [3500, 5860]);
            backend.addHeading(2, 'E.4 File Checksums');
            backend.addParagraph( ...
                ['The companion audit sidecar lists the post-write ' ...
                 'sha256 of every deliverable in this cycle.  ' ...
                 'Sidecar location:']);
            sidecar = autotest.report.SectionBuilder.fieldOrDefault(audit, 'SidecarPath', '<OutputDir>/<basename>_audit.txt');
            backend.addParagraph(sidecar);
            backend.addParagraph( ...
                ['To verify a deliverable: compute sha256 of the file ' ...
                 'and compare against the sidecar entry for that path.  ' ...
                 'Mismatches indicate post-cycle modification and ' ...
                 'invalidate the audit trail.']);
            % v1.3 Part B item 2: self-attesting content checksum.  The
            % ReportBuilder.embedSelfChecksum post-process step substitutes
            % the sentinel below with the sha256 of `word/document.xml` as
            % the autogen wrote it (with the sentinel still in place).
            % The hash is over the document CONTENT, not the .docx zip
            % wrapper, so verification is robust to non-deterministic
            % zip metadata (timestamps, part order).
            backend.addHeading(2, 'E.5 Self-attesting Content Checksum');
            backend.addParagraph( ...
                ['This .docx carries the sha256 of its own ' ...
                 'word/document.xml inline.  The hex below is the ' ...
                 'checksum of that part as the autogen wrote it ' ...
                 '(before the sentinel was rewritten with the hex), ' ...
                 'so the inline value is verifiable.  The same value ' ...
                 'also appears in the audit sidecar for cross-reference.']);
            backend.addParagraph( ...
                'word/document.xml sha256 (sentinel marker, replaced post-build):');
            backend.addParagraph('__DOCX_SHA256_SLOT__');
            backend.addParagraph( ...
                ['Verification recipe: (1) unzip this .docx, (2) read ' ...
                 'word/document.xml, (3) extract the 64-char hex above, ' ...
                 '(4) substitute the hex back to the literal string ' ...
                 '"__DOCX_SHA256_SLOT__" inside word/document.xml, ' ...
                 '(5) sha256 the resulting file.  The result must ' ...
                 'equal the extracted hex.  This proves the hex is a ' ...
                 'genuine content hash, not a planted value.']);
        end

        function v = fieldOrDefault(s, name, default)
            if isstruct(s) && isfield(s, name) && ~isempty(s.(name))
                val = s.(name);
                if ischar(val), v = val;
                elseif isstring(val), v = char(val);
                elseif isnumeric(val) && isscalar(val), v = num2str(val);
                else, v = default;
                end
            else
                v = default;
            end
        end

        % ====================================================== Appendix D
        function appendixD(backend, ~)
            backend.addHeading(1, 'Appendix D -- Glossary');
            terms = { ...
                'Incomplete', ...
                ['matlab.unittest.TestResult disposition for a test that did ' ...
                 'not run to completion because an assumption was not met.  ' ...
                 'Used by matlabunittest to flag opaque-typed inputs, ' ...
                 'project bugs on the accepted-debt list, and user-stub ' ...
                 'placeholders awaiting hand-written assertions.'];
                'JUnit XML', ...
                ['results.xml in JUnit format, written by matlabunittest ' ...
                 'on every run.  Compatible with Jenkins, GitHub Actions, ' ...
                 'and most CI dashboards.  Located at _autotest/reports/' ...
                 'results.xml.']; ...
                'TAP', ...
                ['Test Anything Protocol.  results.tap is a parallel output ' ...
                 'format for shell-friendly CI integrations.  Located at ' ...
                 '_autotest/reports/results.tap.']; ...
                'Smoke test', ...
                ['A best-effort call into the method with a synthesised ' ...
                 'input of the expected shape.  Asserts only that no ' ...
                 'unhandled exception escaped.']; ...
                'Edge test', ...
                ['A targeted call against degenerate inputs (empty, NaN, ' ...
                 'Inf, zero, neg, large, small) that real callers ' ...
                 'occasionally produce.']; ...
                'Randomized property test', ...
                ['A 25-trial randomized invocation of the method against ' ...
                 'rand()-generated input shapes.  Verifies the public ' ...
                 'surface does not throw against a broad sweep of typed ' ...
                 'inputs.']; ...
                'FixtureProvider', ...
                ['+autotest/FixtureProvider.m.  Maps argument names and ' ...
                 'types to concrete literal expressions, including ' ...
                 'project-supplied fixtures.']; ...
                'StateInitializer', ...
                ['+autotest/StateInitializer.m.  Detects zero-arg and ' ...
                 'multi-arg state-init methods on stateful classes and ' ...
                 'wires them into the TestMethodSetup prelude so methods ' ...
                 'see populated instance state.']; ...
                'known_real_signal.txt', ...
                ['_autotest/known_real_signal.txt.  Per-target manifest of ' ...
                 'tests that fail because of an accepted real bug in the ' ...
                 'project, kept across regenerations.']; ...
                'user-stub', ...
                ['Hand-edit-friendly userTest_<name> placeholder under ' ...
                 '_autotest/user_tests/u<Class>.m, seeded once per public ' ...
                 'function / method / property / callback and never ' ...
                 'overwritten on regeneration.  Reports as Incomplete ' ...
                 'until filled in.']; ...
                };
            rows = cell(size(terms,1)/2, 2);
            row = 0;
            for i = 1:2:numel(terms)
                row = row + 1;
                rows{row,1} = terms{i};
                rows{row,2} = terms{i+1};
            end
            backend.addTable({'Term','Definition'}, rows, [2400, 6960]);
        end

        % ====================================================== v1.4 chart helpers

        function pngPath = renderPieChart(passed, failed, incomplete)
            %RENDERPIECHART  v1.4 (.docx) + v1.6 (300 DPI + value labels).
            %   Returns the absolute path to a tempfile PNG rendered at
            %   300 DPI (was 150) with bold percent labels burned onto
            %   each slice and a legend pinned alongside.  Colours follow
            %   the locked v1.4 palette: muted gold (passed), deep red
            %   (failed), slate (incomplete).  '' on failure.
            pngPath = '';
            try
                vals = double([passed, failed, incomplete]);
                names = {'Passed','Failed','Incomplete'};
                colours = [ ...
                    0.706 0.325 0.035; ...   % muted gold #B45309
                    0.600 0.106 0.106; ...   % deep red   #991B1B
                    0.294 0.333 0.388 ];     % slate      #4B5563
                charcoal = [0.122 0.161 0.216];
                fig = figure('Visible','off','Color','w', ...
                    'Position',[0 0 1200 700], 'PaperPositionMode','auto');
                cleanup = onCleanup(@() close(fig)); %#ok<NASGU>
                ax = axes(fig, 'Units','normalized','Position',[0.04 0.06 0.5 0.86]); %#ok<LAXES>
                total = sum(vals);
                if total <= 0
                    h = pie(ax, 1, {'(no tests)'});
                    if numel(h) >= 1 && isgraphics(h(1), 'patch')
                        h(1).FaceColor = colours(3,:);
                    end
                else
                    nz = vals > 0;
                    nzIdx = find(nz);
                    pct = 100 * vals(nz) / total;
                    labels = cell(1, numel(nzIdx));
                    for k = 1:numel(nzIdx)
                        labels{k} = sprintf('%.0f%%', pct(k));
                    end
                    h = pie(ax, vals(nz), labels);
                    nzColours = colours(nz, :);
                    pIdx = 1; tIdx = 1;
                    for k = 1:numel(h)
                        if isgraphics(h(k), 'patch') && pIdx <= size(nzColours,1)
                            h(k).FaceColor = nzColours(pIdx, :);
                            h(k).EdgeColor = 'w';
                            h(k).LineWidth = 2.0;
                            pIdx = pIdx + 1;
                        elseif isgraphics(h(k), 'text') && tIdx <= numel(pct)
                            h(k).FontSize = 14;
                            h(k).FontWeight = 'bold';
                            h(k).Color = 'w';
                            % Hide near-0% slice labels so they don't crowd.
                            if pct(tIdx) < 5, h(k).String = ''; end
                            tIdx = tIdx + 1;
                        end
                    end
                end
                title(ax, 'Test Results Breakdown', ...
                    'Color', charcoal, 'FontSize', 16, 'FontWeight','bold');
                % Legend axes -- separate panel on the right with coloured
                % swatches + counts so the report carries both percent
                % (on-pie) and raw count (in legend).
                axL = axes(fig, 'Units','normalized','Position',[0.6 0.1 0.36 0.8], ...
                    'XLim',[0 1],'YLim',[0 1],'Visible','off'); %#ok<LAXES>
                y0 = 0.85; dy = 0.16;
                for k = 1:3
                    yy = y0 - (k-1)*dy;
                    rectangle(axL, 'Position',[0.05 yy 0.10 0.07], ...
                        'FaceColor', colours(k,:), 'EdgeColor','none');
                    text(axL, 0.20, yy + 0.035, ...
                        sprintf('%s (%d)', names{k}, vals(k)), ...
                        'Color', charcoal, 'FontSize', 14, 'FontWeight','normal');
                end
                pngPath = [tempname() '.png'];
                print(fig, pngPath, '-dpng', '-r300');
            catch ME
                warning('autotest:report:pieRender', ...
                    'renderPieChart failed: %s', ME.message);
                pngPath = '';
            end
        end

        function pngPath = renderBarChart(perSource)
            %RENDERBARCHART  v1.4 (.docx) + v1.6 (300 DPI + value labels).
            %   Pass-rate per source as a horizontal bar chart at 300 DPI
            %   with right-of-bar percent labels in charcoal and a
            %   muted-gold bar fill matching the locked palette.
            pngPath = '';
            try
                if isempty(perSource), return; end
                n = numel(perSource);
                rates = zeros(1, n);
                labels = cell(1, n);
                counts = strings(1, n);
                for i = 1:n
                    p = perSource(i);
                    labels{i} = char(p.File);
                    if p.Total > 0
                        rates(i) = 100 * p.Passed / p.Total;
                    end
                    counts(i) = sprintf('%d / %d', p.Passed, p.Total);
                end
                gold     = [0.706 0.325 0.035];
                charcoal = [0.122 0.161 0.216];
                slate    = [0.294 0.333 0.388];
                figH = max(420, 48 * n + 160);
                fig = figure('Visible','off','Color','w', ...
                    'Position',[0 0 1400 figH], 'PaperPositionMode','auto');
                cleanup = onCleanup(@() close(fig)); %#ok<NASGU>
                ax = axes(fig, 'Units','normalized', ...
                    'Position',[0.30 0.10 0.55 0.82]); %#ok<LAXES>
                barh(ax, rates, 'FaceColor', gold, 'EdgeColor', 'none', ...
                    'BarWidth', 0.7);
                set(ax, 'YTick', 1:n, 'YTickLabel', labels, 'YDir', 'reverse', ...
                    'Color', 'w', 'XColor', charcoal, ...
                    'YColor', charcoal, 'FontSize', 11, ...
                    'TickLength', [0 0], 'Box', 'off');
                xlim(ax, [0 105]);
                xlabel(ax, 'Pass rate (%)', 'Color', charcoal, 'FontSize', 12);
                title(ax, 'Pass Rate per Source File', ...
                    'Color', charcoal, 'FontSize', 16, 'FontWeight','bold');
                grid(ax, 'on');
                ax.GridColor = [0.82 0.82 0.82];
                ax.XGrid = 'on'; ax.YGrid = 'off';
                % Right-of-bar value labels (percent + raw count).
                for i = 1:n
                    text(ax, rates(i) + 1.5, i, ...
                        sprintf('%.1f%%   %s', rates(i), counts(i)), ...
                        'Color', charcoal, 'FontSize', 11, ...
                        'VerticalAlignment','middle', ...
                        'HorizontalAlignment','left');
                end
                % Caption under axes -- explicit "muted gold = passed"
                % gloss so a reader who skims the legend-less bar still
                % knows what they're looking at.
                annotation(fig, 'textbox', [0.30 0.02 0.55 0.05], ...
                    'String', sprintf( ...
                        'Bar = passed / total tests per source.  N = %d sources.', n), ...
                    'Color', slate, 'FontSize', 10, ...
                    'EdgeColor', 'none', 'HorizontalAlignment','left');
                pngPath = [tempname() '.png'];
                print(fig, pngPath, '-dpng', '-r300');
            catch ME
                warning('autotest:report:barRender', ...
                    'renderBarChart failed: %s', ME.message);
                pngPath = '';
            end
        end
    end
end
