classdef OoxmlBackend < handle
    %OOXMLBACKEND  Phase 15 -- hand-rolled OOXML .docx emitter.
    %
    %   Used as the fallback when MATLAB Report Generator is not
    %   licensed.  Emits a valid Word 2007+ .docx by composing each
    %   constituent XML file as a char vector, staging them in a
    %   tempdir, and packing with builtin zip().
    %
    %   Public API mirrors RptgenBackend so SectionBuilder / CoverPage
    %   can render to either backend without conditionals.
    %
    %   Fidelity caveats vs. RptgenBackend:
    %     - Footer page numbers are emitted via a one-line w:fldSimple
    %       in a default footer; styling is minimal.
    %     - No table-of-figures, no captions, no styles beyond
    %       Heading 1/2/3 and Normal.
    %     - Tables use a uniform 1/2 pt grey border; no cell merging.
    %   These limits are intentional -- the goal is structural parity
    %   with the reference, not pixel-perfect typography.

    properties (SetAccess = immutable)
        OutputPath     (1,:) char
        Classification (1,:) char = 'UNCLASSIFIED'   % v1.4: CAPCO banner level
        % v1.6 (DoDI 5200.48): parenthetical portion-marking prefix.  '(U)'
        % for UNCLASSIFIED docs, '(C)/(S)/(TS)/(U//FOUO)' for higher tiers.
        % Each body paragraph and heading is prefixed with this code when
        % EmitPortionMarks is true.
        PortionCode    (1,:) char = '(U)'
    end

    properties (SetAccess = private)
        BodyParts          string  = string.empty   % accumulated <w:p> / <w:tbl> XML strings
        ContentWidth       double  = 9360
        ImageEntries       struct  = struct('SrcPath',{},'PartName',{},'RelId',{},'WidthEmu',{},'HeightEmu',{})
        EmitPortionMarks   (1,1) logical = true     % v1.6 -- opt-out switch
        TableRowToggle     (1,1) double = 0         % v1.6 -- alternating-row shading state
    end

    methods
        function obj = OoxmlBackend(outputPath, classification)
            arguments
                outputPath     (1,:) char
                classification (1,:) char = 'UNCLASSIFIED'
            end
            obj.OutputPath = outputPath;
            obj.ContentWidth = autotest.report.Style.ContentWidth;
            obj.Classification = classification;
            obj.PortionCode = autotest.report.Style.portionCode(classification);
        end

        % ===================================================== Cover page

        function addCoverPage(obj, fields, distHeader, distBody)
            %ADDCOVERPAGE  Title block + metadata table + bordered dist box.
            %   FIELDS is a cell array of {key, value} pairs for the
            %   metadata table.  DISTHEADER / DISTBODY are the strings
            %   inside the bordered Distribution Statement D box.
            %
            %   Phase 16 (Part B item 2): the cover ends with a SECTION
            %   break, not a plain page break.  The cover-page section
            %   carries titlePg=true; v1.4 (B.5) added header+footer
            %   references so the classification banner appears on the
            %   cover page too.
            %
            %   v1.4 (B.3): refreshed typography.  The title is now
            %   Style.TitleFontSize (48pt) bold charcoal; the subtitle
            %   is Style.SubtitleFontSize (18pt) italic slate; a 1pt
            %   accent-coloured rule sits between the metadata table
            %   and the Distribution Statement D box when
            %   fields.AccentRule is true.
            wantRule = isfield(fields, 'AccentRule') && fields.AccentRule;
            obj.addBlankParagraph(900);
            obj.BodyParts(end+1) = obj.titleParagraph(fields.Title, ...
                autotest.report.Style.TitleFontSize, true, 'center', false, ...
                autotest.report.Style.PrimaryText);
            obj.BodyParts(end+1) = obj.titleParagraph(fields.Subtitle, ...
                autotest.report.Style.SubtitleFontSize, false, 'center', true, ...
                autotest.report.Style.SecondaryText);
            obj.addBlankParagraph(300);
            % Metadata table (centered, 2 cols).
            obj.BodyParts(end+1) = obj.kvTableXml(fields.Metadata, [3000, 4500]);
            if wantRule
                obj.addAccentRule();
            else
                obj.addBlankParagraph(600);
            end
            % Distribution Statement D box.
            obj.BodyParts(end+1) = obj.distBoxXml(distHeader, distBody);
            % Cover-only section break (titlePg=true; v1.4 also carries
            % header+footer refs so the classification banner shows).
            obj.BodyParts(end+1) = obj.coverSectionBreak();
        end

        % ===================================================== Headings + body

        function addHeading(obj, level, text)
            %ADDHEADING  Level 1, 2, or 3.
            %   v1.6: prepend the DoDI 5200.48 portion-marking code; emit a
            %   60% muted-gold accent rule directly under each level-1
            %   heading for professional polish.
            arguments
                obj
                level   (1,1) double {mustBeMember(level, [1 2 3])}
                text    (1,:) char
            end
            styleId = sprintf('Heading%d', level);
            sizeMap = [autotest.report.Style.H1FontSize, ...
                       autotest.report.Style.H2FontSize, ...
                       autotest.report.Style.H3FontSize];
            marked = obj.applyPortionPrefix(text);
            obj.BodyParts(end+1) = obj.paragraphXml(marked, ...
                'Bold', true, 'Size', sizeMap(level), ...
                'Style', styleId, 'OutlineLevel', level - 1);
            if level == 1
                obj.BodyParts(end+1) = obj.headingAccentRule();
            end
        end

        function addParagraph(obj, text)
            arguments
                obj
                text (1,:) char
            end
            marked = obj.applyPortionPrefix(text);
            obj.BodyParts(end+1) = obj.paragraphXml(marked, ...
                'AfterSpacing', 160);
        end

        function addPageBreak(obj)
            obj.BodyParts(end+1) = string( ...
                "<w:p><w:r><w:br w:type=""page""/></w:r></w:p>");
        end

        function addBlankParagraph(obj, beforeSpacing)
            if nargin < 2, beforeSpacing = 0; end
            extra = '';
            if beforeSpacing > 0
                extra = sprintf('<w:spacing w:before="%d"/>', beforeSpacing);
            end
            obj.BodyParts(end+1) = string( ...
                ['<w:p><w:pPr>' extra '</w:pPr><w:r><w:t/></w:r></w:p>']);
        end

        function addAccentRule(obj)
            %ADDACCENTRULE  v1.4 -- thin accent-coloured horizontal rule.
            %   Used between cover-page metadata table and Distribution
            %   Statement D box.  Renders as a 1pt rule in Style.Accent
            %   (muted gold) by abusing the bottom border on an empty
            %   paragraph -- the simplest 1-line OOXML idiom.
            obj.BodyParts(end+1) = string([ ...
                '<w:p><w:pPr>' ...
                '<w:pBdr><w:bottom w:val="single" w:sz="' ...
                num2str(autotest.report.Style.AccentRuleSize) ...
                '" w:space="1" w:color="' ...
                autotest.report.Style.Accent ...
                '"/></w:pBdr>' ...
                '<w:spacing w:before="120" w:after="240"/>' ...
                '</w:pPr></w:p>']);
        end

        function addImage(obj, pngPath, widthDxa, heightDxa)
            %ADDIMAGE  v1.4 -- embed a PNG inline at the requested DXA size.
            %
            %   Charts (pie, bar) are rendered to a temp PNG by
            %   SectionBuilder via figure -> pie/barh -> print('-dpng',
            %   '-r150') and handed here.  The PNG is registered in the
            %   media manifest, a unique image relationship ID is
            %   minted, and a <w:drawing> paragraph is appended to the
            %   body.  At close() time the staged PNG is copied into
            %   word/media/ inside the .docx zip.
            arguments
                obj
                pngPath   (1,:) char
                widthDxa  (1,1) double
                heightDxa (1,1) double
            end
            if ~isfile(pngPath)
                warning('autotest:report:Image', ...
                    'addImage skipped -- PNG not found: %s', pngPath);
                return;
            end
            n = numel(obj.ImageEntries) + 1;
            partName = sprintf('image%d.png', n);
            relId    = sprintf('rIdImg%d', n);
            % EMU = English Metric Unit; 914400 EMU == 1 inch == 1440 DXA.
            % So 1 DXA = 635 EMU.
            widthEmu  = round(widthDxa  * 635);
            heightEmu = round(heightDxa * 635);
            obj.ImageEntries(end+1) = struct( ...
                'SrcPath',   pngPath, ...
                'PartName',  partName, ...
                'RelId',     relId, ...
                'WidthEmu',  widthEmu, ...
                'HeightEmu', heightEmu);
            obj.BodyParts(end+1) = string( ...
                autotest.report.backends.OoxmlBackend.drawingParagraphXml( ...
                    relId, n, widthEmu, heightEmu));
        end

        function addStatusBadge(obj, status, inlineLabel)
            %ADDSTATUSBADGE  v1.6 -- colored pill badge for a status.
            %   Rendered as a 1-cell shaded "table" inline next to its
            %   label (e.g. Status: [Pass]).  Word's inline-shape support
            %   is weaker than HTML's; a single-cell table is the most
            %   widely-rendered idiom.
            arguments
                obj
                status      (1,:) char
                inlineLabel (1,:) char = ''
            end
            [fill, text, label] = autotest.report.Style.statusBadge(status);
            labelXml = '';
            if ~isempty(inlineLabel)
                labelXml = ['<w:r><w:t xml:space="preserve">' ...
                    autotest.report.backends.OoxmlBackend.xmlEsc( ...
                        [obj.applyPortionPrefix(inlineLabel) ' ']) ...
                    '</w:t></w:r>'];
            else
                % Stand-alone badge: still prefix the row's portion mark
                % so the marking is consistent across paragraphs.
                labelXml = ['<w:r><w:t xml:space="preserve">' ...
                    autotest.report.backends.OoxmlBackend.xmlEsc( ...
                        [obj.PortionCode ' ']) ...
                    '</w:t></w:r>'];
            end
            badgeRun = sprintf( ...
                ['<w:r><w:rPr><w:b/>' ...
                 '<w:color w:val="%s"/>' ...
                 '<w:shd w:val="clear" w:color="auto" w:fill="%s"/>' ...
                 '<w:rFonts w:ascii="Calibri" w:hAnsi="Calibri"/>' ...
                 '<w:sz w:val="20"/><w:szCs w:val="20"/>' ...
                 '</w:rPr>' ...
                 '<w:t xml:space="preserve">  %s  </w:t></w:r>'], ...
                 text, fill, ...
                 autotest.report.backends.OoxmlBackend.xmlEsc(upper(label)));
            obj.BodyParts(end+1) = string([ ...
                '<w:p><w:pPr><w:spacing w:after="80"/></w:pPr>' ...
                labelXml badgeRun '</w:p>']);
        end

        function addCalloutBox(obj, value, caption)
            %ADDCALLOUTBOX  v1.6 -- executive-summary callout box.
            %   Big accent-colored number + small caption underneath, set
            %   inside a left-bordered light-grey single-cell table.
            arguments
                obj
                value   (1,:) char
                caption (1,:) char
            end
            cw = 2880;   % ~2 inches; three fit across content width
            fill = autotest.report.Style.CalloutFill;
            accent = autotest.report.Style.Accent;
            valueXml = sprintf([ ...
                '<w:p><w:pPr><w:spacing w:before="60" w:after="20"/>' ...
                '<w:jc w:val="left"/></w:pPr>' ...
                '<w:r><w:rPr><w:b/>' ...
                '<w:rFonts w:ascii="Calibri" w:hAnsi="Calibri"/>' ...
                '<w:sz w:val="48"/><w:szCs w:val="48"/>' ...
                '<w:color w:val="%s"/></w:rPr>' ...
                '<w:t xml:space="preserve">%s</w:t></w:r></w:p>'], ...
                accent, ...
                autotest.report.backends.OoxmlBackend.xmlEsc(value));
            captionXml = sprintf([ ...
                '<w:p><w:pPr><w:spacing w:before="0" w:after="80"/></w:pPr>' ...
                '<w:r><w:rPr>' ...
                '<w:rFonts w:ascii="Calibri" w:hAnsi="Calibri"/>' ...
                '<w:sz w:val="18"/><w:szCs w:val="18"/>' ...
                '<w:color w:val="%s"/></w:rPr>' ...
                '<w:t xml:space="preserve">%s</w:t></w:r></w:p>'], ...
                autotest.report.Style.SecondaryText, ...
                autotest.report.backends.OoxmlBackend.xmlEsc(upper(caption)));
            % Single-cell table with thick left border in accent + light
            % grey fill.  Right margin breathes; cell wraps under the
            % callout content.
            borderXml = [ ...
                '<w:tcBorders>' ...
                '<w:left w:val="single" w:sz="24" w:color="' accent '"/>' ...
                '<w:top w:val="single" w:sz="4" w:color="E5E7EB"/>' ...
                '<w:bottom w:val="single" w:sz="4" w:color="E5E7EB"/>' ...
                '<w:right w:val="single" w:sz="4" w:color="E5E7EB"/>' ...
                '</w:tcBorders>'];
            obj.BodyParts(end+1) = string([ ...
                '<w:tbl>' ...
                '<w:tblPr>' ...
                sprintf('<w:tblW w:w="%d" w:type="dxa"/>', cw) ...
                '<w:tblInd w:w="0" w:type="dxa"/>' ...
                '<w:tblLayout w:type="fixed"/>' ...
                '</w:tblPr>' ...
                sprintf('<w:tblGrid><w:gridCol w:w="%d"/></w:tblGrid>', cw) ...
                '<w:tr><w:tc><w:tcPr>' ...
                sprintf('<w:tcW w:w="%d" w:type="dxa"/>', cw) ...
                sprintf('<w:shd w:val="clear" w:color="auto" w:fill="%s"/>', fill) ...
                borderXml ...
                '<w:tcMar><w:top w:w="120" w:type="dxa"/>' ...
                '<w:left w:w="180" w:type="dxa"/>' ...
                '<w:bottom w:w="120" w:type="dxa"/>' ...
                '<w:right w:w="180" w:type="dxa"/></w:tcMar>' ...
                '</w:tcPr>' ...
                valueXml captionXml ...
                '</w:tc></w:tr></w:tbl><w:p/>']);
        end

        function addFailureCard(obj, info)
            %ADDFAILURECARD  v1.6 -- single failure entry in the Failed Tests section.
            arguments
                obj
                info struct
            end
            cls   = autotest.report.SectionBuilder.fieldOrDefault(info, ...
                'Class', '(unknown class)');
            mname = autotest.report.SectionBuilder.fieldOrDefault(info, ...
                'Method', '(unknown method)');
            src   = autotest.report.SectionBuilder.fieldOrDefault(info, ...
                'Source', '');
            ident = autotest.report.SectionBuilder.fieldOrDefault(info, ...
                'Identifier', '');
            msg   = autotest.report.SectionBuilder.fieldOrDefault(info, ...
                'Message', '(no diagnostic captured)');
            expl  = autotest.report.SectionBuilder.fieldOrDefault(info, ...
                'Explanation', '');
            % Header line.
            header = sprintf('%s.%s', cls, mname);
            if ~isempty(src)
                header = sprintf('%s -- %s', header, src);
            end
            obj.BodyParts(end+1) = obj.paragraphXml( ...
                obj.applyPortionPrefix(header), ...
                'Bold', true, 'Size', 22, 'AfterSpacing', 60);
            % Identifier (monospace).
            if ~isempty(ident)
                obj.BodyParts(end+1) = string( ...
                    autotest.report.backends.OoxmlBackend.codeLineXml( ...
                        [obj.PortionCode ' ' ident]));
            end
            % Headline message (body text).
            obj.BodyParts(end+1) = obj.paragraphXml( ...
                obj.applyPortionPrefix(msg), 'AfterSpacing', 60);
            % Stack (monospace).
            if isfield(info, 'Stack') && ~isempty(info.Stack)
                for k = 1:numel(info.Stack)
                    obj.BodyParts(end+1) = string( ...
                        autotest.report.backends.OoxmlBackend.codeLineXml( ...
                            ['  ' info.Stack{k}]));
                end
            end
            % Plain-English explanation.
            if ~isempty(expl)
                obj.BodyParts(end+1) = obj.paragraphXml( ...
                    obj.applyPortionPrefix( ...
                        ['Plain-English explanation. ' expl]), ...
                    'Italic', true, 'AfterSpacing', 200);
            else
                obj.BodyParts(end+1) = obj.paragraphXml( ...
                    obj.applyPortionPrefix( ...
                        'Cause not classified -- investigate manually.'), ...
                    'Italic', true, 'AfterSpacing', 200);
            end
        end

        function addCodeBlock(obj, text)
            %ADDCODEBLOCK  v1.4 -- monospace + light-grey-fill paragraph.
            %   Used by Appendix B for diagnostic stack excerpts so they
            %   read like real code, not like memo prose.  Preserves
            %   newlines: each line becomes its own <w:p>, all sharing
            %   the same paragraph shading so consecutive lines render
            %   as one continuous block.
            arguments
                obj
                text (1,:) char
            end
            % Normalise CRLF/CR to LF, then split.
            t = strrep(text, sprintf('\r\n'), char(10));
            t = strrep(t, char(13), char(10));
            lines = strsplit(t, char(10), 'CollapseDelimiters', false);
            for i = 1:numel(lines)
                obj.BodyParts(end+1) = string( ...
                    autotest.report.backends.OoxmlBackend.codeLineXml(lines{i}));
            end
        end

        % ===================================================== TOC

        function addTOC(obj, headingText)
            arguments
                obj
                headingText (1,:) char = 'Table of Contents'
            end
            obj.BodyParts(end+1) = obj.titleParagraph(headingText, 36, true, 'center');
            % w:fldChar begin -> instrText -> fldChar end pattern.
            tocXml = string([ ...
                '<w:p><w:pPr><w:pStyle w:val="TOC"/></w:pPr>' ...
                '<w:r><w:fldChar w:fldCharType="begin" w:dirty="true"/></w:r>' ...
                '<w:r><w:instrText xml:space="preserve">TOC \o "1-3" \h \z \u</w:instrText></w:r>' ...
                '<w:r><w:fldChar w:fldCharType="separate"/></w:r>' ...
                '<w:r><w:t>(Right-click the TOC and choose "Update Field" if Word does not auto-populate it.)</w:t></w:r>' ...
                '<w:r><w:fldChar w:fldCharType="end"/></w:r>' ...
                '</w:p>']);
            obj.BodyParts(end+1) = tocXml;
            obj.addPageBreak();
        end

        % ===================================================== Tables

        function addTable(obj, headers, rows, columnWidths)
            %ADDTABLE  Headers across the top, columnWidths in DXA.
            arguments
                obj
                headers       cell
                rows          cell
                columnWidths  double
            end
            obj.BodyParts(end+1) = obj.tableXml(headers, rows, columnWidths, ...
                autotest.report.Style.HeaderShading, '');
        end

        function addMetaTable(obj, kvRows)
            %ADDMETATABLE  Two-column key/value table; centered.
            cols = [3000, 4500];
            obj.BodyParts(end+1) = obj.kvTableXml(kvRows, cols);
        end

        % ===================================================== Output

        function close(obj)
            %CLOSE  Stage XML files and zip into the .docx.
            tmpStage = tempname();
            mkdir(tmpStage);
            try
                mkdir(fullfile(tmpStage, '_rels'));
                mkdir(fullfile(tmpStage, 'word'));
                mkdir(fullfile(tmpStage, 'word', '_rels'));

                obj.writeFile(fullfile(tmpStage, '[Content_Types].xml'), obj.contentTypesXml());
                obj.writeFile(fullfile(tmpStage, '_rels', '.rels'),       obj.rootRelsXml());
                obj.writeFile(fullfile(tmpStage, 'word', 'document.xml'),  obj.documentXml());
                obj.writeFile(fullfile(tmpStage, 'word', '_rels', 'document.xml.rels'), obj.docRelsXml());
                obj.writeFile(fullfile(tmpStage, 'word', 'styles.xml'),    obj.stylesXml());
                obj.writeFile(fullfile(tmpStage, 'word', 'settings.xml'),  obj.settingsXml());
                % Phase 16 (Part B item 1): page-number footer.
                obj.writeFile(fullfile(tmpStage, 'word', 'footer1.xml'),   obj.footerXml());
                obj.writeFile(fullfile(tmpStage, 'word', '_rels', 'footer1.xml.rels'), obj.footerRelsXml());
                % v1.4 (B.5): top-of-page CAPCO classification banner.
                obj.writeFile(fullfile(tmpStage, 'word', 'header1.xml'),   obj.headerXml());
                obj.writeFile(fullfile(tmpStage, 'word', '_rels', 'header1.xml.rels'), obj.headerRelsXml());
                % v1.4 (B.1/B.2): copy embedded PNGs into word/media/.
                if ~isempty(obj.ImageEntries)
                    mkdir(fullfile(tmpStage, 'word', 'media'));
                    for i = 1:numel(obj.ImageEntries)
                        e = obj.ImageEntries(i);
                        try
                            copyfile(e.SrcPath, ...
                                fullfile(tmpStage, 'word', 'media', e.PartName), 'f');
                        catch
                            warning('autotest:report:Image', ...
                                'Failed to stage %s', e.SrcPath);
                        end
                    end
                end

                % zip into a temp .zip then rename to .docx.
                tmpZip = [tempname() '.zip'];
                files = autotest.report.backends.OoxmlBackend.listAllFiles(tmpStage);
                if exist(obj.OutputPath, 'file'), delete(obj.OutputPath); end
                origDir = pwd;
                try
                    cd(tmpStage);
                    zip(tmpZip, files);
                    cd(origDir);
                catch innerME
                    try, cd(origDir); catch, end
                    rethrow(innerME);
                end
                movefile(tmpZip, obj.OutputPath, 'f');
            catch ME
                try
                    if isfolder(tmpStage), rmdir(tmpStage, 's'); end
                catch
                end
                rethrow(ME);
            end
            try
                if isfolder(tmpStage), rmdir(tmpStage, 's'); end
            catch
            end
        end

        function pdfPath = renderPdf(~, ~, ~)
            % OoxmlBackend itself does not produce a PDF.  The caller
            % (ReportBuilder) drives the PDF tier via the PdfBackend
            % option.  Returning empty signals "not rendered here".
            pdfPath = '';
        end
    end

    % =================================================== private XML emit
    methods (Access = private)

        function out = applyPortionPrefix(obj, text)
            %APPLYPORTIONPREFIX  v1.6 -- prepend the DoDI 5200.48 portion code.
            %   Returns TEXT unchanged when EmitPortionMarks is off or the
            %   text is already prefixed (cheap idempotency guard).
            if ~obj.EmitPortionMarks || isempty(text)
                out = text;
                return;
            end
            if startsWith(strtrim(char(text)), obj.PortionCode)
                out = text;
                return;
            end
            out = [obj.PortionCode ' ' char(text)];
        end

        function s = headingAccentRule(~)
            %HEADINGACCENTRULE  v1.6 -- 60%-width gold rule under H1 headings.
            %   Renders as a 1pt accent-coloured bottom border on an
            %   empty paragraph indented to the 20%-80% range.  The
            %   indent gives the 60%-of-content-width effect without
            %   needing a real graphical line.
            s = string([ ...
                '<w:p><w:pPr>' ...
                '<w:ind w:left="' num2str(round(autotest.report.Style.ContentWidth*0.2)) ...
                '" w:right="' num2str(round(autotest.report.Style.ContentWidth*0.2)) '"/>' ...
                '<w:pBdr><w:bottom w:val="single" w:sz="' ...
                num2str(autotest.report.Style.AccentRuleSize) ...
                '" w:space="0" w:color="' ...
                autotest.report.Style.Accent ...
                '"/></w:pBdr>' ...
                '<w:spacing w:before="0" w:after="160"/>' ...
                '</w:pPr></w:p>']);
        end

        function s = titleParagraph(~, text, halfPts, bold, alignment, italic, colorHex)
            %TITLEPARAGRAPH  Centred / aligned heading paragraph.
            %   v1.4: italic + colorHex are optional trailing args used
            %   by the cover-page refresh.  Both default off so existing
            %   callers (TOC heading) are unaffected.
            if nargin < 6 || isempty(italic), italic = false; end
            if nargin < 7, colorHex = ''; end
            boldXml = '';
            italXml = '';
            colorXml = '';
            if bold,    boldXml = '<w:b/>'; end
            if italic,  italXml = '<w:i/>'; end
            if ~isempty(colorHex)
                colorXml = ['<w:color w:val="' colorHex '"/>'];
            end
            s = string([ ...
                '<w:p><w:pPr><w:jc w:val="' alignment '"/>' ...
                '<w:spacing w:after="200"/></w:pPr>' ...
                '<w:r><w:rPr>' boldXml italXml colorXml ...
                sprintf('<w:sz w:val="%d"/><w:szCs w:val="%d"/>', halfPts, halfPts) ...
                '</w:rPr>' ...
                '<w:t xml:space="preserve">' autotest.report.backends.OoxmlBackend.xmlEsc(text) '</w:t>' ...
                '</w:r></w:p>']);
        end

        function s = paragraphXml(~, text, varargin)
            opts = struct('Bold', false, 'Italic', false, 'Size', 0, ...
                'Style', '', 'OutlineLevel', -1, 'AfterSpacing', 0);
            for i = 1:2:numel(varargin)
                opts.(varargin{i}) = varargin{i+1};
            end
            ppr = '';
            if ~isempty(opts.Style)
                ppr = [ppr '<w:pStyle w:val="' opts.Style '"/>'];
            end
            if opts.OutlineLevel >= 0
                ppr = [ppr sprintf('<w:outlineLvl w:val="%d"/>', opts.OutlineLevel)];
            end
            if opts.AfterSpacing > 0
                ppr = [ppr sprintf('<w:spacing w:after="%d"/>', opts.AfterSpacing)];
            end
            if ~isempty(ppr)
                ppr = ['<w:pPr>' ppr '</w:pPr>'];
            end
            rpr = '';
            if opts.Bold,   rpr = [rpr '<w:b/>']; end
            if opts.Italic, rpr = [rpr '<w:i/>']; end
            if opts.Size > 0
                rpr = [rpr sprintf('<w:sz w:val="%d"/><w:szCs w:val="%d"/>', opts.Size, opts.Size)];
            end
            if ~isempty(rpr)
                rpr = ['<w:rPr>' rpr '</w:rPr>'];
            end
            txt = autotest.report.backends.OoxmlBackend.xmlEsc(text);
            s = string([ ...
                '<w:p>' ppr '<w:r>' rpr ...
                '<w:t xml:space="preserve">' txt '</w:t>' ...
                '</w:r></w:p>']);
        end

        function s = tableXml(~, headers, rows, columnWidths, headerShade, bodyShade)
            n = numel(headers);
            if numel(columnWidths) ~= n
                error('autotest:report:tableWidth', 'columnWidths must have %d entries.', n);
            end
            cellsXml = '';
            % Header row.
            cellsXml = [cellsXml '<w:tr><w:trPr><w:tblHeader/></w:trPr>'];
            for c = 1:n
                cellsXml = [cellsXml ...
                    autotest.report.backends.OoxmlBackend.cellXml( ...
                        headers{c}, columnWidths(c), true, headerShade)]; %#ok<AGROW>
            end
            cellsXml = [cellsXml '</w:tr>'];
            % Body rows.
            % v1.6: alternating-row shading (light grey on even rows) for
            % a subtler, more polished look than uniform white.  Header
            % shading retains the existing palette so the column-head
            % distinction stays clear.
            altShade = autotest.report.Style.AltRowShading;
            for r = 1:size(rows, 1)
                cellsXml = [cellsXml '<w:tr>']; %#ok<AGROW>
                if isempty(bodyShade) && mod(r, 2) == 0
                    rowShade = altShade;
                else
                    rowShade = bodyShade;
                end
                for c = 1:n
                    val = rows{r, c};
                    if isnumeric(val), val = num2str(val); end
                    cellsXml = [cellsXml ...
                        autotest.report.backends.OoxmlBackend.cellXml( ...
                            val, columnWidths(c), false, rowShade)]; %#ok<AGROW>
                end
                cellsXml = [cellsXml '</w:tr>']; %#ok<AGROW>
            end
            totalW = sum(columnWidths);
            gridCols = '';
            for c = 1:n
                gridCols = [gridCols sprintf('<w:gridCol w:w="%d"/>', columnWidths(c))]; %#ok<AGROW>
            end
            % v1.6: hairline borders only on top, bottom, and interior
            % horizontals; left, right, and interior verticals omitted
            % for a modern, less-cluttered look (Bringhurst-style ruled
            % tables, not grid tables).
            border = [ ...
                '<w:tblBorders>' ...
                '<w:top w:val="single" w:sz="6" w:color="9CA3AF"/>' ...
                '<w:bottom w:val="single" w:sz="6" w:color="9CA3AF"/>' ...
                '<w:insideH w:val="single" w:sz="4" w:color="D1D5DB"/>' ...
                '</w:tblBorders>'];
            s = string([ ...
                '<w:tbl>' ...
                '<w:tblPr>' ...
                sprintf('<w:tblW w:w="%d" w:type="dxa"/>', totalW) ...
                border ...
                '<w:tblLayout w:type="fixed"/>' ...
                '</w:tblPr>' ...
                '<w:tblGrid>' gridCols '</w:tblGrid>' ...
                cellsXml ...
                '</w:tbl>' ...
                '<w:p/>']);
        end

        function s = kvTableXml(~, kvRows, cols)
            cellsXml = '';
            for r = 1:size(kvRows, 1)
                cellsXml = [cellsXml '<w:tr>' ...
                    autotest.report.backends.OoxmlBackend.cellXml( ...
                        kvRows{r,1}, cols(1), true, ...
                        autotest.report.Style.MetaShading) ...
                    autotest.report.backends.OoxmlBackend.cellXml( ...
                        kvRows{r,2}, cols(2), false, '') ...
                    '</w:tr>']; %#ok<AGROW>
            end
            totalW = sum(cols);
            gridCols = sprintf('<w:gridCol w:w="%d"/><w:gridCol w:w="%d"/>', cols(1), cols(2));
            border = [ ...
                '<w:tblBorders><w:top w:val="single" w:sz="4" w:color="BFBFBF"/>' ...
                '<w:left w:val="single" w:sz="4" w:color="BFBFBF"/>' ...
                '<w:bottom w:val="single" w:sz="4" w:color="BFBFBF"/>' ...
                '<w:right w:val="single" w:sz="4" w:color="BFBFBF"/>' ...
                '<w:insideH w:val="single" w:sz="4" w:color="BFBFBF"/>' ...
                '<w:insideV w:val="single" w:sz="4" w:color="BFBFBF"/></w:tblBorders>'];
            s = string([ ...
                '<w:tbl>' ...
                '<w:tblPr>' ...
                sprintf('<w:tblW w:w="%d" w:type="dxa"/>', totalW) ...
                '<w:jc w:val="center"/>' ...
                border ...
                '<w:tblLayout w:type="fixed"/>' ...
                '</w:tblPr>' ...
                '<w:tblGrid>' gridCols '</w:tblGrid>' ...
                cellsXml ...
                '</w:tbl>' ...
                '<w:p/>']);
        end

        function s = distBoxXml(~, header, body)
            % Single-cell table with heavy black border, used for the
            % Distribution Statement D box on the cover page.
            cw = autotest.report.Style.ContentWidth;
            heavy = [ ...
                '<w:tblBorders><w:top w:val="single" w:sz="12" w:color="000000"/>' ...
                '<w:left w:val="single" w:sz="12" w:color="000000"/>' ...
                '<w:bottom w:val="single" w:sz="12" w:color="000000"/>' ...
                '<w:right w:val="single" w:sz="12" w:color="000000"/></w:tblBorders>'];
            inner = [ ...
                '<w:p><w:pPr><w:jc w:val="center"/><w:spacing w:after="160"/></w:pPr>' ...
                '<w:r><w:rPr><w:b/><w:sz w:val="28"/><w:szCs w:val="28"/></w:rPr>' ...
                '<w:t xml:space="preserve">' autotest.report.backends.OoxmlBackend.xmlEsc(header) '</w:t></w:r></w:p>' ...
                '<w:p><w:pPr><w:jc w:val="center"/></w:pPr>' ...
                '<w:r><w:rPr><w:sz w:val="22"/><w:szCs w:val="22"/></w:rPr>' ...
                '<w:t xml:space="preserve">' autotest.report.backends.OoxmlBackend.xmlEsc(body) '</w:t></w:r></w:p>'];
            s = string([ ...
                '<w:tbl>' ...
                '<w:tblPr>' ...
                sprintf('<w:tblW w:w="%d" w:type="dxa"/>', cw) ...
                '<w:jc w:val="center"/>' ...
                heavy ...
                '<w:tblLayout w:type="fixed"/>' ...
                '</w:tblPr>' ...
                sprintf('<w:tblGrid><w:gridCol w:w="%d"/></w:tblGrid>', cw) ...
                '<w:tr><w:tc><w:tcPr>' ...
                sprintf('<w:tcW w:w="%d" w:type="dxa"/>', cw) ...
                '<w:tcMar><w:top w:w="240" w:type="dxa"/>' ...
                '<w:left w:w="240" w:type="dxa"/>' ...
                '<w:bottom w:w="240" w:type="dxa"/>' ...
                '<w:right w:w="240" w:type="dxa"/></w:tcMar></w:tcPr>' ...
                inner ...
                '</w:tc></w:tr></w:tbl><w:p/>']);
        end

        function writeFile(~, p, text)
            fid = fopen(p, 'w');
            if fid < 3
                error('autotest:report:write', 'Cannot write %s', p);
            end
            cleanup = onCleanup(@() fclose(fid));
            % Important: write as raw UTF-8 bytes, no BOM.
            bytes = unicode2native(text, 'UTF-8');
            fwrite(fid, bytes);
        end

        function txt = documentXml(obj)
            % Phase 16 (Part B items 1+2): the FINAL sectPr applies to
            % the LAST section -- which is the main body.  It carries
            % the footer reference so Page X of Y appears under every
            % non-cover page.  The COVER section's sectPr was already
            % emitted by addCoverPage via coverSectionBreak() and
            % carries titlePg=true with no footer.
            sectPr = sprintf([...
                '<w:sectPr>' ...
                '<w:pgSz w:w="%d" w:h="%d"/>' ...
                '<w:pgMar w:top="%d" w:right="%d" w:bottom="%d" w:left="%d" w:header="708" w:footer="708" w:gutter="0"/>' ...
                '<w:cols w:space="708"/>' ...
                '<w:docGrid w:linePitch="360"/>' ...
                '<w:headerReference w:type="default" r:id="rIdHeader"/>' ...
                '<w:footerReference w:type="default" r:id="rIdFooter"/>' ...
                '</w:sectPr>'], ...
                autotest.report.Style.PageWidth, autotest.report.Style.PageHeight, ...
                autotest.report.Style.Margin, autotest.report.Style.Margin, ...
                autotest.report.Style.Margin, autotest.report.Style.Margin);
            body = strjoin(obj.BodyParts, '');
            % v1.4 (B.1/B.5): drawing + DrawingML namespaces enable the
            % <w:drawing>/<a:graphic>/<pic:pic> tree emitted by addImage.
            txt = char([ ...
                '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' ...
                '<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"' ...
                ' xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"' ...
                ' xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing"' ...
                ' xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"' ...
                ' xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture">' ...
                '<w:body>' char(body) sectPr '</w:body></w:document>']);
        end

        function s = coverSectionBreak(~)
            %COVERSECTIONBREAK  Phase 16 Part B item 2.
            %   Emit a section-break paragraph carrying the cover-page
            %   sectPr.  titlePg flag enables special first-page handling.
            %
            %   v1.4 (B.5): the cover section now references the
            %   classification header AND footer -- CAPCO requires the
            %   banner on every page including the cover.  We don't add
            %   a Page X of Y line on the cover (the existing footer
            %   carries both, the cover footer just shows the banner +
            %   the page-number paragraph -- harmless on a single-page
            %   cover where "Page 1 of N" reads cleanly under the
            %   Distribution Statement D box).
            s = string(['<w:p><w:pPr><w:sectPr>' ...
                sprintf('<w:pgSz w:w="%d" w:h="%d"/>', ...
                    autotest.report.Style.PageWidth, autotest.report.Style.PageHeight) ...
                sprintf('<w:pgMar w:top="%d" w:right="%d" w:bottom="%d" w:left="%d" w:header="708" w:footer="708" w:gutter="0"/>', ...
                    autotest.report.Style.Margin, autotest.report.Style.Margin, ...
                    autotest.report.Style.Margin, autotest.report.Style.Margin) ...
                '<w:cols w:space="708"/>' ...
                '<w:docGrid w:linePitch="360"/>' ...
                '<w:headerReference w:type="default" r:id="rIdHeader"/>' ...
                '<w:footerReference w:type="default" r:id="rIdFooter"/>' ...
                '<w:titlePg/>' ...
                '</w:sectPr></w:pPr></w:p>']);
        end

        function txt = footerXml(obj)
            %FOOTERXML  Phase 16 Part B item 1 + v1.4 B.5.
            %   Page-number line (Page X of Y, centred 9pt Calibri) with
            %   the v1.4 CAPCO classification banner above it.  Word
            %   refreshes the PAGE / NUMPAGES fields on first open via
            %   the existing <w:updateFields w:val="true"/> setting.
            fontsz = autotest.report.Style.FooterFontSize;
            rPr = sprintf('<w:rPr><w:rFonts w:ascii="Calibri" w:hAnsi="Calibri"/><w:sz w:val="%d"/><w:szCs w:val="%d"/></w:rPr>', ...
                fontsz, fontsz);
            banner = autotest.report.backends.OoxmlBackend.classificationBannerXml(obj.Classification);
            txt = char([ ...
                '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' ...
                '<w:ftr xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">' ...
                '<w:p>' ...
                '<w:pPr><w:jc w:val="center"/></w:pPr>' ...
                '<w:r>' rPr '<w:t xml:space="preserve">Page </w:t></w:r>' ...
                '<w:fldSimple w:instr="PAGE"><w:r>' rPr '<w:t>1</w:t></w:r></w:fldSimple>' ...
                '<w:r>' rPr '<w:t xml:space="preserve"> of </w:t></w:r>' ...
                '<w:fldSimple w:instr="NUMPAGES"><w:r>' rPr '<w:t>1</w:t></w:r></w:fldSimple>' ...
                '</w:p>' ...
                banner ...
                '</w:ftr>']);
        end

        function txt = footerRelsXml(~)
            %FOOTERRELSXML  Empty Relationships document for footer1.xml.
            %   The footer carries no embedded references; Word still
            %   requires the rels part to exist alongside the footer
            %   part to satisfy package validation.
            txt = char([ ...
                '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' ...
                '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">' ...
                '</Relationships>']);
        end

        function txt = headerXml(obj)
            %HEADERXML  v1.4 (B.5) -- top-of-page CAPCO classification banner.
            %   Single shaded paragraph carrying the classification level
            %   centred in white bold over a per-level background.  Tied
            %   to the main + cover sections via rIdHeader.
            banner = autotest.report.backends.OoxmlBackend.classificationBannerXml(obj.Classification);
            txt = char([ ...
                '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' ...
                '<w:hdr xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">' ...
                banner ...
                '</w:hdr>']);
        end

        function txt = headerRelsXml(~)
            %HEADERRELSXML  Empty Relationships document for header1.xml.
            txt = char([ ...
                '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' ...
                '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">' ...
                '</Relationships>']);
        end

        function txt = stylesXml(~)
            % v1.6 body typography refresh:
            %   - Default body uses Georgia 11pt with justified alignment,
            %     1.5x line spacing, and a 160-twentieth (8pt) post-paragraph
            %     spacing for a less-cramped layout.
            %   - Headings retain Calibri (sans) so the heading/body
            %     visual hierarchy is clear (serif body / sans headings is
            %     the standard professional pairing).
            sb = ['<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' ...
                '<w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">'];
            sb = [sb '<w:docDefaults>' ...
                '<w:rPrDefault><w:rPr>' ...
                '<w:rFonts w:ascii="Georgia" w:hAnsi="Georgia"/>' ...
                '<w:sz w:val="22"/><w:szCs w:val="22"/>' ...
                '</w:rPr></w:rPrDefault>' ...
                '<w:pPrDefault><w:pPr>' ...
                '<w:spacing w:after="160" w:line="312" w:lineRule="auto"/>' ...
                '<w:jc w:val="both"/>' ...
                '</w:pPr></w:pPrDefault>' ...
                '</w:docDefaults>'];
            sb = [sb '<w:style w:type="paragraph" w:styleId="Normal" w:default="1">' ...
                '<w:name w:val="Normal"/></w:style>'];
            sb = [sb autotest.report.backends.OoxmlBackend.headingStyleXml(1, 32, 400, 200) ];
            sb = [sb autotest.report.backends.OoxmlBackend.headingStyleXml(2, 28, 280, 160) ];
            sb = [sb autotest.report.backends.OoxmlBackend.headingStyleXml(3, 24, 200, 140) ];
            sb = [sb '<w:style w:type="paragraph" w:styleId="TOC">' ...
                '<w:name w:val="TOC Heading"/><w:basedOn w:val="Normal"/></w:style>'];
            sb = [sb '</w:styles>'];
            txt = char(sb);
        end

        function txt = settingsXml(~)
            % updateFields=true tells Word to refresh the TOC field on
            % first open.  Critical for populated page numbers without
            % requiring the reader to manually update.
            txt = char([ ...
                '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' ...
                '<w:settings xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">' ...
                '<w:updateFields w:val="true"/>' ...
                '<w:compat><w:compatSetting w:name="compatibilityMode" w:uri="http://schemas.microsoft.com/office/word" w:val="15"/></w:compat>' ...
                '</w:settings>']);
        end

        function txt = contentTypesXml(~)
            % Phase 16 (Part B item 1): register footer1.xml so Word
            % loads it when the main section's sectPr references it.
            % v1.4 (B.1/B.5): register PNG default + header1 part.
            txt = char([ ...
                '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' ...
                '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">' ...
                '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>' ...
                '<Default Extension="xml" ContentType="application/xml"/>' ...
                '<Default Extension="png" ContentType="image/png"/>' ...
                '<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>' ...
                '<Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/>' ...
                '<Override PartName="/word/settings.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.settings+xml"/>' ...
                '<Override PartName="/word/header1.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.header+xml"/>' ...
                '<Override PartName="/word/footer1.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.footer+xml"/>' ...
                '</Types>']);
        end

        function txt = rootRelsXml(~)
            txt = char([ ...
                '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' ...
                '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">' ...
                '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>' ...
                '</Relationships>']);
        end

        function txt = docRelsXml(obj)
            % Phase 16 (Part B item 1): the main section's sectPr
            % references the footer via r:id="rIdFooter".  This rel
            % entry is what binds that ID to the footer1.xml part.
            % v1.4 (B.1/B.5): bind rIdHeader to header1.xml AND emit
            % one rIdImgN per addImage call so embedded charts resolve.
            extras = '';
            for i = 1:numel(obj.ImageEntries)
                e = obj.ImageEntries(i);
                extras = [extras sprintf( ...
                    '<Relationship Id="%s" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="media/%s"/>', ...
                    e.RelId, e.PartName)]; %#ok<AGROW>
            end
            txt = char([ ...
                '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' ...
                '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">' ...
                '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>' ...
                '<Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/settings" Target="settings.xml"/>' ...
                '<Relationship Id="rIdHeader" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/header" Target="header1.xml"/>' ...
                '<Relationship Id="rIdFooter" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/footer" Target="footer1.xml"/>' ...
                extras ...
                '</Relationships>']);
        end
    end

    methods (Static, Access = private)
        function out = xmlEsc(text)
            % Escape &, <, >, ", '
            t = char(text);
            t = strrep(t, '&', '&amp;');
            t = strrep(t, '<', '&lt;');
            t = strrep(t, '>', '&gt;');
            t = strrep(t, '"', '&quot;');
            t = strrep(t, '''', '&apos;');
            out = t;
        end

        function s = cellXml(text, widthDxa, bold, shadeColor)
            % v1.6: detect [STATUS:<name>] sentinel and render the cell
            % as a status badge -- coloured pill text on a fill matching
            % the v1.6 badge palette.  Falls through to plain rendering
            % when the sentinel is absent.
            txtChar = char(text);
            statusTok = regexp(txtChar, '^\[STATUS:([A-Za-z]+)\]$', ...
                'tokens', 'once');
            if ~isempty(statusTok)
                [fillHex, textHex, label] = ...
                    autotest.report.Style.statusBadge(statusTok{1});
                tcPr = sprintf('<w:tcW w:w="%d" w:type="dxa"/>', widthDxa);
                tcPr = [tcPr sprintf( ...
                    '<w:shd w:val="clear" w:color="auto" w:fill="%s"/>', ...
                    fillHex)];
                tcPr = [tcPr ...
                    '<w:tcMar>' ...
                    '<w:top w:w="60" w:type="dxa"/>' ...
                    '<w:left w:w="100" w:type="dxa"/>' ...
                    '<w:bottom w:w="60" w:type="dxa"/>' ...
                    '<w:right w:w="100" w:type="dxa"/>' ...
                    '</w:tcMar>'];
                lbl = autotest.report.backends.OoxmlBackend.xmlEsc(upper(label));
                s = ['<w:tc><w:tcPr>' tcPr '</w:tcPr>' ...
                     '<w:p><w:pPr><w:jc w:val="center"/></w:pPr><w:r>' ...
                     '<w:rPr><w:b/>' ...
                     '<w:rFonts w:ascii="Calibri" w:hAnsi="Calibri"/>' ...
                     '<w:color w:val="' textHex '"/>' ...
                     '<w:sz w:val="18"/><w:szCs w:val="18"/>' ...
                     '</w:rPr><w:t xml:space="preserve">' lbl ...
                     '</w:t></w:r></w:p></w:tc>'];
                return;
            end
            tcPr = sprintf('<w:tcW w:w="%d" w:type="dxa"/>', widthDxa);
            if ~isempty(shadeColor)
                tcPr = [tcPr sprintf('<w:shd w:val="clear" w:color="auto" w:fill="%s"/>', shadeColor)];
            end
            tcPr = [tcPr ...
                '<w:tcMar>' ...
                '<w:top w:w="80" w:type="dxa"/>' ...
                '<w:left w:w="120" w:type="dxa"/>' ...
                '<w:bottom w:w="80" w:type="dxa"/>' ...
                '<w:right w:w="120" w:type="dxa"/>' ...
                '</w:tcMar>'];
            rpr = '';
            if bold, rpr = '<w:rPr><w:b/></w:rPr>'; end
            txtEsc = autotest.report.backends.OoxmlBackend.xmlEsc(text);
            s = ['<w:tc><w:tcPr>' tcPr '</w:tcPr>' ...
                 '<w:p><w:r>' rpr '<w:t xml:space="preserve">' txtEsc '</w:t></w:r></w:p>' ...
                 '</w:tc>'];
        end

        function out = headingStyleXml(level, size, before, after)
            % v1.6: headings override the (now-serif) body default with
            % Calibri (sans) and the charcoal palette colour so the
            % serif-body / sans-heading hierarchy is clear, and override
            % the justified body alignment with left-aligned headings.
            out = sprintf([...
                '<w:style w:type="paragraph" w:styleId="Heading%d">' ...
                '<w:name w:val="heading %d"/>' ...
                '<w:basedOn w:val="Normal"/>' ...
                '<w:next w:val="Normal"/>' ...
                '<w:qFormat/>' ...
                '<w:pPr><w:spacing w:before="%d" w:after="%d"/>' ...
                '<w:jc w:val="left"/>' ...
                '<w:outlineLvl w:val="%d"/></w:pPr>' ...
                '<w:rPr>' ...
                '<w:rFonts w:ascii="Calibri" w:hAnsi="Calibri"/>' ...
                '<w:b/><w:color w:val="1F2937"/>' ...
                '<w:sz w:val="%d"/><w:szCs w:val="%d"/>' ...
                '</w:rPr>' ...
                '</w:style>'], ...
                level, level, before, after, level - 1, size, size);
        end

        function files = listAllFiles(stageDir)
            files = {};
            list = dir(fullfile(stageDir, '**', '*'));
            for i = 1:numel(list)
                d = list(i);
                if d.isdir, continue; end
                full = fullfile(d.folder, d.name);
                rel = strrep(full, [stageDir filesep], '');
                files{end+1} = rel; %#ok<AGROW>
            end
        end

        function s = classificationBannerXml(level)
            %CLASSIFICATIONBANNERXML  v1.4 (CAPCO colour) + v1.6 (DoDM plain).
            %   Per DoDM 5200.01 V2, UNCLASSIFIED documents use a plain
            %   centred-text banner -- no coloured background block.
            %   Higher classifications keep the v1.4 CAPCO colour map
            %   (UNCLASSIFIED green is no longer applied, per the spec).
            sz   = autotest.report.Style.BannerFontSize;
            txt  = autotest.report.backends.OoxmlBackend.xmlEsc(upper(strtrim(level)));
            if autotest.report.Style.isUnclassified(level)
                % Plain text, charcoal, centred; no shading, no colour box.
                s = [ ...
                    '<w:p>' ...
                    '<w:pPr>' ...
                    '<w:jc w:val="center"/>' ...
                    '<w:spacing w:before="0" w:after="0"/>' ...
                    '<w:pBdr>' ...
                    '<w:top w:val="single" w:sz="4" w:color="D1D5DB"/>' ...
                    '<w:bottom w:val="single" w:sz="4" w:color="D1D5DB"/>' ...
                    '</w:pBdr>' ...
                    '</w:pPr>' ...
                    '<w:r>' ...
                    '<w:rPr>' ...
                    '<w:rFonts w:ascii="Calibri" w:hAnsi="Calibri"/>' ...
                    '<w:b/>' ...
                    '<w:color w:val="' autotest.report.Style.PrimaryText '"/>' ...
                    sprintf('<w:sz w:val="%d"/><w:szCs w:val="%d"/>', sz, sz) ...
                    '</w:rPr>' ...
                    '<w:t xml:space="preserve">' txt '</w:t>' ...
                    '</w:r>' ...
                    '</w:p>'];
            else
                fill = autotest.report.Style.classificationFill(level);
                s = [ ...
                    '<w:p>' ...
                    '<w:pPr>' ...
                    '<w:shd w:val="clear" w:color="auto" w:fill="' fill '"/>' ...
                    '<w:jc w:val="center"/>' ...
                    '<w:spacing w:before="0" w:after="0"/>' ...
                    '</w:pPr>' ...
                    '<w:r>' ...
                    '<w:rPr>' ...
                    '<w:rFonts w:ascii="Calibri" w:hAnsi="Calibri"/>' ...
                    '<w:b/>' ...
                    '<w:color w:val="FFFFFF"/>' ...
                    sprintf('<w:sz w:val="%d"/><w:szCs w:val="%d"/>', sz, sz) ...
                    '</w:rPr>' ...
                    '<w:t xml:space="preserve">' txt '</w:t>' ...
                    '</w:r>' ...
                    '</w:p>'];
            end
        end

        function s = drawingParagraphXml(relId, idNum, widthEmu, heightEmu)
            %DRAWINGPARAGRAPHXML  v1.4 (B.1/B.2) -- inline picture paragraph.
            %   Wraps an <a:graphic>/<pic:pic> tree binding to the image
            %   relationship Id minted by addImage.  Default sizing
            %   matches the caller's DXA-converted-to-EMU dimensions; no
            %   wrapping (wp:inline) so the chart sits between paragraphs
            %   like a regular block.
            name = sprintf('Picture%d', idNum);
            s = sprintf([ ...
                '<w:p><w:r><w:drawing>' ...
                '<wp:inline distT="0" distB="0" distL="0" distR="0">' ...
                '<wp:extent cx="%d" cy="%d"/>' ...
                '<wp:effectExtent l="0" t="0" r="0" b="0"/>' ...
                '<wp:docPr id="%d" name="%s"/>' ...
                '<wp:cNvGraphicFramePr/>' ...
                '<a:graphic>' ...
                '<a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/picture">' ...
                '<pic:pic>' ...
                '<pic:nvPicPr>' ...
                '<pic:cNvPr id="%d" name="%s"/>' ...
                '<pic:cNvPicPr/>' ...
                '</pic:nvPicPr>' ...
                '<pic:blipFill>' ...
                '<a:blip r:embed="%s"/>' ...
                '<a:stretch><a:fillRect/></a:stretch>' ...
                '</pic:blipFill>' ...
                '<pic:spPr>' ...
                '<a:xfrm><a:off x="0" y="0"/><a:ext cx="%d" cy="%d"/></a:xfrm>' ...
                '<a:prstGeom prst="rect"><a:avLst/></a:prstGeom>' ...
                '</pic:spPr>' ...
                '</pic:pic>' ...
                '</a:graphicData>' ...
                '</a:graphic>' ...
                '</wp:inline>' ...
                '</w:drawing></w:r></w:p>'], ...
                widthEmu, heightEmu, idNum, name, idNum, name, relId, ...
                widthEmu, heightEmu);
        end

        function s = codeLineXml(line)
            %CODELINEXML  v1.4 (B.4) -- one monospace, light-grey-filled line.
            %   Each diagnostic line gets its own <w:p> sharing the same
            %   shading + font so consecutive lines render as a contiguous
            %   monospace block.  Tight before/after spacing keeps the
            %   block compact.
            sz   = autotest.report.Style.CodeFontSize;
            font = autotest.report.Style.CodeFontName;
            fill = autotest.report.Style.CodeFill;
            txt  = autotest.report.backends.OoxmlBackend.xmlEsc(line);
            if isempty(line), txt = ' '; end  % preserve blank line height
            s = [ ...
                '<w:p>' ...
                '<w:pPr>' ...
                '<w:shd w:val="clear" w:color="auto" w:fill="' fill '"/>' ...
                '<w:spacing w:before="0" w:after="0" w:line="240" w:lineRule="auto"/>' ...
                '<w:ind w:left="120" w:right="120"/>' ...
                '</w:pPr>' ...
                '<w:r>' ...
                '<w:rPr>' ...
                '<w:rFonts w:ascii="' font '" w:hAnsi="' font '" w:cs="' font '"/>' ...
                sprintf('<w:sz w:val="%d"/><w:szCs w:val="%d"/>', sz, sz) ...
                '</w:rPr>' ...
                '<w:t xml:space="preserve">' txt '</w:t>' ...
                '</w:r>' ...
                '</w:p>'];
        end
    end
end
