classdef OoxmlBackend < handle
    %OOXMLBACKEND  Phase 15 -- hand-rolled OOXML .docx emitter.
    %
    %   Used as the fallback when MATLAB Report Generator is not
    %   licensed.  Emits a valid Word 2007+ .docx by composing each
    %   constituent XML file as a char vector, staging them in a
    %   tempdir, and packing with builtin zip().
    %
    %   Public API mirrors RptgenBackend so SectionBuilder / CoverPage
    %   can render to either backend without conditionals.
    %
    %   Fidelity caveats vs. RptgenBackend:
    %     - Footer page numbers are emitted via a one-line w:fldSimple
    %       in a default footer; styling is minimal.
    %     - No table-of-figures, no captions, no styles beyond
    %       Heading 1/2/3 and Normal.
    %     - Tables use a uniform 1/2 pt grey border; no cell merging.
    %   These limits are intentional -- the goal is structural parity
    %   with the reference, not pixel-perfect typography.

    properties (SetAccess = immutable)
        OutputPath  (1,:) char
    end

    properties (SetAccess = private)
        BodyParts   string = string.empty   % accumulated <w:p> / <w:tbl> XML strings
        ContentWidth double = 9360
    end

    methods
        function obj = OoxmlBackend(outputPath)
            arguments
                outputPath (1,:) char
            end
            obj.OutputPath = outputPath;
            obj.ContentWidth = autotest.report.Style.ContentWidth;
        end

        % ===================================================== Cover page

        function addCoverPage(obj, fields, distHeader, distBody)
            %ADDCOVERPAGE  Title block + metadata table + bordered dist box.
            %   FIELDS is a cell array of {key, value} pairs for the
            %   metadata table.  DISTHEADER / DISTBODY are the strings
            %   inside the bordered Distribution Statement D box.
            %
            %   Phase 16 (Part B item 2): the cover ends with a SECTION
            %   break, not a plain page break.  The cover-page section
            %   carries titlePg=true and no footer reference -- so the
            %   distribution statement is not crowded by Page X of Y.
            %   The main section that follows picks up the footer via
            %   the final sectPr emitted at the end of <w:body>.
            obj.addBlankParagraph(900);
            obj.BodyParts(end+1) = obj.titleParagraph(fields.Title, ...
                autotest.report.Style.TitleFontSize, true, 'center');
            obj.BodyParts(end+1) = obj.titleParagraph(fields.Subtitle, ...
                autotest.report.Style.SubtitleFontSize, false, 'center');
            obj.addBlankParagraph(300);
            % Metadata table (centered, 2 cols).
            obj.BodyParts(end+1) = obj.kvTableXml(fields.Metadata, [3000, 4500]);
            obj.addBlankParagraph(600);
            % Distribution Statement D box.
            obj.BodyParts(end+1) = obj.distBoxXml(distHeader, distBody);
            % Cover-only section break (no footer ref, titlePg=true).
            obj.BodyParts(end+1) = obj.coverSectionBreak();
        end

        % ===================================================== Headings + body

        function addHeading(obj, level, text)
            %ADDHEADING  Level 1, 2, or 3.
            arguments
                obj
                level   (1,1) double {mustBeMember(level, [1 2 3])}
                text    (1,:) char
            end
            styleId = sprintf('Heading%d', level);
            sizeMap = [autotest.report.Style.H1FontSize, ...
                       autotest.report.Style.H2FontSize, ...
                       autotest.report.Style.H3FontSize];
            obj.BodyParts(end+1) = obj.paragraphXml(text, ...
                'Bold', true, 'Size', sizeMap(level), ...
                'Style', styleId, 'OutlineLevel', level - 1);
        end

        function addParagraph(obj, text)
            arguments
                obj
                text (1,:) char
            end
            obj.BodyParts(end+1) = obj.paragraphXml(text, 'AfterSpacing', 120);
        end

        function addPageBreak(obj)
            obj.BodyParts(end+1) = string( ...
                "<w:p><w:r><w:br w:type=""page""/></w:r></w:p>");
        end

        function addBlankParagraph(obj, beforeSpacing)
            if nargin < 2, beforeSpacing = 0; end
            extra = '';
            if beforeSpacing > 0
                extra = sprintf('<w:spacing w:before="%d"/>', beforeSpacing);
            end
            obj.BodyParts(end+1) = string( ...
                ['<w:p><w:pPr>' extra '</w:pPr><w:r><w:t/></w:r></w:p>']);
        end

        % ===================================================== TOC

        function addTOC(obj, headingText)
            arguments
                obj
                headingText (1,:) char = 'Table of Contents'
            end
            obj.BodyParts(end+1) = obj.titleParagraph(headingText, 36, true, 'center');
            % w:fldChar begin -> instrText -> fldChar end pattern.
            tocXml = string([ ...
                '<w:p><w:pPr><w:pStyle w:val="TOC"/></w:pPr>' ...
                '<w:r><w:fldChar w:fldCharType="begin" w:dirty="true"/></w:r>' ...
                '<w:r><w:instrText xml:space="preserve">TOC \o "1-3" \h \z \u</w:instrText></w:r>' ...
                '<w:r><w:fldChar w:fldCharType="separate"/></w:r>' ...
                '<w:r><w:t>(Right-click the TOC and choose "Update Field" if Word does not auto-populate it.)</w:t></w:r>' ...
                '<w:r><w:fldChar w:fldCharType="end"/></w:r>' ...
                '</w:p>']);
            obj.BodyParts(end+1) = tocXml;
            obj.addPageBreak();
        end

        % ===================================================== Tables

        function addTable(obj, headers, rows, columnWidths)
            %ADDTABLE  Headers across the top, columnWidths in DXA.
            arguments
                obj
                headers       cell
                rows          cell
                columnWidths  double
            end
            obj.BodyParts(end+1) = obj.tableXml(headers, rows, columnWidths, ...
                autotest.report.Style.HeaderShading, '');
        end

        function addMetaTable(obj, kvRows)
            %ADDMETATABLE  Two-column key/value table; centered.
            cols = [3000, 4500];
            obj.BodyParts(end+1) = obj.kvTableXml(kvRows, cols);
        end

        % ===================================================== Output

        function close(obj)
            %CLOSE  Stage XML files and zip into the .docx.
            tmpStage = tempname();
            mkdir(tmpStage);
            try
                mkdir(fullfile(tmpStage, '_rels'));
                mkdir(fullfile(tmpStage, 'word'));
                mkdir(fullfile(tmpStage, 'word', '_rels'));

                obj.writeFile(fullfile(tmpStage, '[Content_Types].xml'), obj.contentTypesXml());
                obj.writeFile(fullfile(tmpStage, '_rels', '.rels'),       obj.rootRelsXml());
                obj.writeFile(fullfile(tmpStage, 'word', 'document.xml'),  obj.documentXml());
                obj.writeFile(fullfile(tmpStage, 'word', '_rels', 'document.xml.rels'), obj.docRelsXml());
                obj.writeFile(fullfile(tmpStage, 'word', 'styles.xml'),    obj.stylesXml());
                obj.writeFile(fullfile(tmpStage, 'word', 'settings.xml'),  obj.settingsXml());
                % Phase 16 (Part B item 1): page-number footer.
                obj.writeFile(fullfile(tmpStage, 'word', 'footer1.xml'),   obj.footerXml());
                obj.writeFile(fullfile(tmpStage, 'word', '_rels', 'footer1.xml.rels'), obj.footerRelsXml());

                % zip into a temp .zip then rename to .docx.
                tmpZip = [tempname() '.zip'];
                files = autotest.report.backends.OoxmlBackend.listAllFiles(tmpStage);
                if exist(obj.OutputPath, 'file'), delete(obj.OutputPath); end
                origDir = pwd;
                try
                    cd(tmpStage);
                    zip(tmpZip, files);
                    cd(origDir);
                catch innerME
                    try, cd(origDir); catch, end
                    rethrow(innerME);
                end
                movefile(tmpZip, obj.OutputPath, 'f');
            catch ME
                try
                    if isfolder(tmpStage), rmdir(tmpStage, 's'); end
                catch
                end
                rethrow(ME);
            end
            try
                if isfolder(tmpStage), rmdir(tmpStage, 's'); end
            catch
            end
        end

        function pdfPath = renderPdf(~, ~, ~)
            % OoxmlBackend itself does not produce a PDF.  The caller
            % (ReportBuilder) drives the PDF tier via the PdfBackend
            % option.  Returning empty signals "not rendered here".
            pdfPath = '';
        end
    end

    % =================================================== private XML emit
    methods (Access = private)

        function s = titleParagraph(~, text, halfPts, bold, alignment)
            boldXml = '';
            if bold, boldXml = '<w:b/>'; end
            s = string([ ...
                '<w:p><w:pPr><w:jc w:val="' alignment '"/>' ...
                '<w:spacing w:after="200"/></w:pPr>' ...
                '<w:r><w:rPr>' boldXml ...
                sprintf('<w:sz w:val="%d"/><w:szCs w:val="%d"/>', halfPts, halfPts) ...
                '</w:rPr>' ...
                '<w:t xml:space="preserve">' autotest.report.backends.OoxmlBackend.xmlEsc(text) '</w:t>' ...
                '</w:r></w:p>']);
        end

        function s = paragraphXml(~, text, varargin)
            opts = struct('Bold', false, 'Italic', false, 'Size', 0, ...
                'Style', '', 'OutlineLevel', -1, 'AfterSpacing', 0);
            for i = 1:2:numel(varargin)
                opts.(varargin{i}) = varargin{i+1};
            end
            ppr = '';
            if ~isempty(opts.Style)
                ppr = [ppr '<w:pStyle w:val="' opts.Style '"/>'];
            end
            if opts.OutlineLevel >= 0
                ppr = [ppr sprintf('<w:outlineLvl w:val="%d"/>', opts.OutlineLevel)];
            end
            if opts.AfterSpacing > 0
                ppr = [ppr sprintf('<w:spacing w:after="%d"/>', opts.AfterSpacing)];
            end
            if ~isempty(ppr)
                ppr = ['<w:pPr>' ppr '</w:pPr>'];
            end
            rpr = '';
            if opts.Bold,   rpr = [rpr '<w:b/>']; end
            if opts.Italic, rpr = [rpr '<w:i/>']; end
            if opts.Size > 0
                rpr = [rpr sprintf('<w:sz w:val="%d"/><w:szCs w:val="%d"/>', opts.Size, opts.Size)];
            end
            if ~isempty(rpr)
                rpr = ['<w:rPr>' rpr '</w:rPr>'];
            end
            txt = autotest.report.backends.OoxmlBackend.xmlEsc(text);
            s = string([ ...
                '<w:p>' ppr '<w:r>' rpr ...
                '<w:t xml:space="preserve">' txt '</w:t>' ...
                '</w:r></w:p>']);
        end

        function s = tableXml(~, headers, rows, columnWidths, headerShade, bodyShade)
            n = numel(headers);
            if numel(columnWidths) ~= n
                error('autotest:report:tableWidth', 'columnWidths must have %d entries.', n);
            end
            cellsXml = '';
            % Header row.
            cellsXml = [cellsXml '<w:tr><w:trPr><w:tblHeader/></w:trPr>'];
            for c = 1:n
                cellsXml = [cellsXml ...
                    autotest.report.backends.OoxmlBackend.cellXml( ...
                        headers{c}, columnWidths(c), true, headerShade)]; %#ok<AGROW>
            end
            cellsXml = [cellsXml '</w:tr>'];
            % Body rows.
            for r = 1:size(rows, 1)
                cellsXml = [cellsXml '<w:tr>']; %#ok<AGROW>
                for c = 1:n
                    val = rows{r, c};
                    if isnumeric(val), val = num2str(val); end
                    cellsXml = [cellsXml ...
                        autotest.report.backends.OoxmlBackend.cellXml( ...
                            val, columnWidths(c), false, bodyShade)]; %#ok<AGROW>
                end
                cellsXml = [cellsXml '</w:tr>']; %#ok<AGROW>
            end
            totalW = sum(columnWidths);
            gridCols = '';
            for c = 1:n
                gridCols = [gridCols sprintf('<w:gridCol w:w="%d"/>', columnWidths(c))]; %#ok<AGROW>
            end
            border = [ ...
                '<w:tblBorders><w:top w:val="single" w:sz="4" w:color="BFBFBF"/>' ...
                '<w:left w:val="single" w:sz="4" w:color="BFBFBF"/>' ...
                '<w:bottom w:val="single" w:sz="4" w:color="BFBFBF"/>' ...
                '<w:right w:val="single" w:sz="4" w:color="BFBFBF"/>' ...
                '<w:insideH w:val="single" w:sz="4" w:color="BFBFBF"/>' ...
                '<w:insideV w:val="single" w:sz="4" w:color="BFBFBF"/></w:tblBorders>'];
            s = string([ ...
                '<w:tbl>' ...
                '<w:tblPr>' ...
                sprintf('<w:tblW w:w="%d" w:type="dxa"/>', totalW) ...
                border ...
                '<w:tblLayout w:type="fixed"/>' ...
                '</w:tblPr>' ...
                '<w:tblGrid>' gridCols '</w:tblGrid>' ...
                cellsXml ...
                '</w:tbl>' ...
                '<w:p/>']);
        end

        function s = kvTableXml(~, kvRows, cols)
            cellsXml = '';
            for r = 1:size(kvRows, 1)
                cellsXml = [cellsXml '<w:tr>' ...
                    autotest.report.backends.OoxmlBackend.cellXml( ...
                        kvRows{r,1}, cols(1), true, ...
                        autotest.report.Style.MetaShading) ...
                    autotest.report.backends.OoxmlBackend.cellXml( ...
                        kvRows{r,2}, cols(2), false, '') ...
                    '</w:tr>']; %#ok<AGROW>
            end
            totalW = sum(cols);
            gridCols = sprintf('<w:gridCol w:w="%d"/><w:gridCol w:w="%d"/>', cols(1), cols(2));
            border = [ ...
                '<w:tblBorders><w:top w:val="single" w:sz="4" w:color="BFBFBF"/>' ...
                '<w:left w:val="single" w:sz="4" w:color="BFBFBF"/>' ...
                '<w:bottom w:val="single" w:sz="4" w:color="BFBFBF"/>' ...
                '<w:right w:val="single" w:sz="4" w:color="BFBFBF"/>' ...
                '<w:insideH w:val="single" w:sz="4" w:color="BFBFBF"/>' ...
                '<w:insideV w:val="single" w:sz="4" w:color="BFBFBF"/></w:tblBorders>'];
            s = string([ ...
                '<w:tbl>' ...
                '<w:tblPr>' ...
                sprintf('<w:tblW w:w="%d" w:type="dxa"/>', totalW) ...
                '<w:jc w:val="center"/>' ...
                border ...
                '<w:tblLayout w:type="fixed"/>' ...
                '</w:tblPr>' ...
                '<w:tblGrid>' gridCols '</w:tblGrid>' ...
                cellsXml ...
                '</w:tbl>' ...
                '<w:p/>']);
        end

        function s = distBoxXml(~, header, body)
            % Single-cell table with heavy black border, used for the
            % Distribution Statement D box on the cover page.
            cw = autotest.report.Style.ContentWidth;
            heavy = [ ...
                '<w:tblBorders><w:top w:val="single" w:sz="12" w:color="000000"/>' ...
                '<w:left w:val="single" w:sz="12" w:color="000000"/>' ...
                '<w:bottom w:val="single" w:sz="12" w:color="000000"/>' ...
                '<w:right w:val="single" w:sz="12" w:color="000000"/></w:tblBorders>'];
            inner = [ ...
                '<w:p><w:pPr><w:jc w:val="center"/><w:spacing w:after="160"/></w:pPr>' ...
                '<w:r><w:rPr><w:b/><w:sz w:val="28"/><w:szCs w:val="28"/></w:rPr>' ...
                '<w:t xml:space="preserve">' autotest.report.backends.OoxmlBackend.xmlEsc(header) '</w:t></w:r></w:p>' ...
                '<w:p><w:pPr><w:jc w:val="center"/></w:pPr>' ...
                '<w:r><w:rPr><w:sz w:val="22"/><w:szCs w:val="22"/></w:rPr>' ...
                '<w:t xml:space="preserve">' autotest.report.backends.OoxmlBackend.xmlEsc(body) '</w:t></w:r></w:p>'];
            s = string([ ...
                '<w:tbl>' ...
                '<w:tblPr>' ...
                sprintf('<w:tblW w:w="%d" w:type="dxa"/>', cw) ...
                '<w:jc w:val="center"/>' ...
                heavy ...
                '<w:tblLayout w:type="fixed"/>' ...
                '</w:tblPr>' ...
                sprintf('<w:tblGrid><w:gridCol w:w="%d"/></w:tblGrid>', cw) ...
                '<w:tr><w:tc><w:tcPr>' ...
                sprintf('<w:tcW w:w="%d" w:type="dxa"/>', cw) ...
                '<w:tcMar><w:top w:w="240" w:type="dxa"/>' ...
                '<w:left w:w="240" w:type="dxa"/>' ...
                '<w:bottom w:w="240" w:type="dxa"/>' ...
                '<w:right w:w="240" w:type="dxa"/></w:tcMar></w:tcPr>' ...
                inner ...
                '</w:tc></w:tr></w:tbl><w:p/>']);
        end

        function writeFile(~, p, text)
            fid = fopen(p, 'w');
            if fid < 3
                error('autotest:report:write', 'Cannot write %s', p);
            end
            cleanup = onCleanup(@() fclose(fid));
            % Important: write as raw UTF-8 bytes, no BOM.
            bytes = unicode2native(text, 'UTF-8');
            fwrite(fid, bytes);
        end

        function txt = documentXml(obj)
            % Phase 16 (Part B items 1+2): the FINAL sectPr applies to
            % the LAST section -- which is the main body.  It carries
            % the footer reference so Page X of Y appears under every
            % non-cover page.  The COVER section's sectPr was already
            % emitted by addCoverPage via coverSectionBreak() and
            % carries titlePg=true with no footer.
            sectPr = sprintf([...
                '<w:sectPr>' ...
                '<w:pgSz w:w="%d" w:h="%d"/>' ...
                '<w:pgMar w:top="%d" w:right="%d" w:bottom="%d" w:left="%d" w:header="708" w:footer="708" w:gutter="0"/>' ...
                '<w:cols w:space="708"/>' ...
                '<w:docGrid w:linePitch="360"/>' ...
                '<w:footerReference w:type="default" r:id="rIdFooter"/>' ...
                '</w:sectPr>'], ...
                autotest.report.Style.PageWidth, autotest.report.Style.PageHeight, ...
                autotest.report.Style.Margin, autotest.report.Style.Margin, ...
                autotest.report.Style.Margin, autotest.report.Style.Margin);
            body = strjoin(obj.BodyParts, '');
            txt = char([ ...
                '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' ...
                '<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"' ...
                ' xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">' ...
                '<w:body>' char(body) sectPr '</w:body></w:document>']);
        end

        function s = coverSectionBreak(~)
            %COVERSECTIONBREAK  Phase 16 Part B item 2.
            %   Emit a section-break paragraph carrying the cover-page
            %   sectPr.  titlePg flag enables special first-page handling.
            %   No footer reference -- the cover gets no Page X of Y line.
            s = string(['<w:p><w:pPr><w:sectPr>' ...
                sprintf('<w:pgSz w:w="%d" w:h="%d"/>', ...
                    autotest.report.Style.PageWidth, autotest.report.Style.PageHeight) ...
                sprintf('<w:pgMar w:top="%d" w:right="%d" w:bottom="%d" w:left="%d" w:header="708" w:footer="708" w:gutter="0"/>', ...
                    autotest.report.Style.Margin, autotest.report.Style.Margin, ...
                    autotest.report.Style.Margin, autotest.report.Style.Margin) ...
                '<w:cols w:space="708"/>' ...
                '<w:docGrid w:linePitch="360"/>' ...
                '<w:titlePg/>' ...
                '</w:sectPr></w:pPr></w:p>']);
        end

        function txt = footerXml(~)
            %FOOTERXML  Phase 16 Part B item 1: page-number footer.
            %   Centred 9pt Calibri "Page X of Y" using <w:fldSimple>
            %   PAGE / NUMPAGES fields.  Word refreshes both fields on
            %   first open via the existing <w:updateFields w:val="true"/>
            %   in settings.xml.
            fontsz = autotest.report.Style.FooterFontSize;
            rPr = sprintf('<w:rPr><w:rFonts w:ascii="Calibri" w:hAnsi="Calibri"/><w:sz w:val="%d"/><w:szCs w:val="%d"/></w:rPr>', ...
                fontsz, fontsz);
            txt = char([ ...
                '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' ...
                '<w:ftr xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">' ...
                '<w:p>' ...
                '<w:pPr><w:jc w:val="center"/></w:pPr>' ...
                '<w:r>' rPr '<w:t xml:space="preserve">Page </w:t></w:r>' ...
                '<w:fldSimple w:instr="PAGE"><w:r>' rPr '<w:t>1</w:t></w:r></w:fldSimple>' ...
                '<w:r>' rPr '<w:t xml:space="preserve"> of </w:t></w:r>' ...
                '<w:fldSimple w:instr="NUMPAGES"><w:r>' rPr '<w:t>1</w:t></w:r></w:fldSimple>' ...
                '</w:p>' ...
                '</w:ftr>']);
        end

        function txt = footerRelsXml(~)
            %FOOTERRELSXML  Empty Relationships document for footer1.xml.
            %   The footer carries no embedded references; Word still
            %   requires the rels part to exist alongside the footer
            %   part to satisfy package validation.
            txt = char([ ...
                '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' ...
                '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">' ...
                '</Relationships>']);
        end

        function txt = stylesXml(~)
            sb = ['<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' ...
                '<w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">'];
            sb = [sb '<w:docDefaults>' ...
                '<w:rPrDefault><w:rPr>' ...
                '<w:rFonts w:ascii="Calibri" w:hAnsi="Calibri"/>' ...
                '<w:sz w:val="22"/><w:szCs w:val="22"/>' ...
                '</w:rPr></w:rPrDefault>' ...
                '<w:pPrDefault><w:pPr><w:spacing w:after="120" w:line="276" w:lineRule="auto"/></w:pPr></w:pPrDefault>' ...
                '</w:docDefaults>'];
            sb = [sb '<w:style w:type="paragraph" w:styleId="Normal" w:default="1">' ...
                '<w:name w:val="Normal"/></w:style>'];
            sb = [sb autotest.report.backends.OoxmlBackend.headingStyleXml(1, 32, 360, 200) ];
            sb = [sb autotest.report.backends.OoxmlBackend.headingStyleXml(2, 28, 240, 160) ];
            sb = [sb autotest.report.backends.OoxmlBackend.headingStyleXml(3, 24, 200, 140) ];
            sb = [sb '<w:style w:type="paragraph" w:styleId="TOC">' ...
                '<w:name w:val="TOC Heading"/><w:basedOn w:val="Normal"/></w:style>'];
            sb = [sb '</w:styles>'];
            txt = char(sb);
        end

        function txt = settingsXml(~)
            % updateFields=true tells Word to refresh the TOC field on
            % first open.  Critical for populated page numbers without
            % requiring the reader to manually update.
            txt = char([ ...
                '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' ...
                '<w:settings xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">' ...
                '<w:updateFields w:val="true"/>' ...
                '<w:compat><w:compatSetting w:name="compatibilityMode" w:uri="http://schemas.microsoft.com/office/word" w:val="15"/></w:compat>' ...
                '</w:settings>']);
        end

        function txt = contentTypesXml(~)
            % Phase 16 (Part B item 1): register footer1.xml so Word
            % loads it when the main section's sectPr references it.
            txt = char([ ...
                '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' ...
                '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">' ...
                '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>' ...
                '<Default Extension="xml" ContentType="application/xml"/>' ...
                '<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>' ...
                '<Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/>' ...
                '<Override PartName="/word/settings.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.settings+xml"/>' ...
                '<Override PartName="/word/footer1.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.footer+xml"/>' ...
                '</Types>']);
        end

        function txt = rootRelsXml(~)
            txt = char([ ...
                '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' ...
                '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">' ...
                '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>' ...
                '</Relationships>']);
        end

        function txt = docRelsXml(~)
            % Phase 16 (Part B item 1): the main section's sectPr
            % references the footer via r:id="rIdFooter".  This rel
            % entry is what binds that ID to the footer1.xml part.
            txt = char([ ...
                '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' ...
                '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">' ...
                '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>' ...
                '<Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/settings" Target="settings.xml"/>' ...
                '<Relationship Id="rIdFooter" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/footer" Target="footer1.xml"/>' ...
                '</Relationships>']);
        end
    end

    methods (Static, Access = private)
        function out = xmlEsc(text)
            % Escape &, <, >, ", '
            t = char(text);
            t = strrep(t, '&', '&amp;');
            t = strrep(t, '<', '&lt;');
            t = strrep(t, '>', '&gt;');
            t = strrep(t, '"', '&quot;');
            t = strrep(t, '''', '&apos;');
            out = t;
        end

        function s = cellXml(text, widthDxa, bold, shadeColor)
            tcPr = sprintf('<w:tcW w:w="%d" w:type="dxa"/>', widthDxa);
            if ~isempty(shadeColor)
                tcPr = [tcPr sprintf('<w:shd w:val="clear" w:color="auto" w:fill="%s"/>', shadeColor)];
            end
            tcPr = [tcPr ...
                '<w:tcMar>' ...
                '<w:top w:w="80" w:type="dxa"/>' ...
                '<w:left w:w="120" w:type="dxa"/>' ...
                '<w:bottom w:w="80" w:type="dxa"/>' ...
                '<w:right w:w="120" w:type="dxa"/>' ...
                '</w:tcMar>'];
            rpr = '';
            if bold, rpr = '<w:rPr><w:b/></w:rPr>'; end
            txtEsc = autotest.report.backends.OoxmlBackend.xmlEsc(text);
            s = ['<w:tc><w:tcPr>' tcPr '</w:tcPr>' ...
                 '<w:p><w:r>' rpr '<w:t xml:space="preserve">' txtEsc '</w:t></w:r></w:p>' ...
                 '</w:tc>'];
        end

        function out = headingStyleXml(level, size, before, after)
            out = sprintf([...
                '<w:style w:type="paragraph" w:styleId="Heading%d">' ...
                '<w:name w:val="heading %d"/>' ...
                '<w:basedOn w:val="Normal"/>' ...
                '<w:next w:val="Normal"/>' ...
                '<w:qFormat/>' ...
                '<w:pPr><w:spacing w:before="%d" w:after="%d"/><w:outlineLvl w:val="%d"/></w:pPr>' ...
                '<w:rPr><w:b/><w:sz w:val="%d"/><w:szCs w:val="%d"/></w:rPr>' ...
                '</w:style>'], ...
                level, level, before, after, level - 1, size, size);
        end

        function files = listAllFiles(stageDir)
            files = {};
            list = dir(fullfile(stageDir, '**', '*'));
            for i = 1:numel(list)
                d = list(i);
                if d.isdir, continue; end
                full = fullfile(d.folder, d.name);
                rel = strrep(full, [stageDir filesep], '');
                files{end+1} = rel; %#ok<AGROW>
            end
        end
    end
end
